### ISSUE TITLE
Runewarden Deryan

### ISSUE THREAD

**Issue by InsanitoTBC** [elysium-project/classic-bug-tracker#1000]
Hello.

I have been playing as a Blood Elf Priest and I have completed a quest called Runewarden Deryan (unfortunately I don't know how to get the IDs). For some reason the quest is still in a quest log as an incomplete quest.

I hope this helps.

Kindest regards,
InsanitoTBC (the in-game nickname is Metzelaar)

**Comment by namreeb** [comment]
This is the tracker for classic.  Please see https://github.com/elysium-project/tbc-bug-tracker/issues
