### ISSUE TITLE
Fall Damage Problem

### ISSUE THREAD

**Issue by Mooskie** [elysium-project/classic-bug-tracker#1001]
There's a bug with fall damage, sometimes even a short fall would result in the lost of the exact number of our current hp and would kill us

**Comment by Ziggy-QA** [comment]
@Mooskie can you please tell me anything else that could help me reproduce this? I play every day, and have not noticed a problem with fall damage.

**Comment by Mooskie** [comment]
@Ziggy-QA, i doesn't happen often, but sometimes fall damage deals exactly the amout of hp you have and kills you, i dont know if its location specific, I have encounter this bug north of Uther's Grave and in Feralas at the Yeti cave (the higher level ones, i forgot their name)

**Comment by Ziggy-QA** [comment]
I was not able to replicate this by taking fall damage in those locations. Could you maybe try and reproduce it? If you can, comment here exactly where and what you did, provide a screenshot of your combat log of the damage you have taken, and provide me information such as your class/spec/race/level.

In the meantime this issue will be closed pending additional information.
