### ISSUE TITLE
Quest: Metzen he Reindeer

### ISSUE THREAD

**Issue by TenyaI** [elysium-project/classic-bug-tracker#1004]
Hello, I am having a problem with the quest found in the title, I have taken the quest, completed it, but cannot give it in.
I have abandoned the quest, logged out and deleted the WDB folder, deactivated all my addons, retook the quest and made it again, and still cannot give it in after completion.
If it helps with anything, I have changed my faction from Horde to Alliance a while ago, but do not know if that could be the issue. Character name is Tenya. 
Thanks!

**Comment by RainElysium** [comment]
Please open a ticket in game and ask the GM to reset the quest for you. The quest is confirmed as working as intended - so its something on your end. Likely the race change as you mentioned.
