### ISSUE TITLE
 Bugs/Errors

### ISSUE THREAD

**Issue by Sagavin2720** [elysium-project/classic-bug-tracker#1005]
Hello, here are actually the bugs/errors that I found on your server!

1. In "all" locations, monsters recover very quickly and because of this some tasks are difficult to do, you can increase the time of their appearance by at least 3 minutes.
2. "All" monsters attack in melee not in the butt, but from a distance of 1-2 meters.
3. The problem with the chairs in the fortress of Stormwind ...
4. For some reason, it is impossible to inspect a character on the battlefield.
5. Premature aggro in magic mage arrows (the monster must attack only when damage is inflicted on it - such as with the ice arrow of the magician)
6. When using the teleport from the dwarf next to the portals (um island), the cooldown is periodically hung on the return stone.
7. An inconveniently located Christmas tree at the place of arrival (um island).
8. Installing fireworks (um island) does not work.
9. Portals in the capital near the gnome, do not work.
10. And the NPC itself Dwarf makes a teleport to where the return stone is installed (and not to the capitals themselves).
11. Chudoformer works on 1-2m from itself (should work when you enter it).
-------------------------------------------------------------------------------------------------------------------
Здравствуйте, вот собственно говоря те баги/ошибки, которые я нашёл на вашем сервере!

1. Во "всех" локациях, монстры очень быстро восстанавливаются и из-за этого некоторые задания трудно сделать, можете хотя бы на 3 минуты увеличить время их появления.
2. "Все" монстры атакует в ближнем бою не в притык, а с дистанции 1-2 метра.
3. Проблема со стульями в крепости Штормграда...
4. Почему-то бывает нельзя осматривать персонажа на поле боя.
5. Преждевременное агро у чародейских стрел мага (монстр должен нападать, только когда по нему будет нанесён урон - как например с ледяной стрелой мага)
6. При использование телепорта от гнома рядом с порталами (остров гм), переодически вешается кулдаун на камень возращения.
7. Неудобно расположенна ёлка на месте прибытия (остров гм).
8. Установка фейерверков (остров гм) не работает.
9. Порталы в столицы  возле гнома, не работают.
10. А сам нпс гном делает телепорт туда где установлен камень возращения (а не в сами столицы).
11. Чудоформер работает на 1-2м от самого себя (должен срабатывать, когда заходишь в него).

**Comment by Sagavin2720** [comment]
Screenshots/Скриншоты: 
![wowscrnshot_122218_185611](https://user-images.githubusercontent.com/46133965/50424059-2ffe8400-0891-11e9-804d-7bf3a5328c27.jpg)
![wowscrnshot_122218_205421](https://user-images.githubusercontent.com/46133965/50424060-30971a80-0891-11e9-9f67-147cebdc366d.jpg)
![wowscrnshot_122218_205425](https://user-images.githubusercontent.com/46133965/50424061-30971a80-0891-11e9-8338-850117dd651e.jpg)
![wowscrnshot_122218_205433](https://user-images.githubusercontent.com/46133965/50424062-30971a80-0891-11e9-882e-be069a6ab2ef.jpg)
![wowscrnshot_122418_123636](https://user-images.githubusercontent.com/46133965/50424063-30971a80-0891-11e9-9e1d-1406499eb593.jpg)
![wowscrnshot_122418_123930](https://user-images.githubusercontent.com/46133965/50424064-312fb100-0891-11e9-9d53-7fd576987261.jpg)
![wowscrnshot_122418_123952](https://user-images.githubusercontent.com/46133965/50424065-312fb100-0891-11e9-9e70-ec721f4a3f41.jpg)
![wowscrnshot_122418_211554](https://user-images.githubusercontent.com/46133965/50424066-31c84780-0891-11e9-8065-b8d97f96bb3c.jpg)
![wowscrnshot_122418_211557](https://user-images.githubusercontent.com/46133965/50424067-31c84780-0891-11e9-9470-941467a316b7.jpg)
![wowscrnshot_122418_214133](https://user-images.githubusercontent.com/46133965/50424068-31c84780-0891-11e9-9fa8-b75ce9d64186.jpg)
![wowscrnshot_122418_214149](https://user-images.githubusercontent.com/46133965/50424069-31c84780-0891-11e9-9bef-8dd1f7faf022.jpg)
![wowscrnshot_122418_214253](https://user-images.githubusercontent.com/46133965/50424070-3260de00-0891-11e9-8542-6a1b70280e76.jpg)
![wowscrnshot_122418_214918](https://user-images.githubusercontent.com/46133965/50424071-3260de00-0891-11e9-8f9a-29245c6f7f4d.jpg)
![wowscrnshot_122418_214922](https://user-images.githubusercontent.com/46133965/50424072-3260de00-0891-11e9-92a1-28538adff283.jpg)

**Comment by Gancked** [comment]
Is there a way to add that every time I come out of a BG i go to my hearthstone's place rather than where i was before entering?
