### ISSUE TITLE
Double xp tokens dont effect pet xp.

### ISSUE THREAD

**Issue by fatekills** [elysium-project/classic-bug-tracker#1016]
bought double xp tokens me and my cousin, decided to level hunters. the token doesn't effect the pet, which makes it almost impossible to lkevel hunter since they rely on pet so much and i outlevel him at double the speed, so I have to keep retaming new pet every 3-4 levels and its a big problem. I don't believe this was the intended way since it makes leveling, well, impossible and definitely not the way it was meant to be as hunter and fun. please look into this, thanks!

**Comment by fatekills** [comment]
So how do I know if Gms look at this?

**Comment by fatekills** [comment]
bump...

**Comment by ZicoQA** [comment]
This is not a bug. It is how the Token was made, only for the player. If you have suggestions about how it should work please post in our forums.
