### ISSUE TITLE
Line of sight of mobs

### ISSUE THREAD

**Issue by Dizlike05** [elysium-project/classic-bug-tracker#1022]
Hello ,  i don't have any footage ,but line of sight method of stoping mobs cast doesen't work , you can taest it by staring a orc/troll and go try this on a vile familliar

**Comment by ZicoQA** [comment]
I have done many tests and light of sight is working as intended. Mobs stop casting and follow me if I go out of sight. Could you tell me, has this happened on other mobs or just on the vile familliars?

**Comment by ZicoQA** [comment]
Can't follow through on ticket as player didn't specify
