### ISSUE TITLE
Improved Healthstone talent not working.

### ISSUE THREAD

**Issue by gh0st-GitHub** [elysium-project/classic-bug-tracker#1027]
I have a level 22 warlock named "Hasten"

He has the spell Create Healthstone (Minor) which creates a 100 HP healthstone.
http://classicdb.ch/?spell=6201

After taking 1/2 Improved Healthstone talent (10% more healing healthstone), it produced a 110 HP healthstone as expected.

After taking 2/2 Improved Healthstone Talent (20% more healing healthstone), it only produces a 100 HP healthstone.
It should produce a 120 HP healthstone.

I have another warlock and the talent works correctly on it. The talent is now completely not working on this warlock.

I don't know what circumstance created the bug. Relog, restart, delete WDB folder, none of them fix the issue.

**Comment by ZicoQA** [comment]
Closed as its fixed
