### ISSUE TITLE
Ledger from Tanaris

### ISSUE THREAD

**Issue by kvahlen** [elysium-project/classic-bug-tracker#1031]
I was doing Ledger from Tanaris with my two mates, we level together.

I, Thusadin could turn in the quest easily, but both my mates Bythor and Glarthir had the quest appear in a grey `"?", even tho they've collected all the items, and done the same things as I have.
They've also cleared their WDB folder, and one of them tried to borrow my PC to login with, after I turned it in but to no avail.
![image](https://user-images.githubusercontent.com/18743755/51007102-897bd980-1546-11e9-87aa-fdc08a48c6b8.png)
![image](https://user-images.githubusercontent.com/18743755/51007121-9ac4e600-1546-11e9-959f-5fabd231afdf.png)

How can they turn this quest in? 
Yours Truly,
Thusadin

**Comment by ZicoQA** [comment]
Did they have all the items in their bags when delivering? Sometimes people forget the items in the bank and the quest still shows you have everything

**Comment by ZicoQA** [comment]
No response for player. As this is not a comment bug closing the issue.
