### ISSUE TITLE
Ogre Warbeads

### ISSUE THREAD

**Issue by dfi34** [elysium-project/classic-bug-tracker#1035]
Item "Ogre Warbeads" for quest "Falrin's Vendetta" on all classic DB's has 80% chance drop. I've killed lots of ogres and it's definetly has no 80% chance drop

**Comment by ZicoQA** [comment]
According to WoWWiki, the droprate is as follows:
Outside of DM: 1/50
DM North: 1/10
LBRS: 1/7 

I tested in PTR and took me 255 mobs in dm north.
Since "lots" is not a statiscal value. I will say that this is blizzlike
