### ISSUE TITLE
Can't register a guild

### ISSUE THREAD

**Issue by SaintCherry** [elysium-project/classic-bug-tracker#1037]
Nothing happens after clicking 'register a guild' in the guild master's menu. The charter is fully signed.

**Comment by SangriaBoss** [comment]
Hi,

maybe can help but i had same issue until discovered it works only if the charter is in backpack (main bag).
Hope this helps you and devs.

Cheers

**Comment by SaintCherry** [comment]
I suppose it would help but devs fixed it already ^^ thank you!

**Comment by ZicoQA** [comment]
I will fixed this as it apparently has already been fixed
