### ISSUE TITLE
Cursed Darkhound marked as PvP

### ISSUE THREAD

**Issue by NiteKat** [elysium-project/classic-bug-tracker#1043]
There is a Cursed Darkhound mob on the road between Undercity and Silverpine Forest that is flagged PvP. Attacking this mob flags your character for PvP. Link to screenshot showing the mob: https://imgur.com/a/oUVxpzz

**Comment by ZicoQA** [comment]
This is a small bug on your client db. No mobs are showing to me like that.
Though I wouldn't worry much about this as the whole server is PVP. 
The most that killing a pvp mob would is put an alert that the region is being attacked.
