### ISSUE TITLE
Morwen - Bought Barkskin and not showing in spell book. NIghthaven 

### ISSUE THREAD

**Issue by Aragorn909** [elysium-project/classic-bug-tracker#1055]

**Comment by saltyqa** [comment]
@Aragorn909 did you try to resolve this through an in-game ticket?

**Comment by Aragorn909** [comment]
It’s not bugged anymore, I’m sorry I didn’t close the ticket.

Thomas Batson

________________________________

**Comment by saltyqa** [comment]
closing
