### ISSUE TITLE
Meeting stones don't work

### ISSUE THREAD

**Issue by FrostShock** [elysium-project/classic-bug-tracker#1060]
You can't use the meeting stones to find a group.
Also when hovering the mouse over them, it doesn't show the dungeon name and the dungeon level. It just says "Meeting stone"

**Comment by Ziggy-QA** [comment]
@FrostShock In vanilla, meeting stones do not work. It isnt until TBC that they are able to summon players.

Closed. This is blizzlike,

**Comment by leoni4** [comment]
@Ziggy-QA 
No it isn't _blizzlike_
In vanilla meeting stones wokr like LFG sustem:
"Clicking on meeting stone attach you to queue for this dungeon"

Later in TBC they modified it into Summoning Stone, and they added new whole LFG system
