### ISSUE TITLE
Hunter Pet Icon Always Green

### ISSUE THREAD

**Issue by chaospotato** [elysium-project/classic-bug-tracker#1065]
Hunter pets when you press C and look at the icon , its always smiley and green to indicate all is good. This happens with brand new pets, and long time pets. Really sucks because, as with me, I fed my newly tamed owl stacks of level 45 meat only to have it disappear while in a dungeon, ironically while speaking to a GM about the issue. It's a waste of resources and time hunting down pets, only to have them disappear. I have tried the standard WDB deletion 4x and no luck. The GM i spoke to said this has not been reported before....

Is there a fix for this?

**Comment by chaospotato** [comment]
Update: I was previously using the Nostralius client (as it was listed as an acceptable client) and for shiggles, I installed and started using the Elysium client - the problem went away and some of the other quest issues I was having also ended. So if you are using the Nost client, install the Ely client and it should solve a lot of your issues. The canned delete WDM and remove all addons doesn't seem to resolve issues that may be attached to the Nost client.

**Comment by saltyqa** [comment]
Closing as this is not an issue that needs attention for Elysium.
