### ISSUE TITLE
Fix Moira Bronzebeard loot drop rate

### ISSUE THREAD

**Issue by MrXanthios** [elysium-project/classic-bug-tracker#1088]
Moira Bronzebeard is almost exclusively dropping the High Priestess Boots. Out of 10 runs, she dropped High Priest Boots 9 times and once the Swiftwalker Boots, we are beyond unlucky rng. Her loot table is very simple, there are only four items and none of those item is something particular that justifies a way lower drop rate, they should all be around 25% and rotate regularly in her drop. The few information available on wowhead nowadays probably do not represent what was back in the days but they kind of support the idea of an equal drop chance between the 4 blues she can drop (https://www.wowhead.com/npc=8929/princess-moira-bronzebeard). This is not a hand of justice/ironfoe kind of situation, and healers shouldn't struggle like that to have some simple gloves.

**Comment by ZicoQA** [comment]
That's Rng issue for you.. killed her 3 times she dropped 3 different loot for me.
