### ISSUE TITLE
Weapon/Defense skillup rate

### ISSUE THREAD

**Issue by Dezolis** [elysium-project/classic-bug-tracker#1091]
As a lvl 28 rogue with an Int buff (to increase skilI up chance) had a 60 healer friend heal me while I had 5 mobs 3 levels higher than me beat on me for at least 1000 hits if not more and I am still at 139/140 Defense. I never remembered having to take that many hits to to max that skill in Classic. 

Also on my 56 hunter, both characters leveled by grinding and instance/mandatory quests only, and they are always 5-10 below their skill cap. I end up leveling up and increasing the skill cap before I can get weapon and defense skills maxed. This was simply not the case in vanilla. It was slow, but this seems almost 5x slower than classic.

**Comment by cmdrkeen84** [comment]
the mechanics of vanilla crushing blows by any mob 3 lvls or higher than you did not count towards defensive skill if I remember correctly. you'd be better off having multiple low lvl mobs beating on you. while naked.

**Comment by saltyqa** [comment]
Closing as this is not technically an issue to be addressed.
