### ISSUE TITLE
Im at war with friendly factions

### ISSUE THREAD

**Issue by Nafswe** [elysium-project/classic-bug-tracker#1102]
I have farmd reputation with Timbermaw Hold for a while now and when i can't remember if it hapend after i accepted the quest "Runecloth" or after i became friendly with them but now it says in the reputation tab that im at war with them.

Now i can't interact with them but only kill them, a GM sent me here so pleas help me.

**Comment by Gibblewilt** [comment]
Hi, this might be normal. If the reputation bar shows 'neutral' or above you can disable the 'at war' mode by clicking on the crossed swords icon. For factions where you start with low reputation this is not done upon reaching neutral.

**Comment by McMittens** [comment]
@Nafswe Did the method mentioned above resolve this issue for you?

**Comment by Nafswe** [comment]
Yes i have tried it now and it did work.
Thank you so much for the help.
________________________________
Från: McMittens <notifications@github.com>
Skickat: den 2 mars 2019 16:18
Till: elysium-project/classic-bug-tracker
Kopia: Nafswe; Mention
Ämne: Re: [elysium-project/classic-bug-tracker] Im at war with friendly factions (#1102)


@Nafswe<https://github.com/Nafswe> Did the method mentioned above resolve this issue for you?
