### ISSUE TITLE
hunter pet snarler bug

### ISSUE THREAD

**Issue by alfavhunter** [elysium-project/classic-bug-tracker#1103]
so in vanilla Snarler had a lot of base bonus resistances even after taming him. I have deleted my Wdb (edit: and fully exited and reentered the game after doing so) folder and disabled all addons and he still does not have the bonus resistances he is supposed to have. was this an intended change or is it a bug?

if it is a bug please fix this as it is not vanilla like.

![wowscrnshot_022619_161222](https://user-images.githubusercontent.com/44563844/53455974-564fb580-39e1-11e9-9b8b-ebacd0ebf790.jpg)

for reference on the npc/hunter pet in question follow the link below.

https://classicdb.ch/?npc=5356#comments

**Comment by ZicoQA** [comment]
This is working as intended. The mob was fixed after patch 1.10 together with all the rare wolves.
