### ISSUE TITLE
Can't send and receive /w and /s messages

### ISSUE THREAD

**Issue by zarniuup** [elysium-project/classic-bug-tracker#1301]
Hi,
I can't send /w and /s messages. I also can't receive /w messages.
My guild master Guildmasta also said he has similar problems.
My chat channels also don't work. I see no messages in the channels and when I use them I get no responses.
I've tried deleting the WDB folder and reinstalling the client.

![WoWScrnShot_090419_220817](https://user-images.githubusercontent.com/54911529/64284084-700a2080-cf61-11e9-9a45-fa85cc053279.jpg)

![WoWScrnShot_090419_221959](https://user-images.githubusercontent.com/54911529/64284514-6f25be80-cf62-11e9-996c-3d3d6fc27ecb.jpg)

Help would be appreciated.
Thanks

**Comment by Trunkscool** [comment]
I also have this problem, no one is responding. Its really frustrating

**Comment by zarniuup** [comment]
![WoWScrnShot_090419_221959](https://user-images.githubusercontent.com/54911529/64284514-6f25be80-cf62-11e9-996c-3d3d6fc27ecb.jpg)

**Comment by zarniuup** [comment]
Yes. I can't play like this. If no one helps i guess i'll have to quit.
