### ISSUE TITLE
Escort quest: Ending the World - Demolitionist Legoso not moving

### ISSUE THREAD

**Issue by Mountainweed** [elysium-project/classic-bug-tracker#1311]
Summary:
After accepting the quest, "Ending the World", Legoso stays put. 

Steps to Reproduce:
- Accept the quest, "Ending the World"

Expected Results:
-Legoso starts moving

Actual Result:
-Demolitionist Legoso doesn't move so we cant follow him. We need him to destroy Vector Coil. Also Sironas cant be attacked in any way.

**Comment by Mountainweed** [comment]
Bug already reported

**Comment by Zeatur** [comment]
still don not work
