### ISSUE TITLE
Line of sight not being blocked by objects.

### ISSUE THREAD

**Issue by StephenLynx** [elysium-project/classic-bug-tracker#1425]
Trees and such are not blocking line of sight as they should. Walls do block, though. But I am yet to find regular object that blocks movement but doesn't block ranged attacks.

**Comment by Gamemechanicwow** [comment]
Not a bug. This is blizzlike behaviour. Other projects have custom LOS - where trees etc block los, but vanilla had not.

**Comment by StephenLynx** [comment]
Huh. That's the first time I get bamboozled by something like that.
