### ISSUE TITLE
Gnomish Mind Control Cap doesn't use spells, only white attacks

### ISSUE THREAD

**Issue by Deluxolol** [elysium-project/classic-bug-tracker#371]
The Engineering helmet, Gnomisch Mind Control Cap doesn't give the mind controlled target the ability to cast spells, it just white hit the target ur telling it to attack.

**Comment by Terranzin** [comment]
Hello,

Regarding the "pet"-bar you get, this should only consist of the basic commands without abilities. Do you mean that the user does not use any of it´s spells when being controlled?

**Comment by Deluxolol** [comment]
the pet bar should indeed by empty with spells, but the controlled target should use spells own their own, healing the master, dpsing the target and so on.

Examples:
https://youtu.be/4sj21TAmQ-M?t=502 -- Warrior using intercept and other abilities when he got mind controlled by the cap.

https://youtu.be/4sj21TAmQ-M?t=1086 -- Priest healing the master and dpsing the target.

**Comment by Thenari** [comment]
I dont know shit about engineering, can someone confirm if this is still happening?

**Comment by Thenari** [comment]
I was reminded about this when in ZG, jindo has a mind control mechanic often when im a warlock the worst i do is drain soul someone with full health haha doing no dmg

But that means there is a programmed mind control script from each class which i didnt understand when i first saw this, whenever a priest MC me they usually make me jump off an edge into something inconvienent. The gnomish one is supposed to just make your character go through its class specific script i think what this post is implying.

I know the warrior one is real deadly. Our main tank on jindo got brain washed, charged into the ranges area and aoe feared... we now clear all the zombie dancers as we wiped when they pulled lol
