### ISSUE TITLE
lockpick

### ISSUE THREAD

**Issue by Qualthalas** [elysium-project/classic-bug-tracker#409]
I found a guide on the elysium [forum](https://forum.elysium-project.org/topic/28031-lockpicking-guide-1-300/) and it says "You can first start with unlocking the door into the instances but this can only be done about every 10 minutes per door. If you don't wait then it doesn't count as skill up." - I tried to do this at the Scarlet Instance doors, but only the first 2 attempt counted as skill up, none of the further tries ( it was on last Sunday ) and I couldn't get a single skill up from there, my lockpicking skill is 201 and the door shows up as "green" so it should still work. I tried disabling my addons, deleting my WDB folder, restarting my client etc.

**Comment by tubiakou** [comment]
The linked forum guide mentioned above appears to be cross-posted in various places.  E.g. : [This Guide](http://www.blizzardguides.com/wow_1-300_lockpicking_guide.html) is the exact same guide.  I cannot verify its accuracy or correctness.

What I can verify is that after my first successful attempt to increase lockpicking on a Scarlet Monastary Door, no further attempts worked (on PTR).  I performed the following test steps (note that I'm showing what the times were for each step, to show how much time was waited)

1. **15:21:00** Took a level 60 rogue with 190 lockpicking skill to Scarlet Monastary.
2. **15:22:47** Picked a SM door.  My lockpicking skill increased from 190 to 191.
3. **15:25:01** Picked the same door.  My lockpicking skill remained unchanged.
4. **15:26:04** Set lockpicking skill to 201 (as mentioned by the OP).
5. **15:31:05** Picked the same door.  Skill level unchanged.
6. **15:37:29** Picked the same door.  Skill level unchanged.
7. **15:44:13** Set lockpicking skill to 190.
8. **15:45:30** Picked SM door.  Skill level unchanged.
9. **18:58:55** Picked SM door.  Skill level unchanged.

So, with various attempts ranging from a few minutes to over 3 hours after my initial (successful) attempt, no further attempt resulted in increasing my skill level.  This with skill levels at both 190 and 201.

There are various references in period lockpicking guides (_i.e._ originally written between 2003 and 2006) that indicate doors can be used (often specifically referencing Scarlet Monastary) repeatedly to level lockpicking up to at least 225.  These include:
- https://gamebanana.com/tuts/5021
- https://www.ironsongtribe.com/Thread-Zlinka-s-lockpicking-guide

So I believe it reasonable to assume that there is a bug occurring here, if the intent is to actually mimic Vanilla Retail WoW.  Marking this issue as confirmed, subject to further investigation.

**Comment by Thenari** [comment]
Someone check if this can be closed.

**Comment by Thenari** [comment]
I guess i can be that someone and check :stuck_out_tongue_winking_eye:
