### ISSUE TITLE
Goblin Engineering Trainer in gadgetzan eats gold

### ISSUE THREAD

**Issue by Tiamat114** [elysium-project/classic-bug-tracker#424]
Apparently if you are crafting and spam click learn on the Engineering recipes for 260 from the trainer in gadget, it says "another action is in progress" but takes your money anyway each click because they are not instantly learned recipes, and need a cast time. So now I'm out a bunch of gold, yay. Obviously it should not be taking away gold with each click if the spell is unable to be channeled, or just make the recipes instant to learn like most other trainer sold recipes.

**Comment by Navashed** [comment]
I was not able to reproduce this issue.

The NPC you are talking about is Nixx Sprocketspring (8126) correct? I was able to learn everything he had available while crafting without triggering any "Another action is in progress" error text. None appeared to require a cast time.

Could you provide more information about which recipes you were trying to learn at the time this occurred?

**Comment by Inomares** [comment]
Though I cannot remember the exact names, I can confirm this happened to me as well. It was some of the higher-end engineering recipes, which have a cast bar for you to learn them. I believe they will also incur a charge if you are mounted when attempting to learn them.

**Comment by shenna-elysium** [comment]
@Navashed try to do it while using Stealth.

**Comment by Navashed** [comment]
Tested Stealth, worked correctly.

I need an example of a recipe which has a cast time to learn. Everything Nixx Sprocketspring had to offer me as a 300 Goblin Engineer was instant cast and therefore unaffected by this potential issue.

**Comment by Tiamat114** [comment]
I actually have a hunter who just hit the point of learning the recipes in
question and I ran down to tanaris to test it. I can simply replicate the
issue it seems by learning "Thorium Grenade" or "Thorium Widget" as they
are both channeled spells by simply moving and interrupting the cast; or by
being in the process of crafting he takes your money but the spell can't be
channeled. I left Thorium grenades unlearned in case you want a video of
the issue or something.

**Comment by Lightsockie** [comment]
They're are prolly talking about Buzzek, not Nixx. Learned his stuff earlier and some of them did indeed require channeling (meaning if I moved I wouldn't have learned anything)

**Comment by Thenari** [comment]
this is real old lets see if its been fixed yet

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40107741-10ccea42-58c7-11e8-914e-bf6756e882b6.png)

weird how they are called schematics

**Comment by Thenari** [comment]
yep mashed the learn button and watched the money disappear :P just be patient

this isnt a super vital bug but maybe itll get worked on eventually
