### ISSUE TITLE
[AV] Archers respawn

### ISSUE THREAD

**Issue by Fl0ux** [elysium-project/classic-bug-tracker#438]
Frostwolf side, archers in the two towers near the Drek'Thar's dungeon do not respawn. The towers were not on fire.

**Comment by Navashed** [comment]
The archers were observed respawning even while the tower was capped (but not yet on fire). This behavior is incorrect. The archers should not respawn while the tower is capped.

Did you mean to say "the archers in the two towers near Drek'Thar are not supposed to respawn?"

**Comment by Fl0ux** [comment]
Strange... Towers were not capped and archers were not respawning.
