### ISSUE TITLE
Fishing loot missing

### ISSUE THREAD

**Issue by bk187** [elysium-project/classic-bug-tracker#484]
Sometimes after I make succesful catch the loot window is empty. It should always be something if the catch is succesful.

**Comment by nexiros** [comment]
Same happening to me. Which might be contributing to the bad fish rate of certain fish. Please can you fix this, it happens VERY frequently. Will calculate how many missing loot I get in next hour.

**Comment by nexiros** [comment]
Within that hour I had 18 missing loot.

**Comment by Navashed** [comment]
Does it happen in every zone? Which zones have you observed it in? Would you estimate the chance of this occurring is about 5%?

**Comment by nexiros** [comment]
Roughly 129.5 on average fishes I catch per hour in multiple zones, namely, Azshara, Feralas, Tanaris, Moonglade. On average I calculate 19 missed catches per hour over 6 hours worth of recording misses.
I have a feeling thats around 15% rounded up. So not quite the 5% quoted. Also commented on the Winter Squid post. Please check that.

**Comment by Navashed** [comment]
The drop chances of all the items on the loot table for Azshara do not add up to 100% (they add up to ~94%). I assume this would be responsible for a ~6% chance of getting no loot. However, in the other thread (#476) we have established that the loot tables I am viewing are not necessarily correct, so this may not be the case.

**Comment by nexiros** [comment]
Yeh around 6% would be great. But getting around 20 misses per hour isn't really 6%. It's more than double that atm from the times I've been there. Maybe you could check its 6%. Dunno how easy that is.

**Comment by bk187** [comment]
Well you can say whatever you want but every time I did succesful fish on old Vanilla retail I don't remember my loot window being empty. So it's obviously a bug.

**Comment by Navashed** [comment]
Yes, obviously if the loot table does not add up to 100% then that is a bug. That's what I was saying.

**Comment by Inomares** [comment]
Appears to also affect Western & Eastern Plaguelands. Seems like it's just all high level zones. Definitely more than 5% missing in all the high level zones, seems more like every third cast or so.

**Comment by Thenari** [comment]
This is quite old now. Ill ask if this has been touched on and can be closed.
