### ISSUE TITLE
Blind Hunter (Rare Spawn Bat) Razorfen Kraul - As A Hunter Pet

### ISSUE THREAD

**Issue by Catlynjenner** [elysium-project/classic-bug-tracker#545]
Bat is acting immune to all CC and should act like a normal bat pet. Apologize for wasting your time on the previous post and saying it was just the normal instance bat. It is the rare spawn bat and a few players are using it in pvp because of the fact you can't CC it.

**Comment by Navashed** [comment]
Confirmed.

Creature 4425 - Blind Hunter retains its immunities to CC after being tamed. No pet should retain these immunities.
