### ISSUE TITLE
[Alterac Valley] Ivus Issues

### ISSUE THREAD

**Issue by greezli** [elysium-project/classic-bug-tracker#564]
Ivus is broken he wont move from mid at all .... if he got pulled he kill agro target and back .. and ally can't upgrade units atll .... while horde have icelord who tush to AS straight away ally have dumb ivus... horde has elite guards ally have simple one ... fair? please fix :D

**Comment by Catlynjenner** [comment]
Alterac Valley, itself has a lot of complications. First off, the flip flopping from spawning Korrak @ the 30min. or the 2 hour mark in the battleground in blizzard retail it was never flipped flopped around and it was always at the 2 hour mark regardless. Secondly, the field of strife alliance and horde npcs fighting should be switched around as of now horde field of strife are grouped up fighting close to belinda and alliance is grouped up npcs are fighting next to galv. And as stated prior mob pathing such in this case would be Ivus needs reworked. Mob pathing sometimes even seems "glitchy" where it feels like the mob teleports to you. And yes more I've encountered Ivus to just sit and path in a small circle or stand still in the field of strife.

**Comment by Inomares** [comment]
This also happens to Lokholar just FYI. Might be related to him pulling aggro very early on, but I've only seen it happen a couple of times so it's hard to tell what the common denominator was.

**Comment by Thenari** [comment]
Aww oops i unassigned gip :s @Giperionn sorry idk how to undo!

**Comment by Thenari** [comment]
this is old as heck and hasnt been touched i have removed high priority cause I have heard no tickets claiming this issue
