### ISSUE TITLE
Warden for PPC arch causing PPC vanilla client to crash on character loading

### ISSUE THREAD

**Issue by avijoni** [elysium-project/classic-bug-tracker#571]
I've been trying to play wow 1.12.1 with my powermac g5(11.2 model), but cannot get past character retrieving. After investing some time and searching for the problem, I found out it is the problem with the warden for ppc. I had some extended conversation with Fulzamoth on discord about the issue. He suggested me to open the ticket, so at least the dev team get aware of the issue. So here it is. The problem with ppc clients is warden for ppc, which is missing or not working correctly. 
My system: mac 11.2, dual g5 2.3Ghz, 10gb ram, 160gb hdd, nvidia quadro fx 4500 or nvidia gt6600 :)

**Comment by Thenari** [comment]
this.... doesnt super feel like something i can test :/

did you ever get this to work?

**Comment by avijoni** [comment]
Nope. I never managed to get it to work on any vanilla private. But on some private TBC realms, I could play with mac ppc TBC client. Everything worked like a charm.
