### ISSUE TITLE
WSG charge bug

### ISSUE THREAD

**Issue by reddragons** [elysium-project/classic-bug-tracker#578]
Please fix the bug in WSG that makes a warrior run through half the base around ramp and tunnels. Happens too often. What's up with that?

**Comment by YaboyJimmyrustle** [comment]
If possible, please try to get video proof of this in action. Player names abusing this would also be useful, but know that unless we have hard evidence of abuse we won't be able to narrow down when and where the bug occurs. This helps us pin down what error may be happening in the code to result in the bug in-game.

**Comment by WobLight** [comment]
I think that's related to a bigger issue in Warsong Gulch: things tend to fall through the ground.
![screenshot_20180519_091057](https://user-images.githubusercontent.com/26815207/40266049-8b8ce640-5b44-11e8-95b6-4d818a7f5c7e.png)
This spot in the screenshot has particularly bad reputation as many flags got dropped here and fall to tunnel (same as charge bug). Also happens on the ground near tree logs (part of them is underground) and on tree logs (flag fall through to the ground).
