### ISSUE TITLE
AV Loot Issues

### ISSUE THREAD

**Issue by UmbraUnda** [elysium-project/classic-bug-tracker#585]
Why is it that I can't NEED roll plate gear in dungeons but in AV I can?  How is that fair for all players?

I'm so sick and tired of doing AV just for a Frost Runed Headdress off Ice Lord (pre-bis)... every time it drops another class need rolls (ninja) and I (or any other mage) never get it.  As if that weren't bad enough, these very same people who don't really need the gear, laugh in my face telling me how the vendor gold is gonna be so nice.  And when I ask people not to need roll, they verbally harass me and proceed to ninja the gear anyways with joyful content in stealing good gear from me and other players.  This is cruel and toxic....

I've been ninja'd for the last time - THIS HAS GOT TO BE FIXED!  I refuse to do AV until this issue is resolved!

I reported one occurrence today and the GM didn't even care and tried to generalize the situation as a simple player dispute.  THIS IS NOT A DISPUTE, THIS IS ABUSE AND TOXIC VERBAL HARRASSMENT, ITS GOTTA STOP! HOTFIX NEED ROLLS IN AV SO THAT ONLY APPROPRIATE CLASSES CAN NEED ROLL, not this BS ffa.  PLEASE!

**Comment by UmbraUnda** [comment]
Thanks for your feedback.  I will screenshot next time it happens - I should have before really after the many times this has happened.  I agree with and appreciate your proposal to the dev team - hope it get resolved soon.  

When I have enough screen shots, should I post them here or report to GMs?

**Comment by YaboyJimmyrustle** [comment]
You should post those pictures here so they are affiliated with the report and there's no way to link them in a ticket in-game. With those in this report I can refer back to the post when bringing it to the attention of the devs.

I greatly appreciate your patience with this issue.
