### ISSUE TITLE
Mindflay on fully debuffed targets

### ISSUE THREAD

**Issue by Healjuu** [elysium-project/classic-bug-tracker#589]
Mind flay is not doing damage on targets with 8 debuffs. It takes your mana as if casted. But does 0 damage. It is supposed to not apply the debuff if the mob or target is fully debuffed but still continue to do damage. The damage and slowing effect are 2 different parts of the spell. Where even if the spell component of the snare is not showing up the damage should tick.

**Comment by shenna-elysium** [comment]
#prayforshadowpriests

**Comment by Inomares** [comment]
I'm not sure this is working correctly. Like Healjuu says, it is supposed to still apply damage but not apply a debuff if the target has 16 debuffs (and mind flay, like other channels such as drain life, should be pretty low prio).

Right now, Mind Flay seems to have been given a super high prio, and seems to always apply to the target even if they are at 16 debuff slots (forcefully removing something else).

**Comment by Thenari** [comment]
I think i heard @drozdez was working on this, any update?

**Comment by drozdez** [comment]
No, still have no ideas how to fix it(

**Comment by Thenari** [comment]
Long long time ago.
