### ISSUE TITLE
Dustwallow Marsh

### ISSUE THREAD

**Issue by Fzacist** [elysium-project/classic-bug-tracker#608]
North East corner of Dustwallow Marsh there are 3 coastal islands there are supposed to be murlocs on. Only one of them is currently spawning anything. Also directly below the highest island that is currently spawning stuff there is a pathway away from the beach that leads to a small camp in the woods that is supposed to have murlocs. If you would please fix this issue I would greatly appreciate it.

**Comment by YaboyJimmyrustle** [comment]
The camp inland just north of Swamplight Manor is empty as is the island off the coast directly northeast of Swamplight Manor. We will work on populating these islands as soon as possible.

![vacant murloc camp](https://user-images.githubusercontent.com/36592168/38460104-578ecca2-3a68-11e8-847e-09cd98d46cb0.png)
![vacant murloc island](https://user-images.githubusercontent.com/36592168/38460105-57a2647e-3a68-11e8-831e-f32513efe0ed.png)

**Comment by Thenari** [comment]
I was here like a week ago finishing up the skull of impending doom novelty offhand quest chain. looks like it got fixed?
