### ISSUE TITLE
Ravager (Multiple bugs)

### ISSUE THREAD

**Issue by Hanzemon** [elysium-project/classic-bug-tracker#614]
The spell "[Bladestorm](https://classicdb.ch/?spell=9632)" from "[Ravager](https://classicdb.ch/?item=7717)" gets cancelled if triggered while moving (or jumping).

As you can see in [Bladestorm's description](https://classicdb.ch/?spell=9632) the effect n.2 is "(6) Apply Aura n.26: Root" which roots(cc) you unless you cancel the channel manually or cast another spell.

Somehow the Aura: n.26: Root gets cancelled as well as Bladestorm damage and visuals i̶f̶ ̶t̶h̶e̶ ̶p̶l̶a̶y̶e̶r̶ ̶w̶a̶s̶ ̶m̶o̶v̶i̶n̶g̶ ̶o̶r̶ ̶j̶u̶m̶p̶i̶n̶g̶ ̶w̶h̶e̶n̶ ̶i̶t̶ ̶w̶a̶s̶ ̶f̶i̶r̶s̶t̶ ̶t̶r̶i̶g̶g̶e̶r̶e̶d̶ or the target you attacked to **proc** it happens to die.

*Edit: ...if any other action is performed within 0.3s (aprox.) after you start bladestorming, such as moving or jumping.

 Additionally I made a macro that prevents using any spell (specifically "Wing Clip, Counterattack or Mongoose Bite") if my character is **Bladestorming**, this has worked well so far, except when I use it within those 0.3s in which the **bug** that allows you to cancel it by moving occurs, also cancelling it, This means that the macro doesn't detect "Bladestorm" within that period of time.  Using this information we could assume that [Bladestorm](https://classicdb.ch/?spell=9632)  somehow has a delay to apply its **instant** components  and this delay is the bug itself.

 Now about the part that makes it get cancelled when the target you were targeting the moment it procs  **dies** is also a bug, we can see in [this video of retail wow](https://www.youtube.com/watch?v=NPMpjuu9XF8) how the player's targets die on 4 different occasions while **Bladestorming** and it doesn't get cancelled in any of them.

**Comment by Navashed** [comment]
Confirmed, both bugs.

1) Spell 9632 - Bladestorm gets cancelled if the player is moving a moment after it procs. This should not happen, it should root the player instantly upon application. The Bladestorm buff was observed to apply instantly upon melee hit without delay but its root component appears not to apply immediately, likely the source of this issue.

2) Spell 9632 - Bladestorm gets cancelled if the target dies, either on the proc or during the bladestorm. Strange.

**Comment by Mumfo** [comment]
Can confirm, Ravager not blizzlike.

**Comment by Hanzemon** [comment]
So sad I lost faith on this issue being solved and moved to kronos lll, for those who will use **Ravager** in the future: you can remember me as a hero. Att: Ahren Lvl 44 Night Elf Hunter, ceased **Leader** of **<Plated Wings>**.

**Comment by Hanzemon** [comment]
I'm back with my hunter, Is this ever going to get solved ? :D I'm really excited about the concep of this item!

**Comment by Thenari** [comment]
some shoddy work here lol lets close this one as a duplicate

**Comment by Thenari** [comment]
#804
