### ISSUE TITLE
Shimmering Gloves sold by Zizzek does not give random enchantment

### ISSUE THREAD

**Issue by Inomares** [elysium-project/classic-bug-tracker#616]
Zizzek (3572) in Ratchet sells Shimmering Gloves (6565) which are supposed to have a random enchantment:
https://i.imgur.com/uxCjCuh.png

However after buying, the item is not given a suffix nor any stats: 
https://i.imgur.com/8m1oVce.png

**Comment by Giperionn** [comment]
Hello @Inomares . Thank you for reporting. Fix will be available on next server update.
![Image](https://image.prntscr.com/image/BqRwFw5ORvaHeA7n0LZJeA.png)

**Comment by Thenari** [comment]
yo this needs to be double checked lol

**Comment by Thenari** [comment]
lmao so it was gip who did it, +14 agi +15 str on a lvl 17 pair of gloves! and the vendor literally only ever sells of the tiger :P

**Comment by Vasquez-QA** [comment]
This has been fixed on live - Closing Report.
