### ISSUE TITLE
Fishing: Nightfin & Sunscale drop rates are incorrect

### ISSUE THREAD

**Issue by Inomares** [elysium-project/classic-bug-tracker#618]
## Current behaviour:
Sunscale seems to drop almost 24 hours a day, and always drops more frequently than Nightfin except during night (which starts at the wrong time, exact time unknown). Daytime (noon + a few hours) drop rate is unknown to me.

Fishing at 00-03 seems to give around 10-15% Nightfin, which is roughly 1/3 to 1/2 of expected drop rate at this time. Sunscale seems to still drop up until around 2 AM. After Sunscale stops dropping around 2 AM, amount of empty loot windows increase drastically, perhaps indicating that the switch to nightfins just removes the sunscales without adding in the extra nightfins (issue #484 might be relevant). If "full night" with 100% nightfin (~30% drop) is actually in the game, then it's not occurring at 00:00+ as it should. (I have not for instance tried fishing at 4-5 AM).

I don't have a full list of inaccuracies, but I list below how it should work. 

## Expected behaviour:
There is no officially documented behaviour, and some sources _claim_ it has changed at some unspecified time(s). That being said, here's a quick rundown of how these two fishes apparently should work, gathered from various thottbot comments etc.:

Their drop rate depends on server time.

|Time of Day   |Nightfin est. %|Sunscale est.%|
|--------------|-----------|-----------|
|06:00 - 12:00|40%       |60%        |
|12:00 - 18:00|0%            |100%        |
|18:00 - 00:00|60%       |40%        |
|00:00 - 06:00|100%       |0%             |

Please note that the estimated percentages are when either Nightfin or Sunscale actually drop, meaning you don't have a 100% chance _per cast_. Their combined drop rate appears to equal roughly 30% in the high level zones (Feralas and above).

Please also note that the 40/60% estimates are, just that, estimates. There doesn't seem to be a big difference, but noticable enough that multiple commenters at least thought they had noticed it.

## Sources:
https://web.archive.org/web/20080207180712/http://thottbot.com:80/?i=Raw%20Nightfin%20Snapper

There are multiple good comments there, but you'll want to be careful to not look at comments that are too new or too old (since snapshot of the comments was taken 2008 and Blizzard changed fishing during mid-TBC, and some of the older commenters were mostly speculating blindly without providing times or numbers to back up their claims). Here are a ton of comments, with the relevant info highlighted, that show and support this theory:

**Supporting day being 100% sunscale and after 6pm being a mix, favoring Nightfin:**
https://i.imgur.com/1ZAAnFw.png
https://i.imgur.com/iIqVjmK.png
https://i.imgur.com/epM0KiN.png

**Supporting nighttime being 100% (or close to) Nightfin:**
https://i.imgur.com/HmwYgPD.png
https://i.imgur.com/GnMbUD8.png (the last paragraph is also important here, as it notes that he did indeed not catch sunscales during this time)
https://i.imgur.com/DRwGWux.png - this one basically confirms 00:00 as the hard "switch" to pure Nightfin.
https://i.imgur.com/epM0KiN.png (This image is intentionally a duplicate of the last section)

**General theory being presented, times at the point of his comment not fully known:**
https://i.imgur.com/ss2bSgm.png

**Supporting noon being rough start time for "day":**
https://i.imgur.com/d1FUHNJ.png (this one is shaky, but it shows nightfin still kinda dropped at almost 11 AM which is pretty damn close to noon)

**Supporting general theory, claiming he has caught nightfin (very rarely) at noon but never sunscale at night:**
https://i.imgur.com/AIdGvNR.png

**Supporting 12:00-18:00 as 100% sunscale - but poster also thinks that this may not always have been the case earlier during vanilla's lifespan:**
https://i.imgur.com/cKFaGRt.png

**Noting that nightfin is more common than sunscale during evening, and vice versa, even though both still drop:**
https://i.imgur.com/fzqhKeb.png
https://i.imgur.com/OKlIpo0.png - this one also solidly supports the general theory

**Comment by Navashed** [comment]
Fishing loot tables are known to be incorrect. Unfortunately a definitive fix in the near future is unlikely.

I will mark this issue as confirmed out of respect for the work you've put into this topic and the information you have compiled here; all other issues about fishing loot tables I will mark as duplicates and close.
