### ISSUE TITLE
Game Objects not spawning in fatigue / oceanic areas

### ISSUE THREAD

**Issue by Navashed** [elysium-project/classic-bug-tracker#632]
Object 2744 - Giant Clam is supposed to spawn abundantly in the deep, fatigue area of the Vile Reef. Currently there are only a few spawn points, all located outside of fatigue, which makes the quest Pearl Diving (Quest 705) very tedious.

Monstrous Crawler (Creature 1088) and Sawtooth Snapper (Creature 1087) are supposed to spawn abundantly in The Forbidding Sea off the coast of Swamp of Sorrows, particularly around the islands at ~94, 83.

Roland Geardabbler (NPC 8394) is supposed to be in the captain's quarters of the sunken ship in the Ruined Reaches off the southern coast of Azshara. There are no coordinates in the Ruined Reaches that I can observe.

I think all of these missing game objects are due to their placement in unusual zones and subzones off of coasts or in deep water.

**Comment by Thenari** [comment]
a lot of Azshara was unfinished when the game released so the whole ship wrecked crew and naga attack is left over pieces, no quest rewards, missing npcs, buggy script.

its just a relic and this isnt that big of a deal if a npc isnt there, theres no connections to him, he doesnt say anything funny. this is very low priorty to fix


the crocs and crabs though do you know what patch they were added to the islands, i went east of SoS and saw lots of neat terrain that has no mobs in it.

I'm guessing it was populated later

**Comment by Thenari** [comment]
the clams also may of been added to a later patch, after they realized how much of a pain it is to get blue pearls lol
