### ISSUE TITLE
Mantle of Dawn quest in EPL

### ISSUE THREAD

**Issue by Linabeanie** [elysium-project/classic-bug-tracker#657]
Mantle of Dawn quest = turn in 10 argent dawn valor token to exchange for the shoulder enchant + 5 to all resist, i got the 57silver but not the shoulder enchant. Help !?

Quest giver : QUatermaster Miranda Breechlock

**Comment by Thenari** [comment]
lmao yeah i just power used 800+ tokens to get revered on a fresh character

was pretty sure you can buy the +5 resist ones once you hit revered
so i did, i bought one of each type

then i did the quest gave her 10 tokens (worth 250rep) and in return

she gave me 100 rep and 57silver lol

![image](https://user-images.githubusercontent.com/38762769/40038848-1b85f8ce-57e2-11e8-9b2b-688ae7be6540.png)

**Comment by Thenari** [comment]
I think this might be a patch related thing, we exist in patch 1.12 for most purposes but quests are based on 1.7 right now... lets look into that theory

**Comment by drozdez** [comment]
I can be wrong, but there's no any enchants, that can give +5 to all resists
https://classicdb.ch/?npc=11536
Just watch into the list of her goods

**Comment by drozdez** [comment]
Also i found, that this Quatermaster's quest doesn't give enchancemets. Only money and reputation https://classicdb.ch/?quest=5513

**Comment by Thenari** [comment]
I actually got my AD rep to revered and i knew the quest was unñeccesary i bought the fire resist shoulder enchant, then i handed her 250 rep worth of tokens to get 100 rep and a quest completed... seemed like the right thing to do.

**Comment by drozdez** [comment]
So is it working correctly or no?)

**Comment by Thenari** [comment]
No.


Once you hit revered the quest unlocks

The quest completion is supposed to unlock the shoulder enchants.


Right now the shoulder enchants are available right as you hit revered. The quest does nothing now

**Comment by drozdez** [comment]
Are u sure it must unlock? Because there's no info about that here https://classicdb.ch/?quest=5513

**Comment by Thenari** [comment]
Lmao read the quest text the very last line.

**Comment by Thenari** [comment]
@drozdez any news?

**Comment by Thenari** [comment]
Oops i marked this with fixed 15 days ago? I dont remember getting a confirm fix

**Comment by Thenari** [comment]
Maybe during naxx when AD get updated people will notice and be vocal enough got a Dev to notice this
