### ISSUE TITLE
Curse of Weakness Problem

### ISSUE THREAD

**Issue by Aneurysma** [elysium-project/classic-bug-tracker#658]
Hello.

I encountered a bug with the spell "Curse of Weakness" cast by enemies like Jadefire Trickster.
If cast on my hunter it doesn't only reduce the physical damage dealt by 27, but actually completely nullifies it. So my hunter doesnt do any damage when debuffed with it.
Please investigate, thanks.

**Comment by Navashed** [comment]
#417 #465

**Comment by Navashed** [comment]
I have tested this issue on a hunter again and found no issue. Please provide more information. Perhaps your spec or weapon have something to do with this?

![](https://i.gyazo.com/756033e070191863d7a50aa794dc712f.png)

**Comment by Thenari** [comment]
I heard warriors complaining about this like a month or two ago

I cant get debuffed on ptr and im not super in the mode to level a warrior to 60 and run around the world testing all the mobs that use Curse of Weakness 

https://classicdb.ch/?npc=1564 Bloodsail warlock
https://classicdb.ch/?npc=1124 Frostmane shadowcaster
https://classicdb.ch/?npc=7112 Jaedenar Cultist
https://classicdb.ch/?npc=1144 Mosh'Ogg Witch Doctor
https://classicdb.ch/?npc=9678 Shill Dinger
https://classicdb.ch/?npc=7342 Skeletal Summoner
https://classicdb.ch/?npc=3762 Felmusk Felsworn
https://classicdb.ch/?npc=14861 Blood Steward of Kirtonos
https://classicdb.ch/?npc=9039 Doom'rel
https://classicdb.ch/?npc=11453 Wildspawn Trickster
https://classicdb.ch/?npc=4036 Rogue Flame Spirit
https://classicdb.ch/?npc=9518 Rakaiah
https://classicdb.ch/?npc=6008 Shadowsworn Warlock
https://classicdb.ch/?npc=7370 Restless Shade
https://classicdb.ch/?npc=6118 Varo'then's Ghost
https://classicdb.ch/?npc=15623 Xandivious

I can probs look into their abilities and learn how to use their spells myself but I'm not gonna do that unless someone tells me its still happening

**Comment by Thenari** [comment]
Hey this is 3 weeks+ theres other duplicates of this but no one has talked about it recently @drozdez did you do anything with this?

**Comment by drozdez** [comment]
Still no, still no(
