### ISSUE TITLE
Paladin Mechanics Abuse

### ISSUE THREAD

**Issue by mwrye2017** [elysium-project/classic-bug-tracker#663]
Many thanks to players Khandz Gnomidigital for bringing to light a massive abuse done by alliance in wsg
now this was "patched prior" but be sure the methods still work
Number one 
BoP does not prevent you from picking up the flag 
https://gyazo.com/511c981df4c0da7a93ea55b341f9d1d1
https://gyazo.com/12e5e3bae7a5622ddc509b777c6358bb
regularly when they cant beat the defense they simply send a mage with a free action potion BoP him and he is home free yet a flag carry cant have a bop? Try it with a lip you lip and pick the flag back up
now that sounds like abuse to me
Next is the fact paladins can mind control cap and BoP on most private servers to make the EFC drop the flag
on this server Devs decided hey that mechanic needs to be patched so now you cant bop someone while they hold the flag to make them drop it
Instead you simply DI
https://i.gyazo.com/thumb/1200/e3026f88ff17f3d1346bdf000a0c6ae9-png.jpg
https://i.gyazo.com/thumb/1200/0b3a5f7bf365137ea57548bed5a178d0-png.jpg
A normal fair and balanced strat that they do "all the time"
please fix these bugs or alliance will continue to abuse them

**Comment by Thenari** [comment]
you also have chat messages of the paladin confirming he intentionally uses this strategy often knowing its an abuse.
