### ISSUE TITLE
Priest wand specialization

### ISSUE THREAD

**Issue by Sneraz** [elysium-project/classic-bug-tracker#670]
On my priest that im currently leveling there is a weird bug. For some reason the wand specialization spec does not work. I have a wand with 32-60 in damage and i have 5/5 wand specialization which should give me 25% increased damage. However my wand still only does 50-55 damage each cast.

**Comment by Thenari** [comment]
I am testing this now I suppose ill make a lvl 10 priest and do some testing

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39849620-3938822a-53db-11e8-9384-d31a21bf61a5.png)

basic lesser magic wand no talent points looks like its between 6-11 dmg

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39849656-75f9a220-53db-11e8-8563-cbd44073fa37.png)

same wand with 1 talent point

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39849681-9e0b2892-53db-11e8-9004-2ef70488180f.png)

same wand 2 talent points

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39849726-c802207e-53db-11e8-84d1-9c6f3787e146.png)

same wand 3 talen points (i crit once for 19 neat)

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39849761-e9488a0c-53db-11e8-8bbd-d10067b953b0.png)

same wand 4 talent points

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39849849-62421018-53dc-11e8-93e8-9e5954ed2a84.png)

same wand 5 talent points (first time i ever saw a 15)

**Comment by Thenari** [comment]
it should be noted that all wands are magic dmg and damage taken can be lowered by various effects but it looks like the concept of a lil more dmg per wand talent is true. if you can say what wand type and what enemy i can test further but otherwise this is working as intended.
