### ISSUE TITLE
Warrior abilities does not work under curse of weakness

### ISSUE THREAD

**Issue by Jonis12345** [elysium-project/classic-bug-tracker#671]
as I level i've stumbled upon two mobs so far that gives me curse of weakness

The fire guys in stonetalon mountain and the satyrs in ashenvale

When they cast curse of weakness i can't use my key abilities.
The animation cast, but nothing is registered in the combat log or does any damage to the mob.

Please look ino this

**Comment by Thenari** [comment]
haha yeah i remember this, let me check in ptr if its still doing it.

**Comment by Thenari** [comment]
https://classicdb.ch/?npc=1564 Bloodsail warlock
https://classicdb.ch/?npc=1124 Frostmane shadowcaster
https://classicdb.ch/?npc=7112 Jaedenar Cultist
https://classicdb.ch/?npc=1144 Mosh'Ogg Witch Doctor
https://classicdb.ch/?npc=9678 Shill Dinger
https://classicdb.ch/?npc=7342 Skeletal Summoner
https://classicdb.ch/?npc=3762 Felmusk Felsworn
https://classicdb.ch/?npc=14861 Blood Steward of Kirtonos
https://classicdb.ch/?npc=9039 Doom'rel
https://classicdb.ch/?npc=11453 Wildspawn Trickster
https://classicdb.ch/?npc=4036 Rogue Flame Spirit
https://classicdb.ch/?npc=9518 Rakaiah
https://classicdb.ch/?npc=6008 Shadowsworn Warlock
https://classicdb.ch/?npc=7370 Restless Shade
https://classicdb.ch/?npc=6118 Varo'then's Ghost
https://classicdb.ch/?npc=15623 Xandivious

this seems to be all the npc's who can use curse of weakness of varius levels. lets test each one

**Comment by Thenari** [comment]
#772 is a newer version the who are connected now closing this older one as a duplicate
