### ISSUE TITLE
Came back from weekend to empty mailboxes on ALL characters (again)

### ISSUE THREAD

**Issue by Schmidtyeswow** [elysium-project/classic-bug-tracker#674]
Patch: current Elysium patch.
Post made on the recommendation of in-game GM.

Hello Elysium developer,
I've been using my mailboxes between characters as a kind of "external bankbox" due to not having enough space in my bank for all my profession materials and other trade good. However when i came back from the last weekend (friday the 20. to monday the 23. of april) after a few days of not playing, i discovered that my mailbox was empty on all of my characters. Seeing as i had a lot of high level materials this time around (such as dragon scales of red and black kind, 10 fiery cores worth of gold i bid on in the auction house, runecloth, bids on arcane crystals and arcane bars as well as other bids on the auction house like mana potions). i've lost valuables for hundreds of gold. 

The first time this happened to me i lost 7 fiery cores and some other stuff, but i didnt think it possible to refund or such so i never made a threat about it, but as the issue has now happened again im making a post because it sucks having my in game economy ruined due to bugs. Also i had from guildmates that you guys made some sort of hotfix/rollback(?) and as such the issue may be due to that?

I hope to hear back from you :)
 - One hopefull Elysium resident.

**Comment by Thenari** [comment]
Hello, I've been skipping over this post for a while its not something i can do bug testing for, I've also had mail problems on my toons, the mail system is a black hole, but it tends to be 30 days after i get things back.

worst case your account may of been compromised
best case your stuff will show up outta the abyss 30 days in the mail

**Comment by RainElysium** [comment]
No response. Assumed to be fixed.
