### ISSUE TITLE
[Alterac Valley] Irondeep and Coldtooth mines

### ISSUE THREAD

**Issue by Asylum00** [elysium-project/classic-bug-tracker#691]
There are a couple of issues with the AV mines, Irondeep and Coldtooth. Upon securing the mine, Irondeep guards spawn but are able to be attacked by players of the same faction and will attack players of the same faction. They do not attack the troggs in the mine like they are supposed to. This makes it very difficult to complete the quest for supplies in the mine. Furthermore the patrols that spawn in the mine somehow all spawn together which also isn't supposed to happen. TY.

**Comment by Thenari** [comment]
Was just messing around testing stuff, the mines are really weird, like you claim them but they are under constant attack, no new faction miners will spawn to out fight the invading mobs, but if your faction mine leader dies then it can reset :/ so on the ptr im .damage 10000 the mobs on a mouseclick and running around .mod aspeed 4 and even i cant keep up with the mobs spawning

**Comment by Thenari** [comment]
I havent seen the guards attack players yet if you know any conditions for that let us know
