### ISSUE TITLE
[Alterac Valley] Cavalry doesn't work when called again.

### ISSUE THREAD

**Issue by WobLight** [elysium-project/classic-bug-tracker#697]
The second time the Cavalry is called, NPCs row up but don't run for the enemy base.
I witnessed it only once, so it could also be a random chance but it's more likely the event works only once.

**Comment by WobLight** [comment]
Actually there's a report for horde faction here #433

**Comment by Thenari** [comment]
@shenna-elysium Idk shit about pvp has this been touched?

**Comment by WobLight** [comment]
And this was closed because... ?
