### ISSUE TITLE
[Alterac Valley] Looting issues

### ISSUE THREAD

**Issue by WobLight** [elysium-project/classic-bug-tracker#700]
- items dropped from players through Remove Insignia are sometimes not lootable.
- when Remove Insignia is used on a player who didn't use release spirit will produce an unlootable skeleton (that mean that once you close the loot frame you can't loot the skeleton anymore and anything not looted is lost)
- Hides dropped by wolves (guess same goes for Rams horde side?) follow Group Loot rules instead of FFA.

**Comment by Thenari** [comment]
I'll look into this, the first two sound valid but the last one might be loot settings in the party you are in, i dont really know much about how loot works in pvp

**Comment by WobLight** [comment]
I asked the raid leader to change loot mode to FFA, but looks like that's not possible to change loot mode in AV, which sound reasonable.

**Comment by Thenari** [comment]
The cant move inventory around after using a function is probs the same function as DEing an item. Its intended like that and ive lost a few things to DE loot issues

**Comment by Thenari** [comment]
@shenna-elysium find someone who knows stuff about pvp T_T
