### ISSUE TITLE
Sulfuras hand of ragnaros not scaling with extra spell damage

### ISSUE THREAD

**Issue by Alastor89** [elysium-project/classic-bug-tracker#704]
Hello!

I tested out the new legendary, and sadly the chance on hit fireball effect never does more damage than what the tooltip says unless its a crit, when it should have scaling from my spell damage. Please look into it!

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39786682-913123a2-52ef-11e8-81aa-999b8648ba6d.png)

basic attacking only in a boring battle stance with no gear

**Comment by Thenari** [comment]
251 fire ball and 13 per tick

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39786733-d05e9eb0-52ef-11e8-9d59-c68cead63b15.png)

after a flask of supreme power

**Comment by Thenari** [comment]
289 fire dmg and 13 per tick

**Comment by Thenari** [comment]
the fact that the tick doesnt change makes me believe there is no scaling, but srsly why do you want spell power scaling on this itll probs never happen? i guess a shammy maybe? do pallys use 2hand maces?

**Comment by Alastor89** [comment]
Yes, its very good for paladins because of the spell damage scaling. Sadly it doesn't work on this server.

**Comment by Thenari** [comment]
Its been a long time. If anyone wants to reignite this issue feel free.
