### ISSUE TITLE
[Alterac Valley] Snowfall Graveyard is doubled

### ISSUE THREAD

**Issue by WobLight** [elysium-project/classic-bug-tracker#705]
Querying `GetMapLandmarkInfo` function in the client results in two Snowfall Graveyard reported (which often lead to have a gray graveyard on the map even while it is controlled). Also, when it turn from Alliance Controlled to Contested by horde, alliance players waiting to for resurrection are not ported to the nearest valid graveyard and are still resurrected in Snowfall, despite it being contested (also true for Horde -> Contested?).

**Comment by Thenari** [comment]
I don't know shit about pvp @shenna-elysium has this been touched its really old

**Comment by WobLight** [comment]
Why is this closed?

**Comment by Thenari** [comment]
Was testing stale bot. It can auto close things
