### ISSUE TITLE
Wyvern Sting and Freezing Trap are exclusive

### ISSUE THREAD

**Issue by WobLight** [elysium-project/classic-bug-tracker#708]
Applying one removes the other.

**Comment by Thenari** [comment]
this is a duplicate issue so i am closing it

**Comment by WobLight** [comment]
Duplicate? I can't find anything else searching "wyvern sting" aside the positive dot issue.

**Comment by Thenari** [comment]
Theres literally the next issue from your account called the same thing

**Comment by Thenari** [comment]
Omg lmao i got wyvern and viper confused

**Comment by shenna-elysium** [comment]
Please provide the sources fro the correct behavior.

**Comment by Thenari** [comment]
Can you have wyvern sting and viper sting on the same target? It might be unspoken rule like warlock curses only 1 per player class. Ice trap might share it. Ill try it with 2 hunters

**Comment by WobLight** [comment]
No, you're getting more confuse, this is Freezing Trap and Wyvern sting. The freezing effect removes the sleep and vice versa.

**Comment by WobLight** [comment]
Why would a trap remove a sting? One is a sleep, the other is not.

**Comment by shenna-elysium** [comment]
@WobLight now please fix 💃

**Comment by Thenari** [comment]
was playing around on ptr and looked at some patch pages, this is probably blizz-like.

**Comment by WobLight** [comment]
Can you link your sources? I can't find anything specific in Patch Changes here
https://wow.gamepedia.com/Freezing_Trap
https://wow.gamepedia.com/Wyvern_Sting

**Comment by Thenari** [comment]
I got a glimpse at some spell data. Both freezing trap and wyvern sting use aura #12 to stun. You cant have two of the same effect on at a time.

**Comment by WobLight** [comment]
All stuns use aura 12

**Comment by Thenari** [comment]
and all stuns override each other.
