### ISSUE TITLE
Lakota Windsong and Ruul escort quests bugged.

### ISSUE THREAD

**Issue by Tiamat114** [elysium-project/classic-bug-tracker#715]
For some reason both Lakota of Stonetalon and Ruul of Ashenvale have decided to go on strike. Ruul does not spawn ion his cage and if started from where you find him if you even can he walks through the world back to his cage and fails the escort due to out of range. Lakota right now is standing on the edge of a sheer cliff right next to the great lift, not at her spawn, and is completely unreachable in any capacity.

**Comment by Tiamat114** [comment]
Yep Lakota is still there chillin this morning.
![wow](https://user-images.githubusercontent.com/36385657/39877434-f588104a-5443-11e8-9f8a-3e8958cd274f.png)

**Comment by Thenari** [comment]
I'm on the ptr now starting up the escort

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39963687-fc01dc22-5640-11e8-9779-484cb30d654e.png)

I'm pretty sure she should be in a cage but in the ptr shes just standing in a weird spot... idk what to do about this
