### ISSUE TITLE
Pets refuse to attack in some cases.

### ISSUE THREAD

**Issue by WobLight** [elysium-project/classic-bug-tracker#717]
Pets refuse to attack when issued if the target is stealthed (but visible) or using Feign Death.
Also, the pet stop chasing the target when it goes stealth (not vanilla like) and doesn't stop attacking when the target is stunned even if it's an effect that is removed on damage (e.g. Engineering Bombs, not sure whether that's to be expected though).

**Comment by WobLight** [comment]
In the old elysium bugtracker there were plenty of people complaining about pet chasing stealthed units even when no longer visible, but that was always considered blizzlike, there should be videos around showing that. Anyway, at the moment pets refuse to attach even *visible* stealthed units.
I'll look whether I manage to find some video about pets chasing stealthed targets.

**Comment by WobLight** [comment]
I found the video https://www.youtube.com/watch?v=Q0O4RKeD4g4&index=7&list=FLvgfhOlOFZBufweoK4eXBGg

**Comment by WobLight** [comment]
Anyway, back on anathema pet were working fine, something caused regression.

**Comment by Crusaderz** [comment]
Hey, WobLight. 
As someone who played rogue on retail back in 2006 i can comment on a video you linked.

It was a bug. On some major path blizzard broke stealth mechanic.

1) Pets chased rogues when they were no longer visible.
2) If enemy right click on a rogue from the distance they had ther autoattack on even when rogue goes to stealth (enemy stays in combat animation), if rogue moves into melee range he will be instantly autoattacked out of stealth.
3) Stealth often breaks right after vanish by autoattacks. http://epicninjamaneuver.ytmnd.com/ was born during those days and was really popular among players.

Blizzard fixed all those bugs really fast (except 3rd one).

@Thenari 

> you shouldnt be able to attack a Feign Death target
You should be able to select and attack hunter during FD. You also should be able attack him with your pet. Pets on aggressive mode shouldn't attack hunter during FD by itself.

**Comment by Thenari** [comment]
Im gonna label this battleground related cause pvp stuff.

It would be weird if pets had their own stealth detection chances but would be interesting.

**Comment by WobLight** [comment]
It's also broken against stealthed NPCs.

**Comment by Thenari** [comment]
Yeah probs. Lots of stuff is broken :p

**Comment by Thenari** [comment]
Yeah if i sent my imp to attack just regular mobs sometimes he gets scared and heads back to me and phase shifts away. Normally just gotta ask him twice

**Comment by WobLight** [comment]
Why is this closed?

**Comment by WobLight** [comment]
has this been fixed?
