### ISSUE TITLE
Treant Spirit

### ISSUE THREAD

**Issue by Thenari** [elysium-project/classic-bug-tracker#723]
I wanted to test the drop tables for Treant spirits, they are a scripted spawn

from Flute of the Ancients

I Checked the files and Treant spirit is a npc within the game but can not be summoned on this server.

![image](https://user-images.githubusercontent.com/38762769/39963422-b64849a8-5638-11e8-9d01-52c525bb7d45.png)

creature ID is 9601

![image](https://user-images.githubusercontent.com/38762769/39963428-d4196264-5638-11e8-8ca3-e23f3a03e8bb.png)

I tested if it was because i didnt have the quest but i did all the steps of the quest needed to get the flute. the item should be usable the whole of the irontree woods, but specifically if you use it in front of the statue near the ally spirit healer it spawns a quest mob.

**Comment by drozdez** [comment]
I didn't find any chance to make it work correctly, and also in every source there's much videos about summoning Arei, but no any about another mobs. So, I think it's working as intended
