### ISSUE TITLE
Frostwolf Initiate Insignia not being awarded or showing in bag

### ISSUE THREAD

**Issue by Knucklechild** [elysium-project/classic-bug-tracker#727]
Hi, I was in a winning Alterac Valley battleground where the Horde won.  After teleporting out of AV and winning, I went to the quest giver to turn in my Frostwolf Initiate Insignia and it was not in my bag BUT the quest giver had a "?" over his head and that was the only quest I could have turned in.

Per a GM, I depeted all the files in my WDB folder in my game files, relogged, and the issue still persisted.

Please advise.

**Comment by Thenari** [comment]
plz double check your bags were not full lol, otherwise yes sometimes the spawning item in your bag gets messed up. plz give more conditions if you can so we can try to repeat

**Comment by Thenari** [comment]
So can you just attempt to turn in the quest with the invis token? Or are you saving the token for something i dont super know pvp stuff

**Comment by Knucklechild** [comment]
The yellow/golden "?" is above the quest giver, but I cannot complete the
quest because the item isn't in my bag.  Or if it's invisible, the quest
giver NPC can't detect it in my bag to allow me to complete it.

I am not saving the token for anything.  It's literally not in my bag.  I
want to turn in the quest for the EXP.

**Comment by Thenari** [comment]
Ok this sounds like an in game ticket could help you more right now. Put in a ticket and link this github issue page in your ticket.

**Comment by Thenari** [comment]
Do you have any bag addons. Anything that manages inventory?

**Comment by Knucklechild** [comment]
I put in a ticket and they told me to post on this forum...

**Comment by Thenari** [comment]
Haha what gm did that? Did you not link this page in your ticket?

**Comment by Knucklechild** [comment]
I have no recollection which GM told me to go to the forums.  And there was
no need to link the forum post in a ticket since I was told from a ticket
to make a post.

Is it not possible to just put an insignia in my bag or mail one to me?  I
jsut want to turn my quest in and get the EXP.

Thanks.

**Comment by Thenari** [comment]
Following up, I really want you to link this webpage to a GM in a ticket. plz do that and come tell me what happens.

**Comment by Knucklechild** [comment]
Okay so I made two tickets online and was told to make a ticket on here.  

What's going on?  How do we fix this??  This is extremely frustrating.

**Comment by Thenari** [comment]
Hello I didnt get an update on this, did you show a ingame ticket this webpage that helps them know who to talk to and also gives us your toon name so we can find you

**Comment by Knucklechild** [comment]
Yes. I’ve posted back and forth multiple times. I’m done trying. 

Thanks anyway.

**Comment by RainElysium** [comment]
You didn't reply whether or not you have a bag addon running. Disable all addons and check to see if the items are in your bag.

**Comment by Knucklechild** [comment]
I did turn off all addons and the item never appeared.

Thanks,

Christopher B. Wallace

**Comment by Knucklechild** [comment]
You never fixed anything. It’s not closed.

**Comment by Thenari** [comment]
Haha yeah its not fixed but you dont wanna keep trying and i couldnt replicate :/ this was like 3months ago. Havent heard any new instances of this. It might of gotten a fix by doing the server world patch or it might of been some one-off bug. Idk what more i can do. Im sorry no one was ever able to help you :(

**Comment by Thenari** [comment]
This will stay here forever and if it happens again we can reference this.
