### ISSUE TITLE
[Warrior] Sweeping strikes bugs

### ISSUE THREAD

**Issue by Crusaderz** [elysium-project/classic-bug-tracker#744]
There is numerous problems with sweeping strikes warrior talent.

I found an guide reposted from wow-europe forums where author detailed and very well documented all aspects of this ability up to patch 1.11 (atleast).

https://hilbert.wordpress.com/sweeping-strikes-guide/

According to it:

1. _SS stacks with cleave, producing two additional attacks._ - On elysium only one additional attack is produced.
2.  _CAN CRIT. Should have 5% crit baseline, does not scale with melee crit, probably scale with intellect and spell crit. Does not benefit from the Impale talent_ - Does not crit on Elysium.
3. _It is worth noting that SS cannot miss, be dodged, parried nor blocked_ - My SS got parried
![image](https://user-images.githubusercontent.com/3641625/40787258-d91ed5f2-64f5-11e8-98da-ead8e3a3f0e8.png)
and dodged:
![image](https://user-images.githubusercontent.com/3641625/41370965-b274c98c-6f51-11e8-8127-e5236da7a029.png)
4.  [Patch 1.9](http://wowwiki.wikia.com/wiki/Patch_1.9.0) _Sweeping Strikes - Whirlwind and Retaliation will now correctly consume the charges from Sweeping Strikes._ On Elysium SS does not work with Retaliation.

**Comment by Thenari** [comment]
damn thats a long read.

I'm glad you summarized lol....

first idea that comes to mind is different ranks of abilities sometimes are bugged

So I guess ill test the ranks one by one

I'll do it just without any other abilities but SS and cleave. to see how many attacks happen

it has a %dmg scaling you claim i can test that with just enrage i am not in the mood to test every +%dmg thing in the game lol

i can also see if it ever crits, i can use a flask of supreme power to test a spell power bonus.

**Comment by Thenari** [comment]
ok cool sweeping strikes only has one rank that makes it easy

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40555970-dc9eae32-6018-11e8-988a-23b7334907f1.png)

If i understand this, umm i used cleave on the highlord which caused sweeping strikes to hit lady onyxia but she did not get hit by cleave, while another 3rd party soilder did... i feel like if i put the rage to use cleave it should hit all and sweeping strikes should hit someone too

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40556398-806e381a-601a-11e8-8cda-11a6164ac398.png)

ok i gathered full rage then used sweeping strikes right away and a cleave, waited to get enrage +25% dmg, used cleave again with sweeping strikes


it looks like it does 25% more dmg, and the person who got hit by the "sweeping strikes + cleave" took more dmg likely from another base hit, im user if that base hit got a +25% buff from enrage, would need someone to look at the formula for calculating dmg to confirm

**Comment by Thenari** [comment]
So i really like hitting the lady and highlord but im gonna do another test with 3 guards as they have same armour and stuff

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40556986-a10ccad0-601c-11e8-8638-6fb9c6d67e77.png)

err they are all named the same thing... easier to read data with different mobs...

I was fighting 3 guards so its a lil hard to tell what went down,

**Comment by Crusaderz** [comment]
@Thenari 

![image](https://user-images.githubusercontent.com/3641625/40557148-da8b68a8-6057-11e8-8e5a-864e05e54c2b.png)

66 x 1.25 = 88,5 so it's clearly working as intended. But only one additional hit from SS when you cleave two mobs is not right.

**Comment by Thenari** [comment]
"2. Should double dipping from +% damage bonuses (enrage, bg buffs and such). - Don't know how it works on elysium, since my level is not high enough to have SS and Enrage at the same time."

I think it does, so this is working.

**Comment by Thenari** [comment]
yo im doing a thought chain don't comment between them lol I;m editing my writing :P

**Comment by Thenari** [comment]
oops meant to hide your comment but i deleted it lol

**Comment by Thenari** [comment]
anyway im gonna use a supreme power flask and see if that makes me crit

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40557825-6609ec94-601f-11e8-8569-06591e561b28.png)

yeah for sure SS is doubling up on enrage

**Comment by Thenari** [comment]
i've been doing this for like 5+ minutes without getting a crit.... but i also have never gotten a crit with my basic attack lol lets give me some Crit boosting potion or something

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40557947-d32bf0d8-601f-11e8-9307-d9463b99a436.png)

so i got a crit while SS was up, and SS did the same damage of the first hit

**Comment by Thenari** [comment]
are you suggesting SS can crit seperately from the triggering attack?

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40558003-fd45c0a6-601f-11e8-93e9-a5c972b43422.png)

Crit + SS + Enrage

SS double dipped on Enrage when i crit so thats something

**Comment by Thenari** [comment]
it's actually pretty fun, If you hit a target with low armour/dmg reduction, itll do the same dmg it did to the weak target to the SS/cleave target... hit like a critter beside a hard to damage target lol

**Comment by Crusaderz** [comment]
>the hit will do 60~ dmg to main guard, but SS will do 80~ maybe thats a crit?

Critical strikes deal +100% normal damage. So it's more looks like armor difference.

About crits from the guide:

>Sweeping Strikes Crits

>Until 1.11, SS was not able to crit. I say this because several of my mods (CritLine, Damage Meters) had not recorded any SS crits up until that point. Some people will no doubt argue that it could crit but in this case I will simply assume that my mods were not lying and those people are wrong.

>Now, while SS can crit, it’s more of fun bonus than a serious one. SS crits will never do more damage than the original hit would have done if it had crit. This is a bit confusing but I’ll do my best to illustrate this with an example:

>Say that you fight two targets with the same armor with SS up. Here are the four possible outcomes >>(using arbitrary numbers):

>You hit A for 500.
>Your Sweeping Strikes hits B for 500.

>You crit A for 1000.
>Your Sweeping Strikes hits B for 1000.

>You hit A for 500
>Your Sweeping Strikes crits B for 1000

>You crit A for 1000
>Your Sweeping Strikes crits B for 1000

>If you crit A for 1000, SS cannot crit B for more than 1000. In a sense the two attacks work independently of each other in the sense that SS crits will occur regardless of whather your main attack crits or not, but at the same time the SS damage is directly linked to the main attack damage. So SS crits are mainly a fun thing that doesn’t add too much damage in the long run, nor is it predictable at all.

>SS crits will ignore Impale and will not effected by +crit from gear, nor Recklessness.

It's hard to test. You probably need to check source code to make sure it implemented at all

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40558236-aaf8ddf0-6020-11e8-974b-3c7bb59a23e7.png)

haha unconcious dig rat didnt work like i wanted it to 📦 
but i got an enrage + crit + cleave + SS

**Comment by Thenari** [comment]
So you edited your first message and i forgot what i was testing

**Comment by Thenari** [comment]
I'm gonna take a break and just fool around on the real server got a MC raid soon. but tell me what you feel is wrong and ill ask someone to look into it @Crusaderz

**Comment by Crusaderz** [comment]
I deleted double dipping part since it's working

**Comment by Thenari** [comment]
but you want to like get a normal hit, but SS dmg can possibly crit to a cap of a standard hit crit? I've not seen that happen, I've had the supreme power flask and a mongoose on this whole time

**Comment by Crusaderz** [comment]
@Thenari 

>but SS dmg can possibly crit to a cap of a standard hit crit?
That's correct.

>I've not seen that happen
Me neither

**Comment by Thenari** [comment]
I just tagged it as confirmed but im hesitant to say its broken, I would need to hear from more sources that its intended to have a seperate crit chance with a cap of a standard hit crit.

so i gave it the Probably working as Intended... when a higher up person skims this thread They can be the judge of that.

**Comment by Crusaderz** [comment]
From the guide:

>The keen reader might notice that the 1.11 notes are basically the same as the 1.10 ones. Only >difference is that they actually worked this time. This patch made SS what it is today, basically.

>In addition to fixing the “issues” with SS, the developers also blessed it with a 5% crit chance. I assume >it’s effected by int and spell crit because it is not effected by +crit gear or buffs like recklessness. More >about SS crits later.

**Comment by Crusaderz** [comment]
Found new bug. Updated first post.

**Comment by Thenari** [comment]
I need an expert on warriors to check this. I'll bring it up.

**Comment by Crusaderz** [comment]
First post updated new bug added.

**Comment by Thenari** [comment]
Checking in. I talked to some warriors but its hard to have proof on whats broken and whats intended.

**Comment by Crusaderz** [comment]
Well, the detailed guide written at those times is a proof, isn't it? The guide was posted in sep 2006, one month after patch 1.12 so most likely it's was written during 1.12 
![image](https://user-images.githubusercontent.com/3641625/41338288-62ba37d0-6efa-11e8-838b-8619bc99d9ea.png)

>The keen reader might notice that the 1.11 notes are basically the same as the 1.10 ones. Only difference is that they actually worked this time. **This patch made SS what it is today, basically.**
Seems like indeed 1.12 guide.

Bug N1:
Autor claims:
> SS stacks with cleave, producing two additional attacks

SS page on a wowwiki (oct 2006 version):
http://wowwiki.wikia.com/wiki/Sweeping_Strikes?oldid=282560
> Stacks with Cleave, causing four attacks on two enemies every swing, each with a standard critical chance.

Bug N2:

>CAN CRIT. Should have 5% crit baseline, does not scale with melee crit, probably scale with intellect and spell crit. Does not benefit from the Impale talent

He not just said "SS can crit" and moved along. He provided detailed information when it started:

>Until 1.11, SS was not able to crit. I say this because several of my mods (CritLine, Damage Meters) had not recorded any SS crits up until that point. Some people will no doubt argue that it could crit but in this case I will simply assume that my mods were not lying and those people are wrong.

He told how it works:

>Now, while SS can crit, it’s more of fun bonus than a serious one. SS crits will never do more damage >than the original hit would have done if it had crit. This is a bit confusing but I’ll do my best to illustrate >this with an example:

>Say that you fight two targets with the same armor with SS up. Here are the four possible outcomes (using arbitrary numbers):

>You hit A for 500.
>Your Sweeping Strikes hits B for 500.

>You crit A for 1000.
>Your Sweeping Strikes hits B for 1000.

>You hit A for 500
>Your Sweeping Strikes crits B for 1000

>You crit A for 1000
>Your Sweeping Strikes crits B for 1000

>If you crit A for 1000, SS cannot crit B for more than 1000. In a sense the two attacks work independently of each other in the sense that SS crits will occur regardless of whather your main attack crits or not, but at the same time the SS damage is directly linked to the main attack damage. So SS crits are mainly a fun thing that doesn’t add too much damage in the long run, nor is it predictable at all.

He did some research:
>SS crits will ignore Impale and will not effected by +crit from gear, nor Recklessness.

He even provided screenshot (sadly, link is dead)
> http://files.upl.silentwhisper.net/upload5/sscrit.jpg (my highest SS crit so far)

Bug N3:
> It is worth noting that SS cannot miss, be dodged, parried nor blocked

[Fun warrior tricks you may not know about] (https://us.battle.net/forums/en/wow/topic/6520713188)
>You can hit hunters through deterrence with Sweeping Strikes. Target their pet when beside both of them to keep doing some damage. **This works because deterrence works off misses, and sweeping strikes can never miss/dodge/block/parry.**

This is not vanilla source since it was posted during cataclysm, but we can say this part of SS wasn't changed during all those expansions.

Bug N4:
>Sweeping Strikes - Whirlwind and Retaliation will now correctly consume the charges from Sweeping Strikes

Quote taken directly from patch 1.9 notes.
