### ISSUE TITLE
STV Fishing Extravaganza 

### ISSUE THREAD

**Issue by nexiros** [elysium-project/classic-bug-tracker#747]
http://www.wowhead.com/stranglethorn-fishing-extravaganza

Here is clear evidence that event is meant to START at 2pm server time. Currently event starts at 3pm server time. Can you please correct this in game. Thanks

**Comment by nexiros** [comment]
http://blue.cardplace.com/newcache/en/13021327.htm

Was told this will assist my case :)

**Comment by Thenari** [comment]
This a once a week event on sundays right? I cant really do anything about this but ill ask someone above me to check the script event

**Comment by nexiros** [comment]
Are you going to have someone there today to test it and see what's happening? Because like I said it start's an hour late. Will someone be there to start it if it's not beginning at the right time? Kinda cutting into raid preparation times :(

**Comment by nexiros** [comment]
It's late again. If anyone is on and testing to see this.

**Comment by RainElysium** [comment]
Fix implemented. Pushed to repo.
