### ISSUE TITLE
Dies from Portal to Orgrimmar

### ISSUE THREAD

**Issue by SexigeBengt** [elysium-project/classic-bug-tracker#753]
2nd time my character Pervo dies from taking a Portal to Orgrimmar with World Buffs and 100% HP! 

FIX IT!

**Comment by Thenari** [comment]
Weird. I've watched a ton of people use mage portals cant say ive seen anyone die from it. Do you have idea why its happening to you?

**Comment by SexigeBengt** [comment]
I have no clue why this occur, but both times has been after I have gatherered DM Trib and take Portal to Orgrimmar. Its rare, but its 2 times too many. I cannot find and damage in my combat log, but its like you fall and die. Like the "gravity" becomes faulty so even tho i do not fall high I die.

**Comment by Thenari** [comment]
Others use this portal with you? As a theory maybe the king buff fades as you leave the instance and the nearby ogres murder you while loading... 

But im pretty sure during the loading phase of using a portal you should stop existing in world....

Anyway you really shouldnt trust mage portals. Get a warlock to summon you. Its far superiour.

(I probs need to know more about exactly what you were doing. My worst fear is you pissed of a GM who is .die targetting you after you get buffs as some sort of prank haha)

**Comment by Thenari** [comment]
Yo i saw this happen! Apparently people talk about it too but youre the first to report it. The rumour theory i heard is if you click on a fresh portal too quick it doesnt have the time to run some sort of script and you fall to death. People say if you wait like 5seconds its mostly safe lol.

Still this will be looked into!

**Comment by Thenari** [comment]
Ive been taking lots of portals lately ive even been trying to take them as soon as the portal appears which was when the thing happened. I think a patch fixed it?
