### ISSUE TITLE
Sheen of Zanza

### ISSUE THREAD

**Issue by Thenari** [elysium-project/classic-bug-tracker#754]
![image](https://user-images.githubusercontent.com/38762769/40801841-f342f774-64e1-11e8-8e64-198f55975420.png)

someone reported to me that you can't drink the potion right now

tried it on ptr says spell is not available

**Comment by Thenari** [comment]
the other 2 pot rewards work

**Comment by Thenari** [comment]
Can you be more specific on what isnt working?

**Comment by skoo10** [comment]
Yes, the Sheen of Zanza. other 2 pots work. but having the same error as above screen shot.

**Comment by Thenari** [comment]
Hmm maybe something got reverted

**Comment by Thenari** [comment]
@drozdez you know anything about this?

**Comment by drozdez** [comment]
@Thenari we will work on it some later, because it's the item from the later update, so u have just wait)

**Comment by Thenari** [comment]
No this stuff is out now droz :p

**Comment by Thenari** [comment]
Any updates on this?

**Comment by shenna-elysium** [comment]
Not available in this patch.  Wait for 1.11

**Comment by Thenari** [comment]
Shenna do you have a source?

The wow patch history says 1.7

Let me link it below

**Comment by Thenari** [comment]
https://wow.gamepedia.com/Quest:Zanza%27s_Potent_Potables

**Comment by Thenari** [comment]
https://web.archive.org/web/20070602172347/http://www.worldofwarcraft.com/patchnotes/patch-05-09-13.html

**Comment by Thenari** [comment]
Its under the quests added to ZG 1.7

**Comment by namreeb** [comment]
This actually still is an issue, but only for Sheen of Zanza.

**Comment by ZicoQA** [comment]
This has been fixed
