### ISSUE TITLE
Quest: The Stones That Bind Us

### ISSUE THREAD

**Issue by thk88** [elysium-project/classic-bug-tracker#771]
Nighthaven Patch 1.7

The quest tells you to free the spirits of different servants. This is done by lowering the mobs health untill they become invulnerable and then use a stone of binding (which should be glowing once they hit the invulnerable state).
The stones doesn't start glowing. The chat spams that it should be glowing. They are clickable even without lowering the mobs, which they apparently shouldn't be. The mobs should be standing close to the stone, but even placing them almost inside the stones, doesn't help.
I tried having my pet tank it and use the stone prior to them hitting the invulnerable state, didnt work either.
I've tried it at three different kind of servants on multiple stones and it's the same issue on all of them.

Source for expected behaviour:
http://classicdb.ch/?quest=2681

I've tried all the solutions they suggest throughout the comments and none of it worked.

Best regards
Prompt

**Comment by Thenari** [comment]
Hmm well thats not good, I remember reading about this quest line and it looked like so much work for so little reward (to a warlock) :P I know it has been completed by others who actually get use out of the quest rewards. Let me look around if anything recently changed.

my guess is the quest nodes are bugged and not running a script, if a GM higher than me can force kill/respawn the nodes it might start working again, other than that i cant do anything but thank you for reporting this and I hope it gets fixed soon.

**Comment by Brunelleschino** [comment]
Yep, all of the Servants keep getting the debuff "spirit shock" which makes them absord all damage taken even if the stones were used correctly to make them vulnerable.

**Comment by Brunelleschino** [comment]
still not working.

**Comment by Thenari** [comment]
Hey, yes its been almost a week. Im afraid Im one of the only QAs right now and I was a lil burned out I am confirming this and directly telling the Dev team to look into this.

**Comment by Thenari** [comment]
Ive been away for a bit. I suspect it works by now theres been a bunch of server resets it probs needed a turn off and turn on again fix.. adding the old. Hopefully fixed but leaving open

**Comment by Thenari** [comment]
Alright so a new issue was made so i just figured we could use this thread again.

It appears to be having trouble again.

**Comment by Thenari** [comment]
Until it does get fixed im gonna ask players who have this issue to put in an in game ticket and if you can get a GM to watch and confirm. In the ticket put the url to this github page. If you are a GM reading this I read that turning the stone node off and on again helps as a quick fix.

**Comment by Thenari** [comment]
https://classicdb.ch/?object=141812

https://classicdb.ch/?object=141857

https://classicdb.ch/?object=141858

https://classicdb.ch/?object=141859

The numbers at the end are the id numbers for the 4 stones of binding around the blasted lands

**Comment by Thenari** [comment]
From various archieves the most common issue is with the first version with id 141812 thats the south one you need to free 9 of

Its midnight here but if a player knows, are all versions having issues?

**Comment by Thenari** [comment]
Roadblock. Let me know if theres an update
