### ISSUE TITLE
[Master Post] Curse of Weakness ~20~ different spells all same name

### ISSUE THREAD

**Issue by Crusaderz** [elysium-project/classic-bug-tracker#772]
My wand deals 31-58 **frost** damage,

Before CoW debuff:

![image](https://user-images.githubusercontent.com/3641625/41195694-3b13d25c-6c3b-11e8-9b1c-5cd7a827a07b.png)

After:

![image](https://user-images.githubusercontent.com/3641625/41195706-68f00844-6c3b-11e8-986c-c9dc6d9d3603.png)

**Comment by Thenari** [comment]
Umm so you wanna explain what im looking at?

**Comment by Thenari** [comment]
Curse of weakness is all damage output

**Comment by Thenari** [comment]
At least thats how the warlock CoW works. Its useful against fast hitting swarm packs like those imps in MC cause it just makes the tank take x less damage from every attack from that mob

**Comment by Thenari** [comment]
At least thats how the warlock CoW works. Its useful against fast hitting swarm packs like those imps in MC cause it just makes the tank take x less damage from every attack from that mob

**Comment by Thenari** [comment]
Dot spells have different calculations its like -x damage over the duration of the dot i think.

I dont believe it should reduce healing though

**Comment by Crusaderz** [comment]
Mate, you closed this one too early. The CoW in question is the one used by NPCs. https://classicdb.ch/?spell=11980 according by tooltip description it reduces melee damage output, but affects spells aswell

**Comment by Crusaderz** [comment]
Does not affect damage of spells, only wand damage. Sure it's a bug.

**Comment by Crusaderz** [comment]
Still closed?

**Comment by Thenari** [comment]
The tooltip description might be wrong. Why would curse of weakness do different things from different sources they would call it something else.

**Comment by Crusaderz** [comment]
>The tooltip description might be wrong. Why would curse of weakness do different things from different sources they would call it something else.

Haha, don't apply logic here. It is a blizzard after all.

Curse of weakness, reduces all damage (casted by mobs): https://classicdb.ch/?spell=8552
Curse of weakness, reduces physical damage (casted by mobs): https://classicdb.ch/?spell=12493 https://classicdb.ch/?spell=18267 https://classicdb.ch/?spell=17227
Curse of weakness, reduces physical damage by **NEARBLY** enemies (casted by mobs): https://classicdb.ch/?spell=21007 https://classicdb.ch/?spell=12741
Curse of weakness, warlock version: https://classicdb.ch/?spell=702

As i said earlier, [this](https://classicdb.ch/?spell=11980) debuff 
![image](https://user-images.githubusercontent.com/3641625/41358736-b0fd673c-6f31-11e8-99f1-ad73e01cc215.png)
does not affect spells (my drain life damage remains the same before and after), **only wand damage is reduced**.

For example, [this](https://classicdb.ch/?spell=6922) debuff:
![image](https://user-images.githubusercontent.com/3641625/41358606-64c13e34-6f31-11e8-9af7-80019cae8445.png)
is less powerful but my drain life damage is reduced.

So tooltip description is not wrong. Wand magical damage reduced by -physical damage debuffs is a bug.

**Comment by Thenari** [comment]
Well alright. Dang blizzard why would you name a bunch of different spells the same thing :/ im confirming this.

**Comment by Thenari** [comment]
Testing each version of the spell from each of the mobs sounds like a Good First Issue or a Help Wanted!

**Comment by Thenari** [comment]
https://github.com/elysium-project/classic-bug-tracker/issues/671#issuecomment-388975403

**Comment by Thenari** [comment]
https://classicdb.ch/?npc=1564 Bloodsail warlock
https://classicdb.ch/?npc=1124 Frostmane shadowcaster
https://classicdb.ch/?npc=7112 Jaedenar Cultist
https://classicdb.ch/?npc=1144 Mosh'Ogg Witch Doctor
https://classicdb.ch/?npc=9678 Shill Dinger
https://classicdb.ch/?npc=7342 Skeletal Summoner
https://classicdb.ch/?npc=3762 Felmusk Felsworn
https://classicdb.ch/?npc=14861 Blood Steward of Kirtonos
https://classicdb.ch/?npc=9039 Doom'rel
https://classicdb.ch/?npc=11453 Wildspawn Trickster
https://classicdb.ch/?npc=4036 Rogue Flame Spirit
https://classicdb.ch/?npc=9518 Rakaiah
https://classicdb.ch/?npc=6008 Shadowsworn Warlock
https://classicdb.ch/?npc=7370 Restless Shade
https://classicdb.ch/?npc=6118 Varo'then's Ghost
https://classicdb.ch/?npc=15623 Xandivious

this seems to be all the npc's who can use curse of weakness of varius levels. lets test each one
