### ISSUE TITLE
10-19s can still not queue for wsg and pool size is hurting

### ISSUE THREAD

**Issue by Aaron182** [elysium-project/classic-bug-tracker#773]
it was taken out in 1.7 and you guys said it would be fixed even tho it wasn't blizzlike. It was fixed and we were able to queue, now it is back reversed again, and we cannot queue, I even cleared WDB, etc.

**Comment by Thenari** [comment]
Ok sorry was a long day 7hours before a reply. I dont know anything about pvp. So right now im just gonna believe you and mark this high priority. Ill also ask around if anyone on the GM team knows anything about this.

Saturday night for me here took a bit of time off :p

**Comment by Thenari** [comment]
I did tell the GMs about it in my bugtracker channel right after the message a GM s twink noticed he couldnt do batlegrounds

Updating labels

**Comment by drozdez** [comment]
@LilacKnight fixed it, let's applause her)
