### ISSUE TITLE
[Master Post] Interaction of active items and cooldowns

### ISSUE THREAD

**Issue by yandexman** [elysium-project/classic-bug-tracker#798]
Hi. Using Six Demon Bag (https://classicdb.ch/?item=7734)  procs a 3 minute cooldown on Mind Quickening Gem (https://classicdb.ch/?item=19339) and Talisman of Ephemeral Power (https://classicdb.ch/?item=18820). When i use The Mind Quickening Gem or Talisman of Ephemeral Power first the Six Demon Bag goes into cooldown for 20 seconds.

**Comment by Thenari** [comment]
When i use my hero charm from ZG my hat from gnomer final boss, Electromagnetic Gigaflux reactivator, goes on cd

**Comment by Thenari** [comment]
Theres a ton of active items, usually they have a category that shares a CD.

I dont know enough at the moment about what shares what

Its a low priority issue but thank you for giving us a reason to test

**Comment by yandexman** [comment]
Well its strange cause if you use Mind Quickening Gem the Talisman of Ephemeral Power goes on cooldown for 30 seconds or via verca. 3 minute cooldown after using six demon bag is kinda weird.

**Comment by Thenari** [comment]
Oh i must of missed that part of the issue.

I know some items have their own cooldown but also share a category cooldown that can be different.

For example warlock healthstones are 2minutes. Ungoro power crystals are 5min for the buff ones.

Using a crystal first that crystal goes on a 5min while all other crystals and healthstones go on 2min

**Comment by Thenari** [comment]
Figuring out which active items share cooldowns could be a good help wanted! Good first issue

Than figure out whats bugged and whats blizz like
