### ISSUE TITLE
fading combopoints

### ISSUE THREAD

**Issue by Psynic** [elysium-project/classic-bug-tracker#801]
Hey, i started fresh on Northdale pvp with a rogue. There is an issue with the combopoints because if i create combopoints on one target and switching to another target with autoattack only, all combopoints are lost when i switch back. Thats not the right behaviour. I should only lose my combopoints on the first target if i create combopoints on the other.

Thanks for reading!

**Comment by Thenari** [comment]
yeah ive asked a couple rogues. attacking a new target causes all combo points to be lost. this seems to be blizz-like and has been that way since the start of this server.
