### ISSUE TITLE
keyring/bag does not prevent you from making more then 12 inv slots of keys, newly made keys will start a fresh stack in the hidden 13th slot, player is unable to retrieve them.

### ISSUE THREAD

**Issue by Matataker** [elysium-project/classic-bug-tracker#802]
Hi, yesterday i made arcanite skeleton keys , seen the message about receiving them but they never actually appeared in my bags

**Comment by Matataker** [comment]
Is it possible by making a key when the keyring is full, instead of putting the key into the bags, it put it on a 13th slot that cant be seen ebcause the keyring stop at 12 ? then until you hit x10 to start a new stack, u wont be able to use those type of keys ?

**Comment by Thenari** [comment]
Umm if your bags were keyring was full. Id hope the key would go to your regular inv. But it could be a case where like DEing with a full inventory it will let you do it. The mats are used and no item is rewarded.

**Comment by Matataker** [comment]
Yeah i guess at this point i must ask GM for help if i can reproduce it

**Comment by Matataker** [comment]
[2018-07-01 17-55-17.zip](https://github.com/elysium-project/classic-bug-tracker/files/2153256/2018-07-01.17-55-17.zip)

**Comment by Matataker** [comment]
Oh in this video , i think the silver key stacked finally did hit 20x silver keys, and started a new stack in a free slot of my keyring
[2018-07-01 18-00-56.zip](https://github.com/elysium-project/classic-bug-tracker/files/2153262/2018-07-01.18-00-56.zip)

**Comment by Thenari** [comment]
welp that sure is werid! ty for all the videos showing it! that really helps

im confirming it, and I honestly dont know what to label it high or low priority to be fixed

**Comment by Thenari** [comment]
I never went down the blacksmithing route a decade ago in vanilla, I'll scan some archieved forums and see if this has happened in the past.

but right now its almost midnight on canada day and im very canadian and equally drunk.

**Comment by neverson42** [comment]
I've got the same issue happening to me. A party member traded me some keys when my keyring was full. They disappeared. I'm trying to craft more back in town and they're not going anywhere. I assume its a 13th slot that's hidden and they will likely start appearing once I craft more than a full stack of them... sure is annoying though.

https://youtu.be/mq8t41irqKY

**Comment by Matataker** [comment]
The problem is : the keys ARE in the inventory, but not visible, if you happen to make enough key to complete a stack, a new stack will start anew in your keyring... 

Basicly, the keys need to be moved from the invinsible inventory spot to a visible inventory spot

**Comment by Thenari** [comment]
Yes but they should of been blocked once the bag was full. It only happens if you get more than (12?) Items in keyslot.

**Comment by Matataker** [comment]
Yes, the bug can be reproduced easyily by fulling the keyring without bags full, just make a key you dont already posses and it will not appear. then u can make a free slot and make again, wont fill the empty keyring slot , once you get to 20 keys, stacks is full THEN they will start appearing again

**Comment by RainElysium** [comment]
Have you tried clearing your WDB folder and disabling all addons? Then check for the keys.

**Comment by Matataker** [comment]
Yes, didnt worked, they are in the void

**Comment by Thenari** [comment]
@Matataker any updates?

**Comment by Thenari** [comment]
Got another case of this happening as linked above.
