### ISSUE TITLE
[Swift Riding Turtle] auto-dismount bug?

### ISSUE THREAD

**Issue by jaeeeee** [elysium-project/classic-bug-tracker#805]
One of the most useful things about having an epic mount is the ability to quickly dismount to cast spells for combat. With every other mount in the game you're able to click an ability while riding and Lazypig, EZdismount, or AutoMate would dismount you for a seamless transition into combat. After I bought my [Swift Riding Turtle] I lost access to this essential ability. A mount that costs 250 coins should be just as capable as the other mounts! Please assist me with this feature!

**Comment by Thenari** [comment]
Umm you want the server to be responsible for your addon features?
