### ISSUE TITLE
Blackwing Legionnaire does not properly reset if mind controlled during boss phase shift

### ISSUE THREAD

**Issue by Inomares** [elysium-project/classic-bug-tracker#806]
If you (as a priest) mind control a Blackwing Legionnaire (12416) during the first boss encounter in BWL, and then your raid destroys all the eggs, the NPC will not properly reset if it is still controlled when the boss changes phase, but can also not be attacked. 

Your entire raid will be locked in combat, and a GM has to come unstuck you since you can't leave the raid while in combat.

**Expected behaviour:**
Either:
1) Mob should be killable after dropping mind control (in which case the mob should also be able to attack again - which is currently not the case)
**or**
2) The mob should reset (like the rest of them do) when the boss changes phase.

**Comment by Thenari** [comment]
Ha thats neat, most raid groups would really need the priest to help heal or something. You did something interesting :P 

I can't super test a raid fight solo but i will go ahead and wait to confirm this until i get the name of the GM you contacted to fix. Then i can just believe the GM and all.

This is rather specific wondering if its worth the time/resources to write a failsafe mechanic or if its just a rare error that an In-game GM can easily fix.

Im gonna personally label it as Low Priority In-Game GM

But that may change

**Comment by Thenari** [comment]
Made a new label for Raid lock up bugs

**Comment by Thenari** [comment]
2 weeks since the stall prompt issue is being closed. You can still comment here if you have updates
