### ISSUE TITLE
Thorium Brotherhood rep items 

### ISSUE THREAD

**Issue by kuledude123** [elysium-project/classic-bug-tracker#807]
There is no way to access friendly reputation items from thorium brotherhood(Lokhtos Darkbargainer) if u are honored with them as it removes every single item from friendly rep items and then adds honored rep items. Tried deleting the WDB folder but it didn't work.
Page 1(only honored items):
![1](https://user-images.githubusercontent.com/40152501/42414614-f12874f4-8238-11e8-9236-cca7ea55290c.png)

Page 2(only honored items)
![2](https://user-images.githubusercontent.com/40152501/42414625-04d7c1da-8239-11e8-8903-2bf48746a0ef.png)

Specific item im looking for https://classicdb.ch/?item=20761

**Comment by Thenari** [comment]
Hey kuledude that recipe comes out with AQ 1.9 Aug 4th

**Comment by Thenari** [comment]
Classicdb has a link to wiki at top of page. You can see some patch changes*** usually

**Comment by Thenari** [comment]
Theres other friendly rewards too. Bit im pretty sure you can only see them if you have the correct profession.

**Comment by Thenari** [comment]
Based on your photos you have herb and alchy.
