### ISSUE TITLE
Thorium Brotherhood rep items

### ISSUE THREAD

**Issue by kuledude123** [elysium-project/classic-bug-tracker#808]
Cannot purchase friendly rep items from Thorium Brotherhood (Lokhtos Darkbargainer) if you are honored with T.B. as the items from friendly rep get deleted and replaced with honored ones thus permanently closing me out from getting friendly rep recipes in the game. Tried deleting WDB folder and it didn't work.

Page 1(only honored items)
![1](https://user-images.githubusercontent.com/40152501/42415294-cb349aa0-8249-11e8-804e-142fa977255f.png)

Page 2(only honored items)
![2](https://user-images.githubusercontent.com/40152501/42415295-d221de40-8249-11e8-95e3-d389fd7f7bdf.png)

Specific item i'm looking is a friendly rep item:
https://classicdb.ch/?item=20761

**Comment by Thenari** [comment]
Kuledude am i missing something? Why did you make this again?

**Comment by Thenari** [comment]
#807
