### ISSUE TITLE
Alliance, quest, "Bitter Rivals"

### ISSUE THREAD

**Issue by JinxedLY** [elysium-project/classic-bug-tracker#809]
Quest given by Marleth Barleybrew.
Accepted the quest, was given the quest item - "Barrel of Barleybrew Scalder"
After accepting a quest, game froze on my end for a second and quest icon did not disappear above Marleth.
It did disappear approximately 10 seconds later.
Quest did not appear in my quest log.
I am not able to take any actions to complete the quest.
I am not able to abandon quest.
I am not able to take the quest again.

**Comment by JinxedLY** [comment]
GM responded to the ticket in-game and provided me a follow-up quest "Return to Marleth".
In chat it was written that I accepted the quest "Return to Marleth".
In quest log there was no such quest.
However, there was one extra quest - I was supposed to have 4 quests active and after GM gave me a quest, I had 5.
It was back to four upon returning to Marleth and completing the follow-up quest, but I dont remember under which name this quest was registered in log.

Something suspiciously shady going on with that quest line.

**Comment by JinxedLY** [comment]
#748 seems to be relevant.

**Comment by drozdez** [comment]
I tested it, everything goes OK. Maybe u have some addons, that causing this problem? Also u can drop all quests and start it again.

**Comment by JinxedLY** [comment]
As I mentioned in bug report, I was not able to abandon the quest because I did not have it in a quest log.
Same way as #748 could not abandon his quest.

**Comment by Thenari** [comment]
Just seeing this one. Can you plz confirm you are using no addons? And you can put in an ingame ticket a gm can see your quest records.

**Comment by JinxedLY** [comment]
Addons used are Questie and Bagnon.
Bagnon has no business interfeering with quests. Quest log is vanilla, questie is used for navigation solely.
#748 Reports using no addons at all, however.

It does not appear that issue is exclusive to specific quest or chain of quests, but rather some particulary elusive and specific bug in server-client communication. I am going to deep deeper into archive of closed reports.

**Comment by JinxedLY** [comment]
#464 Might be describing the same issue.
#459 describes similiar issue.

**Comment by JinxedLY** [comment]
GM responded that Bitter Rivals is currently active quest for my character, if I understood it correctly.
