### ISSUE TITLE
Certain Twilight Hammer mobs in Silithus are missing spells when mind controlled

### ISSUE THREAD

**Issue by Inomares** [elysium-project/classic-bug-tracker#810]
These mobs cast spells on their own, but when mind controlled they don't have any spells you can use. This affects at least (only tried a few):

[Twilight Master (11883)](http://classicdb.ch/?npc=11883#abilities)
[Twilight Stonecaller (11882)](http://classicdb.ch/?npc=11882#abilities)

You can see which abilities they should have available on classicdb, linked above.

**Comment by Thenari** [comment]
I dont personally know much about mind control. But i do remember another MC report a few months ago lets see if it has clues

**Comment by Thenari** [comment]
#371 in here i learned that each class should have a script they run to do their assigned abiities but you do not directly tell them to use spells. They are supposed to act naturally but on your team now.

**Comment by Inomares** [comment]
That is a different kind of mind control. Charm effects from Engineering's Mind Control Cap gives you the mob as a pet, similar to a temporary hunter pet or a warlock enslave.

Priest's Mind Control makes you control the targeted unit as with hunter's eyes of the beast. You "become" that unit in a way. The unit should not fight on its own.

**Comment by Thenari** [comment]
Ahh well thats weird and i dont know enough about this one. Lets ask a dev to look how it works

 (enslaving demons i get a pet bar with spells its an npc i control, most npcs have 1-4 abilities and i can either manually use them or put them all on auto use and the pet will fight as best as it can... figured it was the same with priest mc)

**Comment by Thenari** [comment]
Any updates?

**Comment by Thenari** [comment]
Maybe with the newer patches theyve been fixed?
