### ISSUE TITLE
Item changes (1.8)

### ISSUE THREAD

**Issue by Zinsora** [elysium-project/classic-bug-tracker#812]
With patch 1.8 some items like the [Icefury Wand](https://classicdb.ch/?item=7514) should get stats changes
Altough the stats really changed the wand for example still shows the old stats(0 int + 4 frostspelldmg)

**Comment by Thenari** [comment]
Before we go further, theres a folder in the same group as wow.exe i believe its called WDB. Basically it remembers item data and other stuff to display to you. In real wow you have to do a patch that changes it for you. Here you need to manually delete the contents of the file. And when you start up the game new stuff will load in.

**Comment by Thenari** [comment]
Im gonna close this but if you still need help you can still comment in here ill see it. I can reopen at any time.
