### ISSUE TITLE
Gnome ability "Escape artist" fails to remove web cast by Giant Webwood Spider in Teldrassil

### ISSUE THREAD

**Issue by JinxedLY** [elysium-project/classic-bug-tracker#814]
Whole issue was described in the title pretty much.
Spider casts web, gnome uses ability, web debuff remains.

**Comment by Thenari** [comment]
Neat! Ive never played a gnome. That spiders web might be classified as something else than a root im assuming maybe its a stun lets look into it

**Comment by Thenari** [comment]
https://classicdb.ch/?spell=20589

So its a racial spell so i should be up to the final patch of vanilla and its spell id is 20589

**Comment by Thenari** [comment]
https://classicdb.ch/?spell=745

The giant spider was the only one youve had the issue with? Most the spiders in that zone should be using the same spell id 745. Its pretty much the same one all spiders use

**Comment by Thenari** [comment]
As a tester on the ptr unless its been fixed. When on a gm toon even with gm mode off. I am unable to be buffed or debuffed except through commands.

So it would be kinda a pain for me to level up a gnome to 10ish and somehow travel to the nelf starting zone (???why are you there silly gnome ;p???)
So if you want to take a screenshot showing your gnome racial on like 59second cd cause you just used it and you still being webbed that would help. But ill eventually try to make my way there or ask someone to do a video

**Comment by JinxedLY** [comment]
(I am there for elven pussy. Those mounts are awesome when used by gnome)
I will try making a video somewhere this week.

**Comment by Thenari** [comment]
Yeah thanks for letting us know though but im gonna slap a low priority on this cause gnomes doing 5-15nelf quests?

**Comment by JinxedLY** [comment]
Traveled back to Oracle Glade. Failed to replicate. My bad.
Can escape artist be interrupted?

**Comment by JinxedLY** [comment]
No, in original scenario that led me to report the issue I used the ability at approx 5 seconds out of 10 left on the web debuff.
Spider was still attacking me at the moment, that is why I assumed that spider interrupted it, after I failed to replicate it,

**Comment by Thenari** [comment]
Can being hit interupt? It might take longer to cast but i thought unless you do a cc the spell will keep trying

**Comment by JinxedLY** [comment]
Apparently getting hit can interrupt escape artist, as I noticed 3 more cases of similiar effect over this week.

**Comment by Thenari** [comment]
I did read in a patch note that the gnome escape artist had its cd lowered. So world patch vs player patch 1.12 could be it?  Im closing for now as its been awhile.
