### ISSUE TITLE
Hero of the Stormpike quest bugged

### ISSUE THREAD

**Issue by sirdrills** [elysium-project/classic-bug-tracker#815]
Hello,

I play on Nighthaven server. Character name Drills on Alliance side. I completed the quest Battle of Alterac, and now I can't pick up the quest Hero of the Stormpike for the rewards. Please help :)

**Comment by RainElysium** [comment]
Confirmed as being disabled via db. Needs to be reenabled upon 1.8 launch for future realm launches.
