### ISSUE TITLE
Enemies fleeing at full speed

### ISSUE THREAD

**Issue by Godmatik** [elysium-project/classic-bug-tracker#816]
Enemies are fleeing at full rather than reduced speed. 

This was fixed a while back but seems to have returned, making it quite the hassle to chase them down when they are near death.

**Comment by Godmatik** [comment]
Minions that have the ability to "run away in fear" are doing so at full 100% speed when at low health, it should at reduced speed (half?)

I mean I don't know how much more specific I can be..... I'm pretty certain you can test this on any of them. Maybe people aren't putting in tickets cause they don't realize it shouldn't be this way? I play on a few different projects and just came back to Nighthaven and it's a glaring issue, admittedly I'm only level 20, so maybe this only impacts low level mobs, but so very every single one I've come across that has the ability to flee, has done so at full speed. I also recall this issue was prevalent when the realm first launched but it was acknowledged on the forums and fixed shortly after.

**Comment by Thenari** [comment]
Yeah its a common enough issue that pops up occassionally im not even near a computer but i was more asking if you could give a specific mob name you know its being weird on.

**Comment by Godmatik** [comment]
Any murloc in Darkshore, like Greymist Warriors, are a good example.

**Comment by RainElysium** [comment]
Which type of fear are you seeing this happening on? Any particular spell?

**Comment by Godmatik** [comment]
Hey Rain,

Yes it is flee when they take a certain amount of battle damage and run, not from any fear effect.

Are you testing on the Nighthaven server or your dev realm? I was playing all last night, mobs were definitely still running at full speed, test it for example on any murloc in Redridge.

**Comment by Thenari** [comment]
Any update on this? @Godmatik @RainElysium

**Comment by RainElysium** [comment]
I was testing on live, yes :) Try and reproduce and add video for me.

**Comment by Godmatik** [comment]
I don't have video capabilities I'm afraid, so I guess I will have to leave it to you guys to figure out or say that this is resolved.

So is it blizzlike that they run away at full speed though? A couple of other projects I play on using the Nost code don't have this same behavior, they run away at a reduced speed like they have a movement debuff on them.

**Comment by RainElysium** [comment]
Well its not a movement debuff, their speed is just decreased. However the problem with this report is I'm unable to reproduce what you're describing. They run at a reduced speed for me once "fleeing".

**Comment by Thenari** [comment]
Could be a visual client side?

**Comment by Thenari** [comment]
Its been almost 20days since the roadblock. This could not be reproduced so it is being closed. You can still comment if it needs to be reopened.
