### ISSUE TITLE
Warlock "improve drain soul"

### ISSUE THREAD

**Issue by eken15** [elysium-project/classic-bug-tracker#817]
Hi,

My talent "improve drain soul" seems to not work. Only work some times but not 100% as the talent says.

**Comment by Thenari** [comment]
Its probs working as intended its just a bitch of the fine print.

Your damage needs to be what kills the target. No pet. No party mate helping you. If anyone else gets the last hit you arent rewarded.

**Comment by Thenari** [comment]
![screenshot_20180716-114658_chrome](https://user-images.githubusercontent.com/38762769/42768549-d535c826-88ed-11e8-8fde-ae7fff74a56b.jpg)
