### ISSUE TITLE
Missing glove icon on character on shop

### ISSUE THREAD

**Issue by taleus** [elysium-project/classic-bug-tracker#822]
https://cp.elysium-project.org/armory/char-1-306497

But I got gloves on the char when I put it up for auction

**Comment by Thenari** [comment]
Hmm not sure if this is the place for that have you tried getting help on the forums there should be a shop "help" section. Not my department sorry ill ask around

**Comment by Thenari** [comment]
This is an issue i have no way to help with. And normally when people with these issues get help from the other teams their issue stays open forever here so im just gonna close this page. You can still comment and stuff but this is a specific issue to just you so i dont think anyone else will be referencing this page.

**Comment by RainElysium** [comment]
Please tell us which gloves you're using and provide a screenshot of your character screen to confirm.

**Comment by taleus** [comment]
![image](https://user-images.githubusercontent.com/40151886/43082022-4c40e888-8e93-11e8-9c06-d76dbcefc307.png)
