### ISSUE TITLE
Stormwind Keep, Royal Gallery Plaques

### ISSUE THREAD

**Issue by JinxedLY** [elysium-project/classic-bug-tracker#826]
Plaques for statues are messed up in Royal Gallery.
One single statue has plaque sitting where it belongs - no issues with that one.
![20180722005718_1](https://user-images.githubusercontent.com/40932005/43040361-78530ee6-8d4a-11e8-9961-ce420a588b5c.jpg)
Another plaque is all messed up, but still accessible at least.
![20180722005722_1](https://user-images.githubusercontent.com/40932005/43040363-7c069db4-8d4a-11e8-9c9b-8f6432ef022b.jpg)
All other plaques are either non-existant or unreachable.
![20180722005725_1](https://user-images.githubusercontent.com/40932005/43040365-80012786-8d4a-11e8-8748-2f8673f8988a.jpg)

**Comment by Thenari** [comment]
I believe that is intended, Its like that because Alliance don't deserve nice things

**Comment by JinxedLY** [comment]
I dont know how to respond to that.

**Comment by RainElysium** [comment]
Need evidence of what should be here please.

**Comment by RainElysium** [comment]
Evidence visible here. Fix pushed to repo.

http://moon-guard.wikia.com/wiki/Royal_Gallery_(Stormwind)
