### ISSUE TITLE
Inventor's Focal Sword Incorrect stats

### ISSUE THREAD

**Issue by RainElysium** [elysium-project/classic-bug-tracker#828]
Stats are set at post 1.10 version.

Evidence:

http://web.archive.org/web/20050206201843/http://wow.allakhazam.com:80/db/item.html?witem=17719

Current stats:
![image](https://user-images.githubusercontent.com/33706636/43048901-60b4d274-8dbd-11e8-8f51-452feb5009c6.png)

**Comment by Thenari** [comment]
Oh yeah i was just reading that satyr's bow and inventor's focal sword and undying scepter all got a nerf in 1.10
