### ISSUE TITLE
Reputation discount dont work!

### ISSUE THREAD

**Issue by Mewrik95** [elysium-project/classic-bug-tracker#834]
Hello, my problem:
i (Nevendar) take exalted with orgrimar and a discount must be 20%, but i came to mount vendor and a discount = 10% like on honored reputation. plz corect this mistake. i whant buy mount for 800g not by 900g.
Please help.

**Comment by Godmatik** [comment]
In Vanilla, you get a 10% discount for being Honored, and a 10% discount for being Rank 3 PvP.

Being revered or exalted doesn't reduce the price any further. That wasn't implemented until late Burning Crusade.
