### ISSUE TITLE
Quest: Supplying the Front

### ISSUE THREAD

**Issue by mkosiorkiewicz** [elysium-project/classic-bug-tracker#836]
Alliance, Night Elf, Warrior, lvl 21
Wrong requirements to complete the quest.

quest description: http://www.wowhead.com/quest=1578/supplying-the-front,

To complete quest you require to have Copper Axe (6) and Copper Plate Belt (6) in your inventory, however you have to create 7 of each of those items to make quest completed.

**Comment by drozdez** [comment]
Are you sure that you need 7 of them? I tried it on my local and it worked as intended. I think you had something like addon problems, but thank you for your recourse)
