### ISSUE TITLE
Alliance, quest, 'The Deserters"

### ISSUE THREAD

**Issue by JinxedLY** [elysium-project/classic-bug-tracker#837]
Theramore deserters guarding the q guy are supposed to be hostile until q guy is defeated.
They are friendly.

**Comment by drozdez** [comment]
Can you explain more concretely please? ^^

**Comment by JinxedLY** [comment]
Investigated the matter.
It appears that blizzard fixed the issue only in 2.3.0.

Issue was that Theramore Deserter NPCs are friendly towards alliance players, where it is heavily implied that they should be hostile.
Intended behavior was that they are hostile until player reaches and deals enough damage to Balos Jacken.

**Comment by Thenari** [comment]
So. Thats blizz like?
Tenatively closing as a blizz-like and confirmed. Maybe a low priority too
