### ISSUE TITLE
World chat

### ISSUE THREAD

**Issue by JinxedLY** [elysium-project/classic-bug-tracker#840]
Sent a report for GM to peek into world chat, which had a lengthy debate including heavy language and insults, and fix the situation.
Few hours later received a letter from GM to open a ticket here.
![20180731030757_1](https://user-images.githubusercontent.com/40932005/43602317-4b6d453e-9698-11e8-8c04-6de233a8e202.jpg)

**Comment by Godmatik** [comment]
That GM had to be mistaken. It's not a bug that people are using (what you consider to be) offensive language in world chat....

**Comment by Thenari** [comment]
Yeah im afraid this is Quality Assurance. We mostly deal with bugs and glitches. Thats a player based issue the game master and maybe community manager can help with that. Labelling this with invalid.

But if you see hate speech on public channels thats against TOU take a screenshot and tell someone usually in game but if you want you can drop it in here as github hosts pictures. Just hit print screen and ctrl v into a comment and github auto hosts. Thats not the best method but itll keep it somewhere public. Theres also the discord server you can use to get someone to help
