### ISSUE TITLE
Quests available to only some players in Silithus

### ISSUE THREAD

**Issue by plastexd** [elysium-project/classic-bug-tracker#842]
Hello. Your dev team included quests people were NOT supposed to get before the AQ doors open. You removed them from the NPCs but people who got them before you did that can still complete them and get the rewards which is an highly unfair advantage.

Quests such as Starlwart's Battlegear that give epic rewards

Could you please fix that and remove the quests from everyone's quest log?

**Comment by drozdez** [comment]
Sorry for this issue! We are working on fixing it right now! thank you for your recourse!
