### ISSUE TITLE
improved drain life talent not improving the spell

### ISSUE THREAD

**Issue by omfgyou** [elysium-project/classic-bug-tracker#847]
5/5 talents should increase the health drained by 10%, my spell tooltip says it should do 18-19 damage, so with 10% it should be like 20-21, but it always ticks for 18 only! checked combat log, no resists or absorb, 18 damage done, 18 healed. So its working properly you say?
![drai1](https://user-images.githubusercontent.com/42284842/43986323-a39b85c2-9d0f-11e8-9e2a-dfcd0e81cffd.jpg)
![drai11](https://user-images.githubusercontent.com/42284842/43986327-a71a5746-9d0f-11e8-8f45-a799510b287c.jpg)

**Comment by omfgyou** [comment]
![drain11](https://user-images.githubusercontent.com/42284842/43986346-e48a1c92-9d0f-11e8-8135-6537eb687ab0.jpg)

**Comment by Thenari** [comment]
Rank 2 is 17 per tick normally the 18 you see is updated by talents and spell power

**Comment by Thenari** [comment]
The spell tooltip has scaling numbers so if it says 17-18 it will (unless another player debuffs the enemy to be weaker to that dmg type)
