### ISSUE TITLE
Can not train leatherworking 1 to 75

### ISSUE THREAD

**Issue by TheGreyMouser** [elysium-project/classic-bug-tracker#851]
Realm Nighthaven
Leatherworking trainers not training apprentice leather working.. they start at jouneyman *SW and IF* req lv10 + 50 lw skill.  Impossible to get to 50 since 1-75 apprentice can not be trained. 
I checked the filters, and my skills panel.  Apprentice leatherworking just isn't there. 

Contacted GM in game twice.  I think 2nd ticket was deleted but issue not resolved.
Steps taken
Per GM
Delete WDB folder and disable add ons
Not resolved
Deleted new WDB folder and WTF folder, add ons disabled
Not resolved.
Attempted to log on another character to train LW, apprentice still not available in SW or IF

Opened ticket  on Github

Thanks for any help

**Comment by Thenari** [comment]
Can you go ahead and press the "k" button and go to the section i think its alphabetical look for leatherworking in there. If you find it screenshot it. If not screenshot all the pages and post it here for me. Ty :)

**Comment by Thenari** [comment]
Oh theres also a skill tab when you press "C" and go to your character sheet. Screenshot the professions area of the skill page.   You can hit print screen button on your keyboard and ctrl+v right into the comment box and github will host it

**Comment by TheGreyMouser** [comment]
resolved in game.   Issue was I was trying to train at the trainer, apparently i should have been training at the apprentice.

thanks.

________________________________
