### ISSUE TITLE
Cannot equip pvp rank items after nighthaven merge

### ISSUE THREAD

**Issue by Lencaar** [elysium-project/classic-bug-tracker#853]
As the title states, I am unable to equip my 'Blood Guard's Dreadweave Boots' after logging in to my character. 

This character did have the Blood Guard rank prior to the merge, when it existed on the Darrowshire realm, but was inactive for some time, and so the rank would have decayed heavily. On Nighthaven, my 'Highest Rank' is listed as 'None'. I also have no current rank, either.

It is noteworthy that I logged on with the above item equipped, along with the matching gloves, but, after un-equipping, I cannot re-equip.

**Comment by Thenari** [comment]
I know merging servers isnt blizz-like so there can be sone unexpected issues. Thank you for letting us know. I think Im supposed to use the black label about our server being the issue. Also ill slap on a battlegrounds related too.

**Comment by Thenari** [comment]
This may not be a Github issue in a bit. Someone high up needs to make a decision.

Its basically to use pvp items do you need to pvp on this server again to get the rank. Or can we move the honour rank data from toon from previous server to this version of that toon on current server

**Comment by RainElysium** [comment]
Greetings,

To maintain the integrity of the pvp standings on Nighthaven, we elected to not carry over rank points of players that were merged from other servers. This is why you are unable to equip the items.

In order to re-equip them, you’ll need to achieve the rank on NH!
