### ISSUE TITLE
Searing Totem attacks don't have a variable damage range and are unable to crit

### ISSUE THREAD

**Issue by JosLi** [elysium-project/classic-bug-tracker#854]
Unsure if it only affects rank 1 and only with points in Call of Flame, but the searing totem on my orc shaman does 10 damage every single hit (tooltip says 9-13 with 2/3 points in Call of Flame) and never crits.

**Comment by Thenari** [comment]
I've never really played shammy but i feel like it must be a lower rank issue otherwise a lot more shammies would let us know :p let me look up some archives on shaman stuff

**Comment by Thenari** [comment]
Also ive seen a couple reports. Talents with a +% dmg normally update the spell description to reflect the new dmg. But also rank 1 spells doing 10dmg a +5% or +10% might be 1 extra dmg (there is hidden decimals for rounding) also a quick internet search I had trouble confirming if searing totem can even crit, if you have a source please show me :)

Rank 1 searing totem in vanilla apparently is different from other ranks though it has increased spell dmg scaling which is weird.
