### ISSUE TITLE
Druid class quest lvl 50 "Torwa Pathfinder" doesn't exist

### ISSUE THREAD

**Issue by Johnnii** [elysium-project/classic-bug-tracker#856]
The Druid class quest "Torwa Pathfinder" isn't available, even though it was added in patch 1.8

Soure:
https://wow.gamepedia.com/Quest:Torwa_Pathfinder

**Comment by Johnnii** [comment]
Nvm, the wowpedia patch changes is faulty, Druid quest doesnt get added until 1.10

**Comment by Thenari** [comment]
Hmm thats really weird. Just to be sure you do not actually need to breadcrumb quest you can go straight to the tauren at the bottom of the ramp from silithus to ungoro. I did read that the breadcrumb quest was changed on what druid npcs know about it
