### ISSUE TITLE
Battle shout + Talen tree (5) not enough attack power

### ISSUE THREAD

**Issue by Mysensed** [elysium-project/classic-bug-tracker#857]
Hi,

Nighthaven pvp 1.9

As a warrior I've got 5 talent point in battle shout (+25%). If i hover over the spell it tells me +231 attack power. However, when i cast the buff and i hover over the top right. It tells me +192 attack power.

Kind regards
Sander (Mysense)

**Comment by Thenari** [comment]
Yep this is a new one but a known category of issues #749 closing this and moving your comment to there.

It is a blizz-like *Visual* error. It has no mechanical difference just the buff says wrong number.
