### ISSUE TITLE
Pink Mageweave shirt

### ISSUE THREAD

**Issue by hawkkor** [elysium-project/classic-bug-tracker#858]
Hi! I found some bug here in UC Josephine Lister nps (Master Shadoweave Tailor) can teach you  how to create a pink mageweave shirt  when you skill tailoring is 75.

**Comment by Thenari** [comment]
I always just assumed she taught that cause the colours go well together. Let me look up stuff.

**Comment by Thenari** [comment]
Yes it appears she should not have this recipe based on the archives of her training page. Also pink mageweave is i think lvl 225 tailoring.

I suppose one could make pink mageweave shirts from lvl 75 all the way to like 250 but that would be pretty expensive (also you cant bolt mageweave yourself until i think 175)

So i put it low priority but it is true she should not have that.

**Comment by Thenari** [comment]
I heard she is supposed to turn you down until you hit like 200+ tailoring. So maybe she has a talk page that isnt being used. Something like you aren't ready for what i teach.

**Comment by Thenari** [comment]
I believe this could be a good first issue. Remove shadowweave trainers from teaching pink mageweave shirt.

**Comment by Thenari** [comment]
https://classicdb.ch/?item=10317
Vendors in cities sell the pattern so she shouldnt even have that to teach

**Comment by RainElysium** [comment]
Fix. Was wrong spell completely, and was on the wrong NPCs. See below.
![image](https://user-images.githubusercontent.com/33706636/45450759-287eea80-b6a7-11e8-8df0-0f1daa823d41.png)

**Comment by Thenari** [comment]
Idk what im looking at there? No trainer should teach pink mageweave shirt. It is a buyable pattern papet
