### ISSUE TITLE
Scarab Lord title

### ISSUE THREAD

**Issue by Ticktackbar** [elysium-project/classic-bug-tracker#859]
When finishing the quest Bang the Gong. I recieved my mount, but no title.

**Comment by Thenari** [comment]
https://wow.gamepedia.com/Title#History_of_PvP_Honor_System_Titles

Pretty sure titles pre-2.0.0 are just pvp

**Comment by Thenari** [comment]
I've asked a few people but I'm wrong sometimes so show me sources :D

**Comment by Thenari** [comment]
https://wow.gamepedia.com/Patch_2.0.3

**Comment by Thenari** [comment]
![screenshot_20180827-132342_chrome](https://user-images.githubusercontent.com/38762769/44675188-c4e59380-a9fd-11e8-9f02-956d569ae24c.jpg)

**Comment by Thenari** [comment]
http://wowwiki.wikia.com/wiki/Scarab_Lord

**Comment by Thenari** [comment]
![screenshot_20180827-132927_chrome](https://user-images.githubusercontent.com/38762769/44675279-0ece7980-a9fe-11e8-8c6e-ebbcde6da374.jpg)

**Comment by Thenari** [comment]
On mobile and on subway to school sorry if the uploads are jumbled

But im at like 99% scarab lord title was awarded 2.0.3 as like a backlog backdated award kind of thing

**Comment by Thenari** [comment]
If this server decided and wanted to give the players who did the quest an award that would be divergent from blizz-like and not an issue for this github. Instead redirect your inquries to the discord support channels or the elyisum-project forums
