### ISSUE TITLE
AQ20 - Ossirian - Clicking the Crystals does not weaken him

### ISSUE THREAD

**Issue by Wolve1** [elysium-project/classic-bug-tracker#860]
Clicking the crystals at Ossirian in AQ20 does not remove his Supreme Mode buff.

**Comment by Thenari** [comment]
GM discord is aware of this issue. Raid bugs are always High-Priority and we hope we can pump out a fix soon!

**Comment by Thenari** [comment]
I threw down an assign of @LilacKnight as I believe the github bot said some new code was added.

I was able to assign you to a issue so i believe you should be able to add the label tags

Go ahead and add the fixed but needs to be tested. Or with a Leads go ahead you can push it straiht to live

**Comment by Thenari** [comment]
Alright well i have been told this has been fixed and can be labelled fixed and closed.
