### ISSUE TITLE
Twilight Marauders in Evade fight with Cenarion Outriders (Forever)

### ISSUE THREAD

**Issue by Thenari** [elysium-project/classic-bug-tracker#861]
Its in the title.

I've known about it since before May 2018 just wasnt super important until now and i never bothered to document it cause im a "Lazy Tester"

**Comment by Thenari** [comment]
I labeled it In-Game GM because if you really super duper need to do the silithus Quest (you really dont theres easier ones :p) you can put in a ticket and a GM is able to .kill all involved in the fight of evades and cause the marauders the respawn elsewhere but they have the potential to get restuck again when they spawn so this is a band-aid solution we will need a developer to do some code work to fix it properly

**Comment by Thenari** [comment]
I believe this has been worked on the marauder's are still pretty buggy but manageable

![image](https://user-images.githubusercontent.com/38762769/46160909-0615d100-c252-11e8-9fa4-a397c0bbb36f.png)

they umm "fly" in a straight fast evading line to their spawn in the north east corner of Silithus when they get stuck, about once/4hours you can see them zoom by

**Comment by ZicoQA** [comment]
this has been fixed on live
