### ISSUE TITLE
Curse of weakness reduces ranged damage to zero

### ISSUE THREAD

**Issue by SAlsum** [elysium-project/classic-bug-tracker#863]
I am a level 53 hunter (UllAesir), and I have noticed (and tested many times after noticing) that whenever I am afflicted with the curse of weakness spell cast by either the Jaedenar Cultist, or the Jadefire Trickster (reduces physical damage by 27), my ranged attacks (using Verdant Keeper's Aim and Sharp Arrows) do no damage at all.

I turned the floating combat text on, as well as checking the combat log to verify that this is the case, and in fact although ranged attack animation still happens, there is simply no entry for it in the combat log whatsoever.

![curse_of_weakness_bug](https://user-images.githubusercontent.com/16842373/44704931-f25c2c80-aa51-11e8-9d30-450625f3d3ff.png)

I was casting auto-shot during this whole fight, and as you can see it is not showing up in the combat log.

**Comment by Thenari** [comment]
Theres a master post for this issue im closing and redirecting to there

**Comment by Thenari** [comment]
#658 #772 #417 #796 its one of these one sec
