### ISSUE TITLE
Prophet Skeram evasion

### ISSUE THREAD

**Issue by AfterShave** [elysium-project/classic-bug-tracker#864]
If a player pulls aggro on Skeram while standing on the ledges beside the stairs on the encounter, he may evade and force a reset on the encounter.

**Comment by Thenari** [comment]
This might be intentional. Its a anti-cheese. If the mob cant defend itself because it is unable to path to the player it will evade. 

I dont know anything about the AQ content so i wont label this ill leave it for someone else for now

**Comment by Thenari** [comment]
Please if you can answer this.

If the player with agro left the safe spot ledge would the boss continue?

Safe spotting against mobs in the wild have timers on when they reset. Boss' normally cant reset so you need to he careful if cheesing a boss.

**Comment by Thenari** [comment]
I've been told this has been fixed and this can be closed now.

**Comment by ZicoQA** [comment]
This is supposed to happen. as thenari mentioned. Blizz intended that people did not stand on the ledges to make the fight harder
