### ISSUE TITLE
Problems with handing in Pvp marks ( Wsg, AB and AV ) 

### ISSUE THREAD

**Issue by Saltan12** [elysium-project/classic-bug-tracker#865]
hello there techinal support team, i got redirected from GM - Roia.

My issues is as  described in the title, that i cant hand any pvp marks in, at the pvp area in Ironforge.
everytime i try i get " item not found " that means, everytime i have to turn marks in i have to travel to Ashenvale, Arathi highlands, or Hilsbrad foothills to hand in.

looking forward to hear from you

Saltan

**Comment by Thenari** [comment]
I do not typically deal with vanilla pvp battleground bugs as they have intense archive history on what is and is not valid... but i can do some info intake.

Do you have any quest or inventory addons (go ahead and list all addons)

For us to help you better, please confirm which npc in ironforge you are going to. And the name of the quest you are using and the item in your inventory (they have number IDs we can look through the big code database thingy)

**Comment by ZicoQA** [comment]
This is working as intended on live. If any players have this issue please say.
