### ISSUE TITLE
Free From the Hold / Barrens > Northwatch Hold

### ISSUE THREAD

**Issue by Willoftheforsaken** [elysium-project/classic-bug-tracker#866]
Hello everyone,

The NPC is locating at an inappropriate place on the hill while he is suppose to be in the first tower at Northwatch Hold.

When you start the quest, the NPC start to run with a high speed and then finally disappear until you get a "Free From the Hold Failed" message.

Please kindly have a look to this issue.

Thank you very much!

Player

**Comment by Thenari** [comment]
https://classicdb.ch/?quest=898

This isnt a site for sources but the comment section is insightful

This is a blizz-like feature of escort quests. They suck and everyone hates them.

**Comment by Thenari** [comment]
This is a muilti script quest at a low level with pitiful rewards honestly there is a very low chance this will be fixed as we have always less than a handful of smart people able to adjust code on the elysium volunteer dev team.

But thank you for letting us know :)

**Comment by Thenari** [comment]
Spawning outside his "prison" is unusual though. But even still he runs very fast and picks fights with everything hes sees. He almost certainly didn't disappear when he ran off at high speed.

He gets himself killed at least 9/10 quest attempts cause this quest is awful and you should move on to more fun aspects of the barrens :p

**Comment by Thenari** [comment]
I am closing this. You can comment here further but basically this quest is intended to suck
