### ISSUE TITLE
Paladin - Holy Shield and Blocking

### ISSUE THREAD

**Issue by frostborn** [elysium-project/classic-bug-tracker#867]
Have anyone reported that paladins can't holy shield (or block at all for that matter) fire elementals "physical" hits with his fists? It is quite annoying that it can't be used for tanking purposes. There are a lot of them in for instance Blackrock Depths (BRD) - AND there are a few fire elemental bosse around. Furthermore, due to unblockable attacks, Blessing of Sanctuary will also not trigger (except the reduced damage part). Paladins can't generate threat for these enemies in a normal fashion.

However - must be mentioned in relation to this - retribution aura does trigger for their fist attacks... I find this very odd? Is this a bug of some kind or is it meant to not be blockable? 

Haven't notice the same for air or water elementals - but will check on this and report back if possible.

**Comment by frostborn** [comment]
Alright, I have checked the other elementals; air, earth and water.

Retribution aura works for all of them. Blocking works only for earth elemental, and is mostly due to their attacks are different. According to combat log, earth elemental "hits" you and therefore classified as a "physical" attack (common attack), while for air, water and fire, the hit is classed as a "magic" attack (X air, water, fire damage). 

This doesn't make things easier, rather more complicated. For instance, why does retribution aura, which is triggered by strike, get triggered from a magic attack - but not from magical spells. The same should be applied for blocking. Of course, none of them should be triggered from magical spells.

**Comment by frostborn** [comment]
Oh, By the way, this should also affect Warriors, which also uses blocking for tanking (although not as much or critical as/for paladin).

**Comment by Thenari** [comment]
Holy shield says if attack blocked x happens

Retribution aura says if struck x happens

**Comment by Thenari** [comment]
Retribution aura is https://classicdb.ch/?spell=10301

Holy shield is

**Comment by Thenari** [comment]
Ughguh mobile is being a dick cant use my clipboard and I accidentally closed issue

(My phone updated overnight and keyboard went to default it is clicking each keystroke gross)

**Comment by Thenari** [comment]
Also this is not a forum so can you edit the title with the specific bug in question.

Are you concerned that you should be able to block fire ele attack?

From my basic understanding the blocking guide said it only blocks melee physical.

The elementals except earth are all melee magic.

**Comment by Thenari** [comment]
I'm reading this again. You seem to solve your own issue. In your second comment you confirm the ele use magic dmg. Except earth therefore no blocking. But retribution is not a block trigger it is a dmg shield
. Like thorns or an imp fire shield. If dmg'd do dmg to attacker.

**Comment by frostborn** [comment]
Sorry, Didn't see all your messages until now.

**"You seem to solve your own issue."** I have reported how the mechanics seems to be working now and questioning the mechanics, not solved the them. 

As I see it, the holy shield ability should work / trigger just as retribution aura does. The holy shield is more or less the prime ability for the protection talent tree to be used for generating threat and thereby tanking. For paladin - any shield user in fact - this not just eliminates the blocking purposes (damage reduction), but for paladin, also the threat generation. I don't believe the game designers would want the shield carries to have this kind of limitation in mind. 

"**Are you concerned that you should be able to block fire ele attack?**" Um, yea indeed I am. But, due to its nature (magic dmg) it should be calculated by resistance, instead of armor (physical). It should block the fire elemental fist attacks (a semi-"physical" attack) to withhold the tanking principles within the game. The spell abilities of course are not intended for blocking - it's a spell. A warrior for instance, doesn't experience these problems, due to their different threat generation mechanics. Same for Shamans actually. For these two classes, it just means a damage reduction. But for Paladins It neglects not just the blocked attack (reducing damage) but also the threat generated by this ability. Same thought process for Blessing of Sanctuary - No block, no holy damage, therefore no threat generated.

"**But retribution is not a block trigger it is a dmg shield. Like thorns or an imp fire shield. If dmg'd do dmg to attacker.**" If retribution works as you say (Referring to: "If dmg'd do dmg to attacker") Why doesn't it trigger on spell abilities (for instance fireblast from mage). Its not consistent in between these two functions.

I can of course be wrong, because the only thing that would eliminate these speculations, is the idea of air, water, and fire are magical elemental. Which is why they have magic attacks. And for that reason it nullifies the physical properties of a shield. Fine! But with these possible intentions it means it ruins the conditions for paladin to tank properly. Which I think is wrong. There are some that states that paladins can't tank in classic wow, or they can't tank without consecration (paladin spell, holy). With these mechanics which I have show, clearly motivates these gamer's statements. I believe it these statements are wrong.

I see a flaw in the mechanics. My questions to you are of these following examples:
- "OBS! Do you see the same thing as I do?"
- "Is this a blizzard coding or -design flaw?
- "Just like a faulty quest - Should this mechanic be corrected for proper function?"
- "If so, Do you have the ability or desire to correct this?"

**Comment by Thenari** [comment]
Dmg shields are always melee. So blocking with a shield to trigger holy shield needs to be a melee attack and physical. Dmg shields like retribution druid throns. Priest weakness thing. Gift of arthus. Imp fire shield. Crystal spire. Those just need to be melee.

**Comment by Thenari** [comment]
Also the argument that i wanna use my spec but the game is unfairly punishing towards it... im a fire warlock. Completely unusable for a bunch of the early content but its my aesthetic so i use it :p

**Comment by Thenari** [comment]
Like mages who wanna raid cant use fire until AQ. Its the nature of vanilla. Your class as a mage means you are almost required to be frost until patchs open up new content that isnt fire immune

**Comment by Thenari** [comment]
Later blizzard opens up. And viability becomes a thing. The classic experience is having OP and weak specs

**Comment by Thenari** [comment]
What you are talking about is a main discussion for what will the official WoW clsssic look like. The arguements of keep it the same as 2006 or start at 1.12.1 player mechanics. Or add quality of life changes. Those kind of talks are for the forums and discord not github.

**Comment by frostborn** [comment]
"**What you are talking about is a main discussion for what will the official WoW clsssic look like. The arguements of keep it the same as 2006 or start at 1.12.1 player mechanics. **" Of course the topic at hand is for the forums. I don't deny that. Some issues would be nice to improve for better experience.

"**Or add quality of life changes. Those kind of talks are for the forums and discord not github.**" But you have clearly misunderstood this for common forum speculations/discussion and missed the questions at hand. I have asked the questions, were misunderstood on the way... I didn't come here to chat as if a common forum. However, It's been judged as such....

**Comment by frostborn** [comment]
Another perspective of the issue:

**Blocking with shield**
- Fire elemental fist attack: Counts as magic. Does not trigger holy shield.
- Ice elemental fist attack: Counts as magic. Does not trigger holy shield.
- Water elemental fist attack: Counts as magic. Does not trigger holy shield.
- Earth elemental fist attack: Counts as physical!? Triggers holy shield.

**Retribution Aura**
- Fire elemental fist attack: Triggers retribution aura.
- Ice elemental fist attack: Triggers retribution aura.
- Water elemental fist attack: Triggers retribution aura.
- Earth elemental fist attack: Triggers retribution aura.

So the point is that there is an inconsistency here. Why does holy shield only trigger for earth while retribution aura triggers for everything? Looks like a bug to me.

**Comment by Thenari** [comment]
Its not inconsistant. Blocking needs 2 things melee+physical.
Retribution aura just needs melee
