### ISSUE TITLE
Mazzaranache quest

### ISSUE THREAD

**Issue by nanodesu88** [elysium-project/classic-bug-tracker#868]
item for quest does not drops. killed about ~50 mobs - 0 items
quest id: 766
item id: 4807

**Comment by Thenari** [comment]
https://classicdb.ch/?quest=766
Is what im looking at. Im not home im on transit. Its a really early game quest so the item drops are 80%

This is an awkward thing but ive done it myself. If you are in a raid group you cannot get quest progress.

If that wasnt the root of the issue ill check it out when i get home.

**Comment by Thenari** [comment]
You put an item id the swoop gizzard is that the only one you cant find?

**Comment by Thenari** [comment]
![screenshot_20180831-170446_chrome](https://user-images.githubusercontent.com/38762769/44935735-eae19f80-ad3f-11e8-99c3-c0c84ac2f2e7.jpg)

**Comment by Thenari** [comment]
This database hae them at 100% (which isnt always true) but just confirm you are killing one of the mobs listed with Swoop in its name.

**Comment by Thenari** [comment]
Also finally. The quest log is sometimes a bit wonky in vanilla double check you dont already have one in your inventory as then youd be unable to find another.

**Comment by nanodesu88** [comment]
@Thenari yes. 3 of 4 items drops almost instantly, but swoop gizzard does not drops after killing a lot of mobs. i am farming Swoop and Taloned Swoop. Did not killed any Wire Swoops

**Comment by Thenari** [comment]
Hmm. If you are on now you can contact a GM ingame with the red "?" To the left of your bags. Copy the URL to this issue in your ticket. An in game GM can take a look at things I can't view will on a bus 45min away from my computer :)

**Comment by nanodesu88** [comment]
GM give me an item and told developers will fix it

**Comment by Thenari** [comment]
Haha thats nice of the GM. It might of just been a drop and retake quest cause wow is code is a mess lol


Im gonna put this as low issue and good first issue if a new dev wants to try. Its a pre lvl 10 quest its very insignificant lol

Also im pretty sure it not working is new or a fluke otherwise someone would of told us by now. Oh well at least you got closure :P

**Comment by nanodesu88** [comment]
I did trying to abbadon and retake quest - no result

**Comment by Thenari** [comment]
Its a weird one because Im very certain no Dev was fiddingly with a lvl 4-8 quest drop rates. It must be a chain of an error that lead to this. May fix itself in an upcoming patch. Ty for letting us know

**Comment by RainElysium** [comment]
Fixed.
