### ISSUE TITLE
Disenchanting epics not giving crafting mats

### ISSUE THREAD

**Issue by pl4ything** [elysium-project/classic-bug-tracker#870]
disenchanting any epic items ilvl 56 and above gives no enchanting mats of any sort, should be a 100% chance for [item=20725] Nexus Crystal

The item that was initially reported in discord support was 19369

**Comment by pl4ything** [comment]
Plenty of bag space and a loot window still should have popped up but it didn't. tried many epics from different raids and nothing showed.

https://www.youtube.com/watch?v=M_rO93jxRjk&feature=youtu.be

**Comment by Thenari** [comment]
You are in GM mode buddy :p

**Comment by pl4ything** [comment]
Turned off GM mode same result. made a new account and maxed out enchanting, same result no loot.

**Comment by shenna-elysium** [comment]
Will be fine after server restart/crash.
