### ISSUE TITLE
Quest "Dear Pamela" Eastern Plaguelands

### ISSUE THREAD

**Issue by Believe82** [elysium-project/classic-bug-tracker#871]
While doing the quest Dear Pamela I noticed that the "ghost of the Past" mob that are suppose to spawn are spawning in an increased rate. In the hut where the head is, two are spawning when you enter the hut and a third almost 1m after you kill the first. If I remember correctly this quest should have one protector and one spawn after you loot the doll piece.

Thank you for your help.

**Comment by Thenari** [comment]
Its a scripted spawn. They spawn when you get near the quest item. Looting the quest item has a chance to cause a new one to spawn right where you just picked it up which would trigger the spawn again. Each spawn trigger is 1 or 2 ghosts.

It is intense but blizz-like intense. An oversight of the scripts most likely.

**Comment by Thenari** [comment]
Let me get some screenshots

**Comment by Thenari** [comment]
A double check there should be 2 nodes for each of the 3 pieces for 6 nodes very close nearby. It's likely they all shouldnt be up at once but blizzard must of assumed the amount of players doing the quest was high haha.

**Comment by Thenari** [comment]
Im gonna close this let me link my sources and if you have sources that bring new info let us know!

**Comment by Thenari** [comment]
https://classicdb.ch/?spell=17132

Heres the doll trap trigger if you go near it summons a ghost that lasts 5min. (If a player just was here before you the ghost does not despawn btw it goes back to hiding cause spooky ghost)

**Comment by Thenari** [comment]
I wonder if a rogue can disarm it lol

**Comment by Believe82** [comment]
Its spawning 2 mobs when you get close
