### ISSUE TITLE
Arcane Missiles, spell consumes mana and player channels but no damage is done.

### ISSUE THREAD

**Issue by ShunnieMage** [elysium-project/classic-bug-tracker#872]
Hello! It is a repost from Elysium Project forum (Help & Support section):

A strange bug was happening often today (and yesterday). While trying to cast Arcane Missiles spell (being a mage) in Warsong Gulch, in many cases I've just spent mana and stood channeling for 5 seconds, but no actual spellcasting or damage to the enemy happened. Combat log didn't show that the spell was casted at all, too. I've noticed it after getting Arcane Missiles VIII from AQ20 raid, because started to use the spell slightly more often.

Some other mage players have confirmed that they've faced this bug, too.

Update:
The problem with the Arcane Missiles spell proves to be critical - after intense testing on monsters, it seems that the spell fails to work as intended more than 50% of the time.

It either leaves your character standing channeling for 5 seconds (with mana spent already on that spell) while no cast/damage actually happens - as described in the previous message - or it casts three "waves" of Arcane Missiles (out of normal five "waves") with the remaining two "waves" not happening (character just stands channeling for 2 more seconds, or so).  Monster suffers three "waves" of damage and remains alive because the last two waves don't show up at all. Combat log shows exactly the same (no spellcasting/damage at all in the first case, and only three "waves" of damage to monster in the second case).

Having one of the important spells (the one of the only two damage spells of Arcane school for mages, and the one very useful in PvP) not working is really discouraging. Please look into this issue!

Another update:
After a few more attempts/tests - I couldn't have Arcane Missiles spell to work normally even once.

**Comment by Thenari** [comment]
#742 i remember there was some work done on arcane missiles after this bug. But be a connection

**Comment by ShunnieMage** [comment]
Well, I must say that "now it's "official" - Arcane Missiles spell literally doesn't work (almost). Just tried casting it 5 times in a row at enemy in BG (Warsong) right now. 5 times I was just standing and "channeling" it without any effect. It's just a waste of mana and 5 seconds of time/mobility at the moment.
Also, I didn't cast it that much in previous days (my character was merged to Nighthaven), but I am pretty sure I would noticed that the spell is non-functional at all. To my view, it started after I've got AQ20 Arcane Missiles VIII. However, using the lower rank (7) of the spell didn't really change anything.

**Comment by Thenari** [comment]
I am in the middle of moving and have no computer access but i am gonna confirm and high priority this and push it to the bug testing discord for a dev to look at it

**Comment by ShunnieMage** [comment]
Thanks a lot! :)

**Comment by ShunnieMage** [comment]
Hello again! Any progress regarding this?

It seems that the bug is happening less often, but it still happens a lot - and when it does, it usually is several times in a row. Just now I was in Warsong Gulch trying to damage an opponent (who was busy attacking other players) with Arcane Missiles spell. I've attempted to cast the spell three times, and three times I was standing channeling it with zero effect. So, 15 seconds of nothing for a huge mana expense.

Please, do something about it!

**Comment by Shette** [comment]
check it after next update, should work properly

**Comment by Thenari** [comment]
it may* have a visual bug but mechanically it should be working fine now.
