### ISSUE TITLE
Frost damage from Icicle Rod doesn't increase Blizzard damage

### ISSUE THREAD

**Issue by WobLight** [elysium-project/classic-bug-tracker#874]
Equipping [Icicle Rod](https://classicdb.ch/?item=2950) doesn't have any effect on Blizzard. It could be that the damage increase is too low but I can't verify that.

**Comment by Thenari** [comment]
@WobLight youre normally pretty good at this just double checking.

Blizzard is a what 1/3 spell scaling per second for 8 seconds  right?  https://wow.gamepedia.com/Blizzard says 394% idk that should be high enough scaling to see a +10 spell power...

Is it working on other spells? I am mid move i dont have a computer set up yet so ill ask either you or another playtester to do basic frost spells with nothing but the rod and confirm if its the rod thats giving no frost power. It would be very strange if it was only the one blizzard spell it should be using math like a funnel first adding all frost power into 1 unit of X then doing base dmg +X/spell scaling

**Comment by WobLight** [comment]
I works for frost nova and others, even if it's not enough to increase damage steadily, it should still get dithered afaik (sometimes dealing X and sometimes X+1) but that's not happening. Quickest way to test it would be to try with some greater amount of frost damage addition.

**Comment by Thenari** [comment]
That link is wow.gamepedia my bad thats probs the newest patch

https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/2188-how-spell-damage-calculated-mages.html some sort of old forum post with numbers

**Comment by WobLight** [comment]
10/3/8=0,42 so it's not enough to have a stead increase in damage, it could either be that the damage is not added or not dithered. I did some work on dithering back when elysium was open source, but I don't recall what the status on the matter was.

**Comment by Thenari** [comment]
![screenshot_20180905-085743_chrome](https://user-images.githubusercontent.com/38762769/45094564-b24c1800-b0e9-11e8-9a54-e9a27e6bcf4e.jpg)

**Comment by Thenari** [comment]
This guy references somethinf called Danyas formula it has to do with the lower level you got the spell the less efficient spell power is

**Comment by Thenari** [comment]
I know my fire lock when using Hellfire its about 14% of my fire power per tick for 15 seconds but mages scale better with spell power.

**Comment by Thenari** [comment]
Also let me know if this is wrong, do +X spell power ever have hidden or rounded decimals? Whats the significant figure for math here. If something is below 0.5 is it just lost?

**Comment by Thenari** [comment]
It could even be a client side visual. So just pull the combat log out of your chat client and stretch it big. Make sure you have addons disabled and using nothing but the staff blizzard a friend in a duel (ask friend to get naked too just in case) screenshot the combat log with your character sheet open so we can see the rod. Then do it again without the rod.

**Comment by WobLight** [comment]
![immagine](https://user-images.githubusercontent.com/26815207/45097164-74b7b100-b122-11e8-8258-99143645f0ab.png)
this is what I can provide atm. Blizzard rank 1, 200 damage total (from tooltip) with the Rod.
It would be much safer to just test it on a local server with more spell damage to check whether is a rounding issue or damage not added at all.

**Comment by Thenari** [comment]
Probably :p but im at a train station so i call not it.

**Comment by Thenari** [comment]
I know this isnt your only toon :p give this lil mage some wizard oil. Wizard oil a high lvl toon can put on a twink in a trade same as those arcanums from DM. Just get a friend to oil up the rod ;)

**Comment by WobLight** [comment]
Reaching +31 frost damage effectively increase Blizzard's damage by 1, so it's a rounding issue (missing dithering). I guess that affects all spells.

**Comment by WobLight** [comment]
dither works like this: there's a chance equal to the decimal part of the number to be round up. E.g. 1.25 would have a 25% chance to be rounded to 2. I had some work started to implement that back when elysium was opensource, my work wasn't complete but I can upload it in my old fork if you wish.

**Comment by Thenari** [comment]
Neat i didnt know that! I actually dont super know who is best to talk to about code stuff but that sounds like something Shenna does maybe? If you got discord thats the easy way to contact them. I'll also throw down a link to your comment to the development discord.
