### ISSUE TITLE
Bloodvine Dissapeared

### ISSUE THREAD

**Issue by Aleksbaum** [elysium-project/classic-bug-tracker#875]
Hello.

So i bought 12xBloodvines on the AH for a lot of gold. I proceeded to store them in my bank, then suddently it bugged out... It said I had 2x4 bloodvines, and when i took them out it said i had 2x20... After trying to put them back in the bank and out again to make it say 12x like I originally had it just went down to 4x. 

Now i only have 4x Bloodvines, 8 less than i originally had. Which is going to cost me a lot of gold...

I will add some photos showing what was going on...

![uten navn](https://user-images.githubusercontent.com/43042141/45169879-d1889980-b1fe-11e8-9a64-7dd852755c65.png)
![bloodvine](https://user-images.githubusercontent.com/43042141/45169896-db120180-b1fe-11e8-8290-c6674506c72b.png)

**Comment by Thenari** [comment]
This is a personal issue and not a generic bug that affects other (Yet). It is very specific so if you do use discord the elysium channel has a support or help channel you can talk in. I am closing this issue as Development need not worry about this (yet! If more cases come up it will be an open ticket). It is not locked you can always comment in here and it can be reopened whenever.

**Comment by Aleksbaum** [comment]
Yeah im still waiting after talking to the first GM.. Really sucks for me, grinded so long for that gold...

**Comment by Thenari** [comment]
Sorry bud. Just doing the standard questions though.

Disable Addons and check again?

Might be a corruption in your item saved data files im pretty sure thats the WTF folder not the WDB one so maybe delete the WTF folder and close the client and relaunch. Itll see youre missing your WTF file and give you a brand new one.

Uhhh theres more info on the help/support discords this isnt my area :p

**Comment by Thenari** [comment]
I think its rude to give out other peoples discords or usernames. Kinda like giving strangers your friends phone numbers. So just dont post any personal info here plz

**Comment by Aleksbaum** [comment]
Ill try those things. The first GM told me to delete my WDB one. Ill try with WTF.

**Comment by Aleksbaum** [comment]
Didnt work. Its so wierd... Really hope a GM can help me further, this just sucks so hard..

**Comment by Thenari** [comment]
Err onw of those folders is like your macros and stuff sorry if you deleted those

**Comment by Aleksbaum** [comment]
So what do I do now? Im not getting any help from the GM's and dont understand who to maybe contact @discord... This sucks so bad... just randomly losing 150g

**Comment by Thenari** [comment]
There should be an item recovery process let me look it up

**Comment by Aleksbaum** [comment]
Any news?
