### ISSUE TITLE
Character Auction

### ISSUE THREAD

**Issue by ohlordyitskek** [elysium-project/classic-bug-tracker#877]
Recently purchased toon has it's stats, mailing system, and inventory bugged. Stats for gear are all red and don't adjust after unequip/reequip. Successful auctions were not retrieved and put in mailbox. All items say Made by Charactername. Deleted WDB folder. Disabled addons. Nothing 😞

**Comment by Thenari** [comment]
Maybe a clean install of the client? Sounds like a visual client side to me. But you bought a character from the website right?

**Comment by ohlordyitskek** [comment]
yeah. sweet deal too.

**Comment by Thenari** [comment]
Mechanically is it as if you have no gear?

Or is it all visual?

**Comment by ohlordyitskek** [comment]
It was a big ol mess. Stats were bugged, damage output etc. Don't know how or why. But you know Rain, He came along and saved the day. My hero <3

**Comment by Thenari** [comment]
Alright so ill close this. You can always comment here and it can be reopened in the future.
