### ISSUE TITLE
[Wanted!  Otto and Falconcrest] Elites respawn is buggy.

### ISSUE THREAD

**Issue by WobLight** [elysium-project/classic-bug-tracker#878]
Hello, Falconcrest and another non-quest elite next to him respawn very quickly (I'd say less than 10sec). The corpses also disappears on respawn, which likely cause wipe and no loots.
1st try:
We casted CC on Otto and Falconcrest and killed both casters beside him, but a caster respawned almost instantly. We worked around that keeping it in CC, killed Otto then Falconcrest killed us.
2nd try:
We CCed Falconcrest, Otto and the buggy mage, killed the other mage, then otto and than Falconcrest. One of us died so we were waiting to loot for him to come back, but Falconcrest respwned in no time and wiped us again.

**Comment by Thenari** [comment]
#873 it was just messed with.
