### ISSUE TITLE
Undead Mage Level 1 to Level 2 Discrepancy? 

### ISSUE THREAD

**Issue by TheAngryCanadian** [elysium-project/classic-bug-tracker#879]
I tested my theory [*PLEASE STATE THEORY*] with 2 undead mages yesterday, when lv 1 start pools are 61/225, and lv 2 pools are 67/220. The spirit gain and HP gain are as what the level up says it is, but the INT and Mana gains are not. 

Leveling to 2, reduces the INT value by 5, subsequently having me lose 75 mana points. 
![level 1](https://user-images.githubusercontent.com/43192171/45441875-94e4f400-b67d-11e8-87e1-a5a3379ff504.jpg)

![level 2](https://user-images.githubusercontent.com/43192171/45441883-9f06f280-b67d-11e8-95eb-9cfbe2b1b32a.jpg)

If this is a known issue, as I did not see it in existing ones, then just close it and let me know. 

Thanks alot.

**Comment by Thenari** [comment]
Do you have an idea on what it should be? Archived tables? Big spreadsheets? Idk anything about this. What is a start pool 61/225 67/220 mean?
