### ISSUE TITLE
Quest bug "Satyr Slaying!"

### ISSUE THREAD

**Issue by Doramus** [elysium-project/classic-bug-tracker#880]
Hey,

so in Ashenvale, the quest "Satyr Slaying!" is bugged. Upon completion the quest awards 30 silver and 199 xp. According to the wiki, the quest should award 2550 xp at lvl 26.
   I completed the quest at lvl 31, when it was still 'yellow'. It was most dissapointing.

xoxo to you, staff

**Comment by RainElysium** [comment]
Hi there! The quest EXP is indeed wrong, but not near that amount.
Please see here:
http://web.archive.org/web/20060525003949/http://wow.allakhazam.com:80/db/quest.html?wquest=1032

There are varying EXP amounts but we go by the original vanilla experience. Many of these websites are not accurate.

That being said I've fixed the EXP for this quest and set it to 260. Thanks!
