### ISSUE TITLE
A Strange Red Key

### ISSUE THREAD

**Issue by dab2110** [elysium-project/classic-bug-tracker#881]
Quest "A Strange Red Key" obtained from item "Blood Red Key" should be turned in to "Captured Arko'narin" (classicdb.ch/?npc=11016) in a cage in the Shadow Hold cave in Felwood. Followup quest "Rescue From Jaedenar" is an escort, during which "Captured Arko'narin" gets her armor back, and becomes "Arko'narin" (http://classicdb.ch/?npc=11018).

When I found the Key and started the quest, the latter NPC ("Arko'narin" (http://classicdb.ch/?npc=11018)) was in in the cage. This NPC won't accept turn in from the Key quest. You can open the cage she is in, but you can't turn in the quest.

I tried re-logging, abandoning and restarting, etc.

**Comment by Thenari** [comment]
Just looked it up. The quest rewards suck lol.
