### ISSUE TITLE
Unable to find "Formula: Enchant 2H Weapon - Agility"

### ISSUE THREAD

**Issue by Rapkica** [elysium-project/classic-bug-tracker#883]
Every list i checked it says that i need to be friendly with Timbermaw Hold to be able to buy this formula in game. My addon confirms me the same thing.. I am already half way being revered with these guys and i havent seen this item in game. I have checked multiple times timbermaw vendor just to be clear that im not blind nor stupid.. its not there :) can you fix this issue!?!

**Comment by Thenari** [comment]
Lol. The first list you should check is what patch an item.is available. That recipe is 1.10
