### ISSUE TITLE
Corrupted Redpath Not spawning : The Battle of Darrowshire

### ISSUE THREAD

**Issue by jcap1142** [elysium-project/classic-bug-tracker#884]
Attempted to do quest "The battle of Darrowshire" and the NPC named "Redpath the Corrupted" did not spawn after 15 min time in the event.

**Comment by jcap1142** [comment]
It starts by placing the Relic Bundle https://classicdb.ch/?item=15209 in the Darrowshire Square. Its then followed by waves of undead NPC's and then

Prevent Davil Lightfire's death until the death of Horgus.

Prevent Captain Redpath's death until Redpath the Corrupted appears.

Defeat Redpath the Corrupted.

Speak with the spirit of Joseph Redpath when he appears at the town square, then speak with Pamela at her home.

Redpath did spawn and was killed by the NPC that was meant to kill him. Then it was just endless waves of NPC and never Redpath the Corrupted.

Hope this helps.
Thanks!

**Comment by ZicoQA** [comment]
Quest worked find for me on Live. Please try to clean your WBD folders
