### ISSUE TITLE
Dreadsteed of xoroth

### ISSUE THREAD

**Issue by LIlpugsley** [elysium-project/classic-bug-tracker#885]
I was running DM W for my epic mount. Everything was going accordingly but for some reason after the dreadsteed of xoroth was slain I did not get credit for it. I have witnesses and a screenshot that clearly shows the dead dreadsteed of xoroth but I was not able to complete the quest.
![screenshot 12](https://user-images.githubusercontent.com/43336890/45615269-e1835300-ba20-11e8-84d2-0d7b7324f649.png)
![screenshot 10](https://user-images.githubusercontent.com/43336890/45615278-e942f780-ba20-11e8-9e2e-1126dfb2a0f7.png)
![screenshot 11](https://user-images.githubusercontent.com/43336890/45615287-f06a0580-ba20-11e8-86d1-abb5e7119078.png)
![Uploading Screenshot (7).png…]()

**Comment by Thenari** [comment]
Arent you supposed to enslave it not kill it lol

**Comment by Thenari** [comment]
Im pretty sure when i did the quest it didnt consume the mats just a bunch of soul shards. It sucks man but if something went wonky and no one was there to record the wonk we almost always cant do anything :p 

Get some friends and do it again :D  (maybe make sure you got an ingame gm witness)

Also there are a number of ways the quest can fail make sure to keep that ritual up

**Comment by Thenari** [comment]
https://classicdb.ch/?npc=14506

Second chance at the loot too :p

**Comment by Thenari** [comment]
ahah damn i just realised youre th lilpugsley we get reports in for dishonourable camping in tarren mills and xroads :P it's a small server don't grief lowbies our only thing keeping this server alive is lowbies being able to level and renew our supply of players. try and limit yourself to 3 corpse camps per person kthxbye

**Comment by swansoon** [comment]
Having similar situation as Lllpugsley, but we didn't see the spirit of the dreadsteed after the fight. It simply disappeared. Quest is done, but where to finish? There were two warlocks in the group, both of us had the quest, but faced the same issue with the disappearing dreadsteed spirit. 
We tried to reopen the gate and repeat the fight but didnt work. 
Shall we drop the quest and do it again?
![wowscrnshot_122918_141144](https://user-images.githubusercontent.com/46186683/50540786-abfe1200-0b98-11e9-9d8c-0976b3d2dccd.png)

**Comment by swansoon** [comment]
Update: 
I dropped the quest and take it up again next day, made a second run in Dire Maul west. Fortunately everything went well, I didn't wait till the end of the fight, when appeared I spoke with the spirit of Dreadsteed, and finish the quest, got the mount without any problem.
