### ISSUE TITLE
Bought character is horde. But has properties of being alliance. (No orgrimmar buffs, av mines)

### ISSUE THREAD

**Issue by Kenjai** [elysium-project/classic-bug-tracker#887]
Hello, my alt, Blowit, mage on Elysium - Nighthaven realm patch 1.9 is being hurt by friendly faction land mines in Alterac Valley. Please be aware that this char was purchased from the store.

Thank you.

**Comment by Thenari** [comment]
I dont have access to a bought toon from the store. So if you are willinging to just confirm it is happening that speeds things up. Message a GM ingame to witness next time you apply to get into AV. Or if your computer can take a video. Screenshots are fine too for this.

This is not blizz like to be able to buy toons in vanilla so there are no easy tools to fix this. Thanks for letting us know.

**Comment by Kenjai** [comment]
Alright. I will come back with proof :)

**Comment by Kenjai** [comment]
![wowscrnshot_092018_125522](https://user-images.githubusercontent.com/43410418/45811091-dc4e2e80-bcd4-11e8-880b-69cf4d7df22a.jpg)
![wowscrnshot_092018_125525](https://user-images.githubusercontent.com/43410418/45811092-dc4e2e80-bcd4-11e8-9da8-5bf3754a6be2.jpg)
![wowscrnshot_092018_125532](https://user-images.githubusercontent.com/43410418/45811093-dce6c500-bcd4-11e8-9141-d78cad2b2c4b.jpg)


Proof .

**Comment by Kenjai** [comment]
up!

**Comment by Thenari** [comment]
And normally the mines do no damage to your own faction? Kinda uncharacteristic of landmines to discriminate who they blow up.

**Comment by Thenari** [comment]
Ha weird

**Comment by Thenari** [comment]
Can you check if the ally mines in AV affect you.

**Comment by Kenjai** [comment]
I am affected by ally mines too....

**Comment by Thenari** [comment]
There might be some sensitive account info i dont want you to be typing out here. 

To get a confirmation of account can you put in a in game ticket and link the url to this github. You need a higher up GM as this is a store bought error. Ill let someone with more power know about this
