### ISSUE TITLE
Suntara Stones 

### ISSUE THREAD

**Issue by Sloppyboi** [elysium-project/classic-bug-tracker#888]
Suntara Stones in Searing Gorge isn't working. After you finish the escort quest, the item appears but it doesn't work to give you the quest.  I try to interact with the object, but the cog wheel doesn't show up to do so.

**Comment by Thenari** [comment]
Suntara stones is the name of then second part of a 5 piece quest chain.

Please describe the steps you have taken so far.

**Comment by Thenari** [comment]
Ahh its the name of the first quest too.

**Comment by Thenari** [comment]
Some suggest the letter you need is there the whole time. After the escort is shot you should get a quest update that lets you talk to the letter.

Blizzard vanilla escort quests are a garbage fire.

If it bugged you its best for you to drop the quest and try again.

**Comment by Thenari** [comment]
Wow and the rewards for the quest are garabge too. I guess of you need IronForge rep you could do this.

**Comment by Vasquez-QA** [comment]
Greetings,

Quest is working at intended, unable to replicate the issue reported (see below)

![escort q searing gorge](https://user-images.githubusercontent.com/2932176/46911809-7fa20480-cf5e-11e8-90f7-3079b0d9160b.PNG)
![escort q searing gorge 2](https://user-images.githubusercontent.com/2932176/46911810-829cf500-cf5e-11e8-8c1c-8e4911f30030.PNG)

Try to abandon and re-take the quest. If you still have an issue open a ticket in game.

Closing Report.

KR.
Vasquez
