### ISSUE TITLE
[Nighthaven PvP: 1.9] Tome of conjured food rank 7 isnt in game 

### ISSUE THREAD

**Issue by Tercoil** [elysium-project/classic-bug-tracker#889]
[Tome of conjure food VII ](https://classicdb.ch/?item=22897)not in game but according to https://wow.gamepedia.com/Tome_of_Conjure_Food and http://wowwiki.wikia.com/wiki/Tome_of_Conjure_Food it was added in Patch 1.9

**Comment by pl4ything** [comment]
>  Patch 1.11.0 (2006-06-20): Introduced Rank 7 as a Tome drop.
https://wow.gamepedia.com/Conjure_Food

> [Conjure Food] now has a new rank (Rank 7) available in Stratholme.
https://wow.gamepedia.com/Patch_1.11.0
