### ISSUE TITLE
Spirit of Eskhandar bugged

### ISSUE THREAD

**Issue by comus777** [elysium-project/classic-bug-tracker#891]
the Eskhandar mob spawned from the Spirit of Eskhandar set has 8hp and hits for extremely low amounts of dmg. based off of wowhead comments it seems that it's because eskhandar is designed to scale with the user's level, and it seems that the level scaling may be bugged on this server.

**Comment by Thenari** [comment]
Its weird that it scales with level. All the items for the 4 piece req lvl 60.

**Comment by Thenari** [comment]
A lot of future patches confirm the item is a joke. The cat does scale with level but was incredibly weak during the time of original wow. Its only useful component is its armour shred.

If you have a source saying numbers it should be, let us know.

**Comment by comus777** [comment]
Some stuff that points towards this
http://classicdb.ch/?npc=14306
the classicdb page lists Eskhandar as a level 1 npc that only has 8 health. Clearly eskhandar is not level 1 so this implies that there is some sort of level scaling going on. 
the comments from wowhead also show that eskhandar conforms to the user's level, and that he should be hitting for 100~ at lvl 60+, and according to one comment had 5k hp at lvl 80.

**Comment by Thenari** [comment]
The set gets a lot of work in future patches. Past 1.12.1 isnt valid for this current server
