### ISSUE TITLE
Quest:Scrying Goggles? No Problem! is not leting me take it after preQ done

### ISSUE THREAD

**Issue by Paparia** [elysium-project/classic-bug-tracker#893]
Nighthaven PvP

after delivering Quest:Scrying Goggles? No Problem!8577

the Inconspicuous Crate become uniteractable the moment i cliked accept on the follow up 
Quest:Scrying Goggles? No Problem!8577

i got messege that i am not eligible 

Thats is a raid quest

**Comment by Thenari** [comment]
Is your rep with the brood of N at least neutral?

**Comment by Thenari** [comment]
If that wasnt the issue let us know.

**Comment by Paparia** [comment]
yes my reputation was neutral

and i was ofered the quest but the accept button just closed it without giving me the quest


________________________________
