### ISSUE TITLE
Quest 8736 [The Nightmare Manifests] NPCs not spawning with script

### ISSUE THREAD

**Issue by RainElysium** [elysium-project/classic-bug-tracker#895]
**Intended Behaviour:**

During quest event, Nighthaven Defenders (GUID 15495) should spawn to defend the raid against waves of Nightmare Phantasm (GUID 15629) that spawn throughout Nighthaven. Tyrande (GUID 15633) should also spawn and cast healing spells upon the raid, and Remulos.

**Current Bugged Behavior:**
- NPC Nighthaven Defender does not spawn during scripted fight, at all. (Exact locations of spawns unknown. Likely in the main fight area, and then 2 for each of the spawn points of the Phanatasms to simulate a battle)
- NPC Tyrande does not use spells to heal raid or Remulos.
- NPC Remulos is not healable by raid.
- Announcement detailed below should be server wide, but is not.

**Sources:**

NPC Nighthaven Defender & Tyrande can be seen here: https://www.youtube.com/watch?v=OH4W234BPfs

Information on fight can be found here: https://classicdb.ch/?quest=8736

> Shades are evading and reseting a lot, which is anyoing, but allows you to eat/drink if you are getting overruned. You can heal Remulus, in case he's taking to much damage (tho, he was healing himself alot).
> 
> Shades are doing Shadowbolt Volley for 500 damage, and Fear lasting 2 seconds. Both are resisted heavily, becouse of level adventage (lvl62 vs 70).
> 
> Eranikus, from what I've seen, had 3 abilities. A stacking Acid Breath (150 every 3 sec per stack, or something like that) and Noxious Breath, which increase cooldown of your abilities by 10 seconds (lasts 30), so watch your threat ;). Also does Shadowbolt Volley (30-40 yard range) for 1,5k damage.
> 
> He hits for around 800-1200 damage, with 2-2,5 sec swing.
> 
> At around 50% (or was it time based?) Tyrande and her Priestesses comes to help. Tyrande (i think) casts Moonfire, that does pathetic damage, and Mass Healing - 4,5k HP every 2 seconds, for 12 seconds.
> 
> At 20% he's redeemed, and appears (server wide?) warning: "Eranikus, Tyrant of the Dream, is wholly consumed by the Light of Elune. Tranquility sets in over the Moonglade"
> 
> After small talk with Tyrande, everyone get's credit (when taking quest, you get a pop up like with Escort quests, so you can have multiple people doing it).

**Comment by Bubbles9001** [comment]
Also the spawn rate of shades are wrong. After each failed attempt the spawn rate doubles. I have video evidence if needed ?

**Comment by Bubbles9001** [comment]
Tyrande also ran into the fight dragging about 20 shades with her wiping the raid

**Comment by jcap1142** [comment]
*At around 50% (or was it time based?) Tyrande and her Priestesses comes to help. Tyrande (i think) casts Moonfire, that does pathetic damage, and Mass Healing - 4,5k HP every 2 seconds, for 12 seconds.*

We have video evidence from multiple characters that this did not occur. Had this occurred the quest would have been completed, without a doubt.

**Comment by Bubbles9001** [comment]
Also on the video our wipes we had 4x-8x  the number of shades up then what was going on in the video posted above

**Comment by Bubbles9001** [comment]
https://www.twitch.tv/videos/316397167

**Comment by jcap1142** [comment]
https://youtu.be/ki164-o94Ls

another view of the event

**Comment by Bubbles9001** [comment]
> _At around 50% (or was it time based?) Tyrande and her Priestesses comes to help. Tyrande (i think) casts Moonfire, that does pathetic damage, and Mass Healing - 4,5k HP every 2 seconds, for 12 seconds._
> 
> We have video evidence from multiple characters that this did not occur. Had this occurred the quest would have been completed, without a doubt.
Yeah if the event was working properly i could follow what the GM that told me to do. And do the quest to get the reward I can bring screen shots of that too

**Comment by Vasquez-QA** [comment]
Changes have been made on the PTR. Waiting to be patched to live.
