### ISSUE TITLE
[BUG] Improved drain soul warlock

### ISSUE THREAD

**Issue by douryx** [elysium-project/classic-bug-tracker#898]
Hi,

Warlock talents Improved drail soul (2/2) doesn't work as well.
It is write 100% chance to improved mana regen, but the effect proc less than 1 minion /5 killed with drain soul activated

**Comment by Thenari** [comment]
#58 #817 

Its confusing.

You need to do the kill. No pet no party no nothing.

**Comment by ixidion** [comment]
It's definitely not working. Tried many times, without Pet, without any Dots at all. Server is Nethergarde.

**Comment by ixidion** [comment]
> It's definitely not working. Tried many times, without Pet, without any Dots at all. Server is Nethergarde.
After relogging it's now working. Very strange.
