### ISSUE TITLE
Tiger's Fury and Zandalarian Hero Medallion don't stack

### ISSUE THREAD

**Issue by Rorau** [elysium-project/classic-bug-tracker#899]
In catform, the ability Tiger's Fury (rank 4) (increases damage done by 40 for 6 sec) does not stack with the trinket buff from Zandalarian Hero Medallion (Use: Increases your melee and ranged damage by 40 for 20 sec. **Every time you hit a target, this bonus is reduced by 2**.)

It looks like the game treats it as a re-application of the same buff but just with different names. Which must be a bug, because the trinket buff decreases in damage with every hit, while Tiger's Fury remains constant for it's 6 second duration. 
The trinket buff is called Restless Strength, while Tiger's Fury buff is just Tiger's Fury. 

I have tested it both by simply looking at my character sheet damage. It goes from 162-189 to 206-233 when using Tiger's Fury (rank 4), and also from 162-189 to 206-233 when using the trinket, and while farming on various npc's. So separately each ability works, but they don't stack. Presumably my character sheet damage should increase from 162-233 to 246-273 if both are used simultaneously. 

I have been unable to find any kind of information that says they shouldn't stack (and in fact I can only find posts on the subject on this server's forums complaining about it) and it doesn't make sense that they wouldn't stack, since Tiger's Fury stacks will all other kinds of on-use damage, and attack-power increasing trinkets, buffs and abilities.

**Comment by Thenari** [comment]
Do firewater and frostmaul juju stack?

**Comment by Thenari** [comment]
Ive never really played a  AP user let me look up some history on it.

**Comment by Rorau** [comment]
> Do firewater and frostmaul juju stack?
Not that I'm aware, but they're both consumables and there's many consumables that don't stack so I guess for consumables that is to be expected. 

But this is a catform ability and an on-use trinket buff, which work for so many other things it's weird why this one wouldn't.

**Comment by Thenari** [comment]
Yeah thats true. They have different spell IDs. Theres a few wonky overlaps that are intended to not work. The github is primarily for fixing things that arent working. If this is blizz-like and how its supposed to work idk if we can change it. I know the hero charm for casters also puts a bunch of other non trinkets on cd.

If someone can prove this is not intended we can look into it.

**Comment by ZicoQA** [comment]
This has been tested on live and is working.
