### ISSUE TITLE
Tactical Mastery

### ISSUE THREAD

**Issue by Manuvaa** [elysium-project/classic-bug-tracker#900]
So as of today, even tho im 5/5 in Tactical Mastery which i supposed to let u keep up to 25 rage points when u change stance. Well in my case i go to 0. idk it worked like 1 hour ago. Havnt tried respeccing yet, since im sitting in AQ right now
Cheers Manuva

**Comment by Thenari** [comment]
Hmm i was just playing with a warrior last night and it was working for him... do you have a specific situation you were in that it didnt work?
