### ISSUE TITLE
Giant Eye Tentacles on c'thun are able to melee their targets for 11k?

### ISSUE THREAD

**Issue by comus777** [elysium-project/classic-bug-tracker#901]
I got melee'd by a giant eye tentacle on the c'thun fight for 11k dmg, oneshotting me. Not sure if this is intentional or a bug, but it definitely does not seem correct.

**Comment by comus777** [comment]
https://legacyplayers.com/Raids/Viewer/?id=22964&exp=0
log of the cthun kill

the player in question here is baldrogue

**Comment by Thenari** [comment]
Hello this is a raid based one which are pretty hard to test solo but I'll see what i can find

**Comment by Thenari** [comment]
https://classicdb.ch/?npc=15334 this duder right? Ive never been to aq40 :3

**Comment by comus777** [comment]
Yep, that's the one. I don't believe they or their small counterparts should be able to melee their targets at all, much less for 11k dmg.

**Comment by comus777** [comment]
On the topic of the cthun fight, I notice that the small eye tentacles are listed as (??) Boss level mobs on this server, when they should be 60 non-elites according to all the guide videos and kill videos from live and other private servers that I've seen. Not that big of a deal but being (??) level does affect glancing blows/spell resist rates. which makes them very slightly harder to kill than they should be.

**Comment by ZicoQA** [comment]
Was for 1 hour fighting cthun alone, and there was no crits for giant eye bigger than 3k. He melee me for 1k-2k and this is as intended. I will relate the issue of the small eyes, however this didnt look like it affected much of me hitting them.
