### ISSUE TITLE
The Stones That Bind Us (Blasted Lands Quest) [Nighthaven]

### ISSUE THREAD

**Issue by cruzach** [elysium-project/classic-bug-tracker#902]
The servants you are supposed to kill for this quest are, as it seems, un-killable. Even after attacking the nearby stone, they remain invulnerable. I was told in general chat to open a ticket, and after doing so received a letter in-game to submit a ticket to the github. I know there are similar posts to this that are closed but the issue is still persisting. Thanks!

**Comment by Thenari** [comment]
This is a duplicate but the github system auto closes older versions. Its best to just do ingame ticket to reset the stones as they bug out.

**Comment by Thenari** [comment]
#565 #771 #784  #852

**Comment by aromero7578** [comment]
Can we please reopen this? I'm having the same issue, the quest does not work.

**Comment by ZicoQA** [comment]
This quest was working for me as long as you kill the mobs close to the stone
