### ISSUE TITLE
Druid Talent: Omen of Clarity

### ISSUE THREAD

**Issue by Lowekee** [elysium-project/classic-bug-tracker#904]
The druid talent Omen of Clarity is malfunctioning, in 2 different manners, as i experienced it.

When the clearcast procs at near 0 energy, it does NOT alow for a rake ability to be cast (35 energy cost).
This is the first manner.

**The second manner, and more obvious one, is this:
When the clearcast procs, and i cast ferocious bite, it drains the energy  cost of ferocious bite (40 energy).** (**Thenari Confirms below**)

This is all the info i can provide. Had this happen to me on multiple occasions, on the feralas Elite Giants on the shore.

**Comment by Thenari** [comment]
Im at home and have minor PTR powers now so i can test this :)

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/46842617-9b5dad00-cd9c-11e8-9a1d-88480c36e6ae.png)
 hitting my 1 key constantly to see the out of energy

**Comment by Thenari** [comment]
i was pretty sure i was able to cast it when out of energy because of clearcasting but not sure how often that happens, had my finger over printscreen the whole time

**Comment by Thenari** [comment]
the ferocious bite though does take energy looked like just the 35 of the cast fee, but also FB will use all your energy available to do more dmg per point, it must be confused somehow

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/46842717-3191d300-cd9d-11e8-8613-8442b399c842.png)

nope it took all the energy!

got 1 combo point then just basiced at full energy- clearcasting consumed- no energy

**Comment by Thenari** [comment]
pretty sure FB is 35 energy, rake is 40. just to be sure we are talking same things, sometimes theres more going on idk about. like other talents.

the above tests are with only 5 in wrath and 5 in natural weapons and 1 in omen

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/46843048-f7c1cc00-cd9e-11e8-8721-d4421eba1ed0.png)

**Comment by Thenari** [comment]
checked with ferocity in case it was a minus -100% energy -5energy that was confusing the system but i was able to use a free rake at 20 energy

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/46843198-a8c86680-cd9f-11e8-9186-5afb0fb2389c.png)

double check with new talents

**Comment by Thenari** [comment]
@Lowekee can you tell me your talents and what rank of Rake you are using, I gotta go to bed but it could be a specific rank is bugged. I'll test more when i have info
