### ISSUE TITLE
C'thun Fight Giant Claw Tentacle BUG

### ISSUE THREAD

**Issue by nastyxx** [elysium-project/classic-bug-tracker#905]
we are talking about the giant claw tentacle at C'thun.
https://www.wowhead.com/npc=15728/giant-claw-tentacle
Wowhead
Giant Claw Tentacle
Giant Claw Tentacle is a level 60 Elite NPC that can be found in Temple of Ahn'Qiraj. The location of this NPC is unknown. In the NPCs category.

this is retail, but its the attacks he is doing
and he is doing this on nighthaven aswell
everything fine until now
so the Thrash ability is :They have a Thrash ability (two extra attacks), meaning they will one-shot anyone who doesn't have a very high armor rating.
meaning it is oneshotting non-tanks with that ability if u get aggro from the main tank.
now to the bug.
if a tank gets on the tentacle that spawns. and is tanking it. he gets the normal stuff. harmstring. auto attacks. and if a second tank for example overaggroes the maintank he will get this Thrash ability aswell. even tho he has "high Armor"
so the bug is. he uses this thrash ability on everyone that gets aggro after the first tank
I can give u video evidence for it aswell.
we thought for a long time, that stunning the mob is doing this bug. but I watched the VOD from yesterday probably 20 times looked up logs from legay players. noone stunned that thing. and then I found the thrash ability meaning. its common on different bosses for example in BWL and there its working normally like it should. but on these Claws its completly off.
https://streamable.com/7iwai

the clip to it
u see the first tank going on it and he is going after
getting aggro at some point and get devastated
and we thought its happening because someone is stunning it. but actually noone stunned the add. its 100% because of that. the Thrash ability isnt working like it should

**Comment by RainElysium** [comment]
"so the bug is. he uses this thrash ability on everyone that gets aggro after the first tank"

**Comment by Rorau** [comment]
It doesn't seem bugged to me. The tentacle does thrash on whoever happens to have aggro and is in melee range. Tanks apparently just have to eat their greater stoneshield potions, possibly use shield wall, and hope healers are ready to spam them with colossal heals.

**Comment by nastyxx** [comment]
> It doesn't seem bugged to me. The tentacle does thrash on whoever happens to have aggro and is in melee range. Tanks apparently just have to eat their greater stoneshield potions, possibly use shield wall, and hope healers are ready to spam them with colossal heals.

you should read how the Trash-Ability works. and I can tell u. not like this :)

**Comment by Rorau** [comment]
Okay, where do I read about it?

**Comment by ZicoQA** [comment]
http://wowwiki.wikia.com/wiki/Thrash

For me it looks like its working as intented
