### ISSUE TITLE
The Stones That Bind Us is broken

### ISSUE THREAD

**Issue by Kekadin** [elysium-project/classic-bug-tracker#907]
Hello this is Skaza from Nighthaven PvP 1.9 patch.
I couldn't progress with the quest The Stones That Bind Us. This quest from the demon questchain in Blasted Lands is broken. After bringing servants to ~10%hp they go immune but then it goes wrong. One mob could spawn like 2 stones in 8-10 mins and destroying them woudn't cause any effect. So non quest mobs spawned 2 times when i was trying to 'free' the quest mob.
It can be easly checked by repeating the quest with any character.
Ultimately a GM called Theflame helped me out by instantly finishing the quest. Then he told me to report it here.
I hope it helps.
Cheers

**Comment by Thenari** [comment]
#565 #902 #784 #771 #852  and theres probs more

**Comment by Thenari** [comment]
In game ticket is best until a good fix works
