### ISSUE TITLE
Hive'Ashi Ambusher respawn time is extremely low

### ISSUE THREAD

**Issue by WobLight** [elysium-project/classic-bug-tracker#909]
Less than one minute, probably much lower.

**Comment by Thenari** [comment]
They rapidly spawning? Thats strange but kinda good for farming ;p i believe there should about 10 or so nodes surrounding the edges of the northern hive since last time i was there.

I know respawn timers are affected by mass amounts of local players.

**Comment by WobLight** [comment]
I've done some more research, looks like even on blizzard servers those respawn awfully fast, so the problem is likely just the way they're implemented, as their bodies disappears on respawn, you have to be fast to loot them for the quest before they're gone...

**Comment by Thenari** [comment]
Well good job, you figured it out :)
Thanks for reporting it now in case anyone else has the same idea
