### ISSUE TITLE
Venoxis Despawn

### ISSUE THREAD

**Issue by Yuecchi** [elysium-project/classic-bug-tracker#910]
We were clearing Zul Gurub and we were wiping on Venoxis. One of our hunters kited the boss across the nearby bridge to despawn the boss, however after doing this the boss did not respawn again.

Video Proof: [https://youtu.be/FP9mz8S9TFs](url)

**Comment by Vasquez-QA** [comment]
Now fixed on PTR - Ready to be patched to live.
