### ISSUE TITLE
Nighthaven PvP patch 1.10 - Wrath of Cenarius item

### ISSUE THREAD

**Issue by tutuma499** [elysium-project/classic-bug-tracker#914]
Patch 1.10 should have fixed the proc of Wrath of cenarius but it's still broken, Either it's way too low or it don't proc on some spells like Hellfire.

From 1.10 patch note : 
- Wrath of Cenarius will now trigger off all damaging spells.

thx,

**Comment by Thenari** [comment]
Teah a couple item changes are needed to be manually done. (Also hi tutuna :3)

**Comment by ZicoQA** [comment]
working as intended
