### ISSUE TITLE
Druid quest: A Better Ingredient

### ISSUE THREAD

**Issue by kegam** [elysium-project/classic-bug-tracker#917]
I have a problem with the above mentioned quest. I have completed it (quest log says complete) and I have the required item in my inventory. However for some reason I cannot turn in the quest. No question mark on the npc "Torwa Pathfinder". 
I had a conversation with a GM and he told me to report the issue here, because he could not solve the issues.

**Comment by RainElysium** [comment]
Hi there. Have you attempted deleting your WDB Folder, restarting WoW, and then disabling all addons?

**Comment by kegam** [comment]
Yeah I have, still not working

Sent from my iPhone

On 18 Oct 2018, at 23:49, RainElysium <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there. Have you attempted deleting your WDB Folder, restarting WoW, and then disabling all addons?

**Comment by Vasquez-QA** [comment]
Unable to replicate - Quest working as intended:

![image](https://user-images.githubusercontent.com/2932176/47532888-85c2aa00-d8a9-11e8-8fbc-bf51fa210af6.png)

If you are still having issues, open an in game ticket to have the quest completed for  you.

**Comment by Vasquez-QA** [comment]
Receiving multiple Reports of this quest, despite it appears to be working on PTR. Passing to Developers.
