### ISSUE TITLE
Job Opening: Guard Captain of Revantusk Village Bugged Quest

### ISSUE THREAD

**Issue by Oxidiy** [elysium-project/classic-bug-tracker#919]
Description of quest says to kill following mobs:
10 Berserker
5 Hunters
5 Blood Drinkers
5 Soul Eaters
![bug](https://user-images.githubusercontent.com/44255786/47137671-58359980-d2c8-11e8-9d88-8e271f5b8f8d.png)
I cant complete quest! It wont turn in!
Btw killing **80** elite mobs isnt an easy task :(

**Comment by Shettelight** [comment]
it`s just wrong description: https://www.wowhead.com/quest=7862/job-opening-guard-captain-of-revantusk-village
Should`ve 20 for each

**Comment by Vasquez-QA** [comment]
Greetings,

I have tested this quest and it is working as intended:

![image](https://user-images.githubusercontent.com/2932176/47533452-aab81c80-d8ab-11e8-9d3c-05c140f7ff8d.png)

Try deleting  your WDB Folder, restarting WoW, and then disabling all addons.

If you still have an issue, raise an in game ticket and we can auto complete the quest for you.

Vasquez

**Comment by ZicoQA** [comment]
I can confirm this has been tested and is working
