### ISSUE TITLE
[Dead Man's Plea] Strath 45 min.

### ISSUE THREAD

**Issue by Charlyy1** [elysium-project/classic-bug-tracker#920]
![ysida harmon](https://user-images.githubusercontent.com/44293254/47217306-3b709300-d3a8-11e8-99b3-52b18ada4534.png)

Baron Rivendare dead before 45 min and still cant complete quest.

**Comment by Shaplex** [comment]
I also experienced this issue with my group trying to complete Dead Man's Plea.  We had 14 minutes remaining when we killed Baron!  ..but we were unable to talk to Ysida Harmon. 

![baron dead in under 45](https://user-images.githubusercontent.com/40157795/47259309-ab008400-d475-11e8-86b7-9bef9a7f3f03.png)

**Comment by Vasquez-QA** [comment]
Now fixed on PTR - ready to be patched to live.
