### ISSUE TITLE
Engineering Bug: Ornate Spyglass

### ISSUE THREAD

**Issue by Magicteapota** [elysium-project/classic-bug-tracker#921]
Hello! There seems to be a bug with the Ornate Spyglass item from Engineering. It vanishes from your inventory after a few minutes time (or if you log out).

I tried making a couple myself (for the fun!) but when I relogged they had vanished completely with no trace. I decided to make another one and noticed in flight that the item simply vanished from my inventory. 

Is this something more people have noticed? Can it be fixed. I am quite fond of these fun little items.

**Comment by Vasquez-QA** [comment]
Hello!

Thank you for bringing this issue to our attention. 

Ornate Spyglass (GUID 5507) does vanish from inventory after a re-log.

Confirmed on PTR - Passing to developers,

**Comment by missye04** [comment]
I made 6 and all gone Y_Y

**Comment by ZicoQA** [comment]
fixed
