### ISSUE TITLE
Barkeep Kelly is not selling Rumsey Rum Black Label

### ISSUE THREAD

**Issue by GrenderG** [elysium-project/classic-bug-tracker#927]
[Barkeep Kelly](https://classicdb.ch/?npc=2366) should sell [Rumsey Rum Black Label](https://classicdb.ch/?item=21151) but currently he is not selling it.

**Comment by Thenari** [comment]
A quick followup 
![screenshot_20181027-113547_chrome](https://user-images.githubusercontent.com/38762769/47606033-56608a00-d9dc-11e8-85ab-7b360720f083.jpg)

Im assuming you are trusting classicdb for his sale window.

A lil thought suggests him selling infinite for cheap would be crazy.

Looks like the buff rum is added when he is in the cavern of times.


But if you have a source thats reliable let us know.

**Comment by GrenderG** [comment]
Nope, I based my issue in classicdb information. Seems like classicdb not only shows information about Vanilla WoW.
