### ISSUE TITLE
Tar Pits in Un'Goro aren't slowing you down.

### ISSUE THREAD

**Issue by GrenderG** [elysium-project/classic-bug-tracker#929]
These pools should be slowing down your run / swimming speed.

**Comment by Vasquez-QA** [comment]
Hello,

This behavior is intended, slowing debuff was added in Cata:

https://wow.gamepedia.com/Lakkari_Tar_Pits

Closing report.

**Comment by GrenderG** [comment]
Lol my memory failed, I thought this was the behavior since Vanilla. Thanks for pointing it out.

**Comment by Vasquez-QA** [comment]
No worries :)
