### ISSUE TITLE
Lesser Magic Wand doing too much damage

### ISSUE THREAD

**Issue by Varlun** [elysium-project/classic-bug-tracker#930]
I crafted myself a Lesser Magic Wand and it's supposed to be doing 6-11 damage but it's doing 18-22 on average, low hitting for 14 and critting for 28. I'm a level 13 Priest.

**Comment by Vasquez-QA** [comment]
Tooltip is correct, you will need to delete your WDB folder. When you log back in it should so correct stats.
Let me know how you get on.

**Comment by Varlun** [comment]
That fixed it. Not sure why it messed up I only made this character a few days ago. And it's also unfortunate because I sold like 7 wands I'd made that I could've disenchanted instead. Oh well, thanks.

**Comment by Vasquez-QA** [comment]
No worries and that's unfortunate but at least you know now!

I will close this report.
