### ISSUE TITLE
Cannot turn in quest "Hunting for Ectoplasm"

### ISSUE THREAD

**Issue by crackwood2** [elysium-project/classic-bug-tracker#933]
Hello

I gathered all items for quest "Hunting for Ectoplasm"

12x Scorched Ectoplasm
12x Frozen Ectoplasm
12x Stable Ectoplasm

All items are in my bag, with the Ectoplasmic Distiller

Questgiver (Max Manascrambler in Gadgetzan) still get a gray interrogation mark -- i cannot turn in the quest

Please if you can give it a look it would be appreciated

Thanks in advance!

My email: brisebois_david@hotmail.com

![hunting for ectoplasm](https://user-images.githubusercontent.com/44588740/47680592-9cb11700-db9d-11e8-87c1-1d90946af601.png)

**Comment by Vasquez-QA** [comment]
Hello,

It seems I cannot replicate the problem so it must be specific to your account / character.

Can I ask that you delete your wdb folder and disable all ad-dons and try again?

If  you still can't hand the quest in, can I ask that you log an in game ticket and explain that you have already reported the issue here.

Let me know the outcome

Thanks!

**Comment by crackwood2** [comment]
Hello


Sadly deleting the WDB folder and disabling all the addon did not solve the problem


I opened an in game ticket as you suggested


Thanks


________________________________
De : Vasquez <notifications@github.com>
Envoyé : 29 octobre 2018 17:49
À : elysium-project/classic-bug-tracker
Cc : crackwood2; Author
Objet : Re: [elysium-project/classic-bug-tracker] Cannot turn in quest "Hunting for Ectoplasm" (#933)


Hello,

It seems I cannot replicate the problem so it must be specific to your account / character.

Can I ask that you delete your wdb folder and disable all ad-dons and try again?

If you still can't hand the quest in, can I ask that you log an in game ticket and explain that you have already reported the issue here.

Let me know the outcome

Thanks!

**Comment by crackwood2** [comment]
I was able to make it work


- Put all Ectoplasm in bank

- Drop the quest (Even if saying it will delete the item -- heartbeats... )

- Items still in bank, YAY!

- Got quests back and was able to turnin


phew


________________________________
De : Vasquez <notifications@github.com>
Envoyé : 29 octobre 2018 17:49
À : elysium-project/classic-bug-tracker
Cc : crackwood2; Author
Objet : Re: [elysium-project/classic-bug-tracker] Cannot turn in quest "Hunting for Ectoplasm" (#933)


Hello,

It seems I cannot replicate the problem so it must be specific to your account / character.

Can I ask that you delete your wdb folder and disable all ad-dons and try again?

If you still can't hand the quest in, can I ask that you log an in game ticket and explain that you have already reported the issue here.

Let me know the outcome

Thanks!

**Comment by Vasquez-QA** [comment]
Excellent news!

Thanks for confirming - I will close this one off!

👍
