### ISSUE TITLE
Multiple bugs suddenly

### ISSUE THREAD

**Issue by Lowekee** [elysium-project/classic-bug-tracker#936]
Hello.

My main character, Lowekee, level 60 Alliance side NIght Elf Druid), is experiencing a few bugs that i encountered around an hour ago.

Upon login i'm getting some "you don't have any space in your bags" messages in my chat window
and in a red message in the middle of my screen.

My friendlist appears empty, (which it normally isn't).

Also when typing in a name in the mailbox, a macro style errror message appears on screen.

My alt does NOT experience any of these bugs.

I have tried deleting the WTF and WTB folders upon advice from Rain and Pl4ything. Didn't work.

I have tried disabling addons, moving the entire addon folder away from the directory, nothing has worked so far. I have tried logging out and in multiple times, also have tried exitting the game.

Sincerely,

**Comment by Lowekee** [comment]
FIXED.

**Comment by Vasquez-QA** [comment]
Hello Lowekee,

I'm glad to hear you resolved this issue, can I ask what you did to fix it out of interest?

I'll close the report.
