### ISSUE TITLE
Zap Farflinger BROKEN!

### ISSUE THREAD

**Issue by vucoo** [elysium-project/classic-bug-tracker#937]
Zap Farflinger the NPC in Everlook(winterspring) usually gives you a transporter trinket if you have goblin engieneering over 260, i have 300 and i get nothing... tried del interface and wdb and even made a fresh non addon client and still nothing.

P.S. your game masters are useless.

**Comment by Vasquez-QA** [comment]
Hello,

I am able to speak with the NPC and learn the recipe with no issues (see below)

What is your current reputation with Everlook?
And do you have Goblin Engineer Membership Card in your inventory?

![image](https://user-images.githubusercontent.com/2932176/47735391-52469d80-dc64-11e8-83de-815f42cd5415.png)

![image](https://user-images.githubusercontent.com/2932176/47735424-61c5e680-dc64-11e8-9adc-0e17fd8e5b1b.png)

P.S. I am sorry you feel that way about our GMs.

**Comment by ZicoQA** [comment]
tried on 4 different chars 2 alliance and 2 horde and all of them it is working. Guess the player didn't have the rep for it or the Card in his inventory.
Since it's been so long and no reply from user I will close this

**Comment by banallwowbots** [comment]
Not working on Nethergarde!

I can talk to Zap Farlinger, but once I click "PH Unknown" I am not receiving the skill Dimensional Ripper - Everlook. 

Reputation with Everlook: Honored
Goblin Engineer Membership Card in your inventory:Yes
