### ISSUE TITLE
[Mage talent Ignite] Only one target affected on AoE crits

### ISSUE THREAD

**Issue by WobLight** [elysium-project/classic-bug-tracker#938]
If a spell deals critical strike to multiple targets (Flamestrike/Blastwave) only one is affected by Ignite.
No idea whether this is blizzlike or not, but is sure weird.

**Comment by Thenari** [comment]
Might be a hidden mechanic ignite has an internal cooldown? Unsure if blizz lets ask some mage nerds

**Comment by ZicoQA** [comment]
This is working as intended
