### ISSUE TITLE
Strangelethorn Fever Npc bug

### ISSUE THREAD

**Issue by ilyysae** [elysium-project/classic-bug-tracker#943]
Can't speak with Witch Doctor Unbagwa to start the quest event.

**Comment by ilyysae** [comment]
Hello. NPC 'Doctor Unbagwa' was untargetable even though I had the Stanglethorn Fever quest I waited around for 20mins and it was still untargetable but after 2 hours NPC was targetable. Still not sure what caused it but it seemed normal after that.

**Comment by Vasquez-QA** [comment]
Ok thank you for confirming 👍
