### ISSUE TITLE
Environment Issues

### ISSUE THREAD

**Issue by RogueArc** [elysium-project/classic-bug-tracker#954]
1) Thousand Needles: If you step off a hill (as in running above the creatures) and step off, 1300+ damage. If you step off the lift ramp, at the bottom, before touching the ground texture, 1300+ damage.
2 different characters died this way.

2) STV, Vile Reef: Killing lvl 35-37 Elite Murlocks, Fatigue kills you? DOWN in the water, not going across. And yes I had a Water Breathing potion with 20+ minutes left. 

[WoWScrnShot_111118_034634.zip](https://github.com/elysium-project/classic-bug-tracker/files/2569182/WoWScrnShot_111118_034634.zip)

**Comment by ZicoQA** [comment]
1. Can you be more specific on the hill you are talking about? There are many hills and none that I've tested have given me fall damage. Neither did the lift ramps
2. Couldn't find anywhere which gave me fatigue near the murlocks, please pin point the location

**Comment by ZicoQA** [comment]
this was working fine.
