### ISSUE TITLE
Quest text for Corruptor's Scourgestones & Mantles of the Dawn

### ISSUE THREAD

**Issue by elysiumstarz** [elysium-project/classic-bug-tracker#956]
"Corruptor's Scourgestones" quest text reads "For the Dawn, my g$sister:brother:!"

I experienced this one myself, as well. 

![image](https://user-images.githubusercontent.com/44957725/48324473-be6ebd00-e5e5-11e8-813c-cfdca993a4cc.png)

Quest entitled "Mantles of the Dawn" has "Missing header! (quest designers)" instead of the applicable zone. 

![image](https://user-images.githubusercontent.com/44957725/48324504-e0683f80-e5e5-11e8-99f0-331efd4ddc78.png)

**Comment by elysiumstarz** [comment]
![bug report quest text](https://user-images.githubusercontent.com/44957725/48519878-61f8e100-e823-11e8-91f4-71e78660f00a.PNG)

**Comment by elysiumstarz** [comment]
This is still open

**Comment by RainElysium** [comment]
Fixed on live!
