### ISSUE TITLE
Not dispelling poison from Maexxna when using abolish poison

### ISSUE THREAD

**Issue by Hecama12** [elysium-project/classic-bug-tracker#957]
On Maexxna our Maintank had Abolish poison on and it didnt dispell the poison as you can see in this link. https://www.youtube.com/watch?v=vwO8DO0JICc&feature=youtu.be

**Comment by Lordron** [comment]
i see only one poison on maexxna - necrotic poison (28776) and it get dispelled by abolish poison (2893)

**Comment by Hecama12** [comment]
How can you say that when at 08 he has abolish and necrotic on and at 13 he still have the poison on

**Comment by Ziggy-QA** [comment]
This has been fixed.
