### ISSUE TITLE
Final Blow quest in Felwood

### ISSUE THREAD

**Issue by Joshonenine** [elysium-project/classic-bug-tracker#963]
The quest Final Blow in Felwood is bugged. The NPC's you have to kill go out of combat as soon as you engage them. Two seconds after my frostbolt hit one of them, they all 3 deaggro'd and returned to their original spots. I thought it was a distance thing, like you can't kite them, but I stood right on top of them and they would literally aggro and deaggro every second. Incredibly frustrating seeing as how you gotta kill about 30 things to get down into that cave to kill them only for them to bug out and not be able to complete the quest. Thanks for any help.

**Comment by Vasquez-QA** [comment]
Hello,

Sorry to hear that you are having problems with this quest.

I have not been able to replicate the issue and could not get them to evade.

Are you still having the problem?

Please confirm.

Thanks

**Comment by ZicoQA** [comment]
This quest is working as intended. Please clear your WDB folder and try again. If you experience further issues please elaborate what is making the quest bug
