### ISSUE TITLE
Missing Mob for Quest - Ursal the Mauler -

### ISSUE THREAD

**Issue by erxkum** [elysium-project/classic-bug-tracker#965]
https://www.wowhead.com/npc=2039/ursal-the-mauler is missing from "the Cleft" cave on Teldrassil.

**Comment by Vasquez-QA** [comment]
NPC "Ursal the Mauler" (GUID 2039) spawns in Gnarlpine Hold at approx. 38, 79 (see below)

He was moved to the Cleft Cave in Cataclysm.

![image](https://user-images.githubusercontent.com/2932176/48982740-55577100-f0de-11e8-8281-0059868f5b8e.png)
