### ISSUE TITLE
lvl10 Orc Hunter Quest Problems

### ISSUE THREAD

**Issue by EvilNecroid** [elysium-project/classic-bug-tracker#966]
i got the rod to tame the pig and tamed it no problem but once tamed it wandered around doing its own thing so i just ran away and left it and turned in that quest. then i got the rod for the surf crawler but when i tried to tame it it said failed because i still had the pig as a pet. so i tried to dismiss the pig but couldnt so i had to relog and then the pig was gone. then i tamed the surf crawler but again it just wandered around doing its own thing so i dismissed it right away and it attacked me and almost killed me because i was still hurt from taming it. anyway i got the rod to tame the scorpion and once again it just wandered around doing its own thing. i tried to tell it to attack a near by pig and it just said "i cant attack that target" so i was forced to dismiss and fight the scorpion so i could finish the quest.

**Comment by EvilNecroid** [comment]
um i just ran back past the pig like 3 or 4 hours later and its still there tamed and wandering

**Comment by ZicoQA** [comment]
This quest is working as intended. When you use the item, the pet is tamed as suppose to. You have to dismiss it before you can tame another pet, as a Hunter cannot have two pets at the same time. The thing is this is different as the normal hunter spell as the item doesn't despawn the pet, it releases it back to wild. As you can read on the quest text he says for you to practice with the pet
