### ISSUE TITLE
Cant access Extra Chars #1 Server

### ISSUE THREAD

**Issue by EvilNecroid** [elysium-project/classic-bug-tracker#968]
On the server list i can see an (8) next to the Extra Chars #1 server so im guessing i must have old chars from ages ago on there but when i click it it says loading for like 1 second and then just kicks me back to the server list. i tried deleting my WDB folder and that does nothing.
i told a GM about it and he said he would get back to me but that was last week.

**Comment by MadmanKel** [comment]
I alsohave a character there, from what I've found out, it's from their old Anathema server, which was hacked last year, and they did bring characters back. I did talk to them face to face in game, and they said they should be bringing those guys into the server upon TBC dropping, which is soon.
