### ISSUE TITLE
Feign Death bug

### ISSUE THREAD

**Issue by Lecia2134** [elysium-project/classic-bug-tracker#969]
You can pull three mobs, and have your pet attack one, pull it back and feign death and the two that you didnt touch (after initial pull) will reset. Obviously not game breaking, but it definitely makes a difference.

**Comment by Kristoferhh** [comment]
This is very much intended, not a bug. It's called Feign Death pulling.

**Comment by spectras** [comment]
I used to do that in vanilla as well, so does not sound like a bug.
