### ISSUE TITLE
Gurubashi Arena Trinket

### ISSUE THREAD

**Issue by eridaisback** [elysium-project/classic-bug-tracker#970]
Hey could I have your help plz. 
Gurubashi arena chest bugged thrice already for my twink, not sure if its because of taking the quest but I've tried everything to fix it and cant loot the trinket anymore and General from staff told me to also report it here. I'm losing progress each 3 hours due to this, on top of having already lost 3 trinkets which I actually couldnt loot off the chest, feels like a big loss and dissapointment.
This puts extra stress on the arena event and makes people really unhappy to see me there more often than needed.

When I open the chest I'm able to see and loot everything except the arena master trinket
 this is what it look likes(notice chat I've looted items):
https://imgur.com/a/T0sd0eJ

**Comment by Vasquez-QA** [comment]
Hello,

I have been able to loot the chest with no issues (see below) but I will try to replicate the issue for you. Leave it with us.

![image](https://user-images.githubusercontent.com/2932176/48982147-4e2c6500-f0d6-11e8-93c6-bc1430e9f110.png)

**Comment by ZicoQA** [comment]
I've done exactly as you taking the quest I can still loot. Have you tried clearing you wdb folder and looting again?

**Comment by ZicoQA** [comment]
Tested on 4 different chars, 2 alliance, 2 hordes, one low level. All have it working.
