### ISSUE TITLE
Mining nodes have to be mined repeatedly to get all ore/stone/etc

### ISSUE THREAD

**Issue by TheGreyMouser** [elysium-project/classic-bug-tracker#973]

**Comment by TheGreyMouser** [comment]
When mining any ore node, you have to click it several times, getting 1 ore per click up to the contents of the node.  Example node has 3 copper.. you have to mine that node 3 times.  VS Skinning you skin each beast once to get 1 to 3 leather and vs herbalism where you pick the herb node only once to get 1 to 3 herbs.  To be fair to all, this needs to be fixed to mine node one to get all ore or adjust skinning and herb picking to you have to skin or pick the same herb several times.  I prefer to mine each node only once, but fair is fair.

**Comment by Vasquez-QA** [comment]
Mining nodes in this fashion in blizz-like for Vanilla and as such working as intended. 

Prior to Patch 3.0.8, mining a node completely required multiple attempts, one for each unit of ore.
