### ISSUE TITLE
Warsong Gulch Mark of Honor Retrieval Issue

### ISSUE THREAD

**Issue by imisterk** [elysium-project/classic-bug-tracker#974]
- Snip - 

Marks being unique is the bloody problem. *facedesk*

**Comment by Vasquez-QA** [comment]
Ca you elaborate on this report please?

You can carry up to 20 at a time?

**Comment by imisterk** [comment]
Hi Vasquez. I think it was intended to work like this as the WSG Marks are 'Unique' to 20, hence why I am unable to open them in the mailbox.
