### ISSUE TITLE
Alchemy . Transmute : water to death

### ISSUE THREAD

**Issue by Onemorepint** [elysium-project/classic-bug-tracker#980]
Hello , few days ago i learned the recipe transmute death to water . The day after i logged in the recipe was completely unlearned. 
I bought off the actuion house a new recipe and learned it.
3 days later it happened the same , the  recipe was unlearned.

It s not just it doesnt show on the alchemy list. it s not known , because if i click on a recipe it doesnt show "already known"

Am i the only one who is happening this bug ?

Edit:
i ve noticed as well the cd for transmute today is even longer than yesterday .... still i havent transmuted today .  ti gives me more than 1 day of cd .  please clue me in :(

**Comment by ZicoQA** [comment]
Suspect player error. no response.
