### ISSUE TITLE
Wrecked boat not continuing quest in Feralas

### ISSUE THREAD

**Issue by nclsmitchell** [elysium-project/classic-bug-tracker#993]
The Missing Courier quest is stucked in Feralas as the Wrecked boat is just saying « Greetings » instead of validating the first step of the quest.

Thank you in advance for your help.

Skylux

**Comment by ZicoQA** [comment]
This is what is showing for me on all my chars:
![image](https://user-images.githubusercontent.com/46020855/52066021-a3ba3d80-256f-11e9-93e3-9b5894cdc94e.png)

Did you click on the boat under water and it said "Greetings"? 
Have you tried login in and out? clearing your wdb folder?

**Comment by ZicoQA** [comment]
Unable to replicate. Might be client side. Closed
