### ISSUE TITLE
Bugged twink items

### ISSUE THREAD

**Issue by SingleDuplo** [elysium-project/classic-bug-tracker#994]
There are some items from Sunken Temple whick could be obtained by low lvl character at the start of the server (in early patch). Later patch fixed out that and those items don't drop anymore using that bugged way. But some players still have those items and use it for twinks. So it's really unfair when somebody have an advantage and others can get the same gear. 
The items are;
Mark of Hakkar - ring
Hakkari Breastplate - leather chest
Hakkari Shroud - cloth head
I think it's obvious that these items is overpowered for 19 lvl twink.

By the way, for your information. There was a bug that low lvl Shimmering Gloves had stats +22/22 in early patch and then it has been fixed. I had these gloves and one day i logged on and found empty slot instead of it. 
So i think it would be fair to do the same with Hakkari gear.

**Comment by Ziggy-QA** [comment]
@SingleDuplo this isn't really a bug, rather its an issue regarding fairness, and best directed towards a GM. Please submit an in-game ticket.
