### ISSUE TITLE
Metzen the Reindeer for the mission Metzen the Reindeer doesn't spawn

### ISSUE THREAD

**Issue by odarian-elysium** [elysium-project/classic-bug-tracker#996]
NPC Metzen the Reindeer for the christmas quest chain doesn't spawn making the completion impossible:
https://classicdb.ch/?quest=8746

Expected behaviour: Should spawn in both Searing Gorge and Tanaris at the locations indicated on classicdb.

Bugged behaviour: Doesn't spawn in either of the locations.

Reproduce: Go to either coordinates 68.8 / 34.2 in Searing Gorge or 72.3 / 48.1 in Tanaris where he should spawn with a 3 minute respawn window according to classicdb.

**Comment by Ziggy-QA** [comment]
@odarian-elysium 

This issue has already been placed on the developer to do list, but thank you for the bug report! :)

**Comment by RainElysium** [comment]
Fixed.
