### ISSUE TITLE
Can't take quest in Felwood

### ISSUE THREAD

**Issue by lavanth** [elysium-project/classic-bug-tracker#999]
Hello. For some reasons can't take the 3rd quest from the chain in Felwood from Greta Mosshoof. The name of the quest is "Seeking Spiritual Aid". The req level is 48, but my char is 49 and still can't get it.
Thanks!

**Comment by ZicoQA** [comment]
Looks fine for me. Did you wait a while for her to go and return?

**Comment by ZicoQA** [comment]
No response for player. Can be client side. will reopen if more bugs appear
